#!/usr/bin/env python3
"""Every number the FUSION-PARTNER manuscript prints, tied to the artifact field that computes it.

⛔ WHY THIS EXISTS — THE SAME ONE-OF-A-PAIR SHAPE, ONE PAPER OVER.
`research/manuscripts/fusion-partner/emc-fusion-partner-stratification.md` states in its own opening
that **every number below has one home**: `emc-fusion-partner-pooling.json`, generated by
`emc_fusion_partner_pooling.py`. The artifact side of that promise is guarded —
`test_emc_fusion_partner_pooling_check.py` proves `--check` refuses a hand-edited artifact — but
**nothing read the prose against it**. Measured 2026-08-26: 94 test modules name the sibling
`fusion-junction-aso` submission and 2 name `fusion-partner`, neither a numbers guard. So a figure
could drift in the manuscript, disagree with the artifact that produces it, and every test in the
repository would still pass.

That is not hypothetical for this document. Four rounds of blind adversarial review took its blocker
count 3 -> 2 -> 9, and several of the nine were exactly this class, each found by a human-equivalent
reader one round after it was introduced:

  * "of its 16 citation records, 11 carry a `verification_note`" — the artifact's count was 12;
  * two appendix rows pointed at `analyses.B_outcome_by_partner.counter_signal.metastasis_reading`,
    a key that does not exist (the real one is `analyses.B_outcome_by_partner.metastasis_reading`);
  * `cohorts_identified` / `cohorts_pooled` were TYPED into the generator and undercounted the
    moment a cohort was added;
  * an analysis verdict stated a claim absolutely where the prose stated it bounded.

⛔⛔ EVERY SITE THAT STATES THE QUANTITY, NOT WHETHER IT APPEARS SOMEWHERE. The sibling guard
(`test_journal_article_numbers.py`) first asserted `value in prose` and a mutation test walked
through three of nine corruptions, because one figure stood at three sites and corrupting ONE left
the others standing. Every assertion here therefore captures the number out of the CONSTRUCTION that
states it and checks EVERY match, via `re.findall` in the parametrized test below. Counted in the
committed text: "46.7" appears 4 times, "10.3" 6, "78 %" 6, "18.2" 6, "0.0034" 6, "24.8–69.9" 4,
"30.60" 3 and "43.4" 3 — so the failure mode is not hypothetical for this document either.

⛔ THE ASSERTIONS ARE ON DERIVED VALUES, NEVER ON REMEMBERED ONES. Each binding computes what the
prose should say from the artifact and looks for that. A failure means the manuscript and its
evidence have diverged — fix whichever is wrong, but do not relax the binding, and never paste the
artifact's current value in as a literal to make it green.

⚠ ROUNDING AND FORMATTING, HANDLED EXPLICITLY RATHER THAN BY LOOSENING THE MATCH.
The generator already rounds every rate to ONE decimal before writing it (`percent`,
`ci95_lo_percent`, `ci95_hi_percent`, `comparator_minus_taf15_percentage_points`), so there is no
second rounding decision to make here and `_pct` is a pure `%.1f` render of the committed float.
Three formats differ from the artifact's own and each is converted, not tolerated:
  * hazard ratios print with two decimals in the prose ("HR 30.60") and are stored as `30.6` — `_hr`;
  * the sources' own p-values print without the leading zero ("P = .004") and are stored as `0.004`
    — `_pubp`;
  * a handful of counts reach the page as WORDS ("three", "fifty-eight") — `_word`, which raises on
    an unmapped value rather than guessing.

⭐ MEASURED, 2026-08-26 — 36 of 36 mutations caught, 22 of them SINGLE-SITE.
Each mutation was applied to a `cp -al` clone (never the working tree), written as a new file and
`os.replace`d so the shared inode could not carry it back, and asserted LANDED by digest and by
occurrence count BEFORE the gate's answer was read — a mutation that never applies reports exactly
what a guard that never fires reports. An unmutated clone was run first as the positive control.
The set: 22 single-site corruptions of figures stated at 2-5 sites each (46.7 % at all three of its
homes in turn, 18.2 % at two of its five, 0.0034, 78 %, HR 30.60, 23, 9.2, 43.4, and both appendix
restatements); 2 arm swaps that leave every digit correct; 8 corruptions of a figure with a single
home; a pointer typo; an unbound figure inserted into the prose; and 6 GENERATOR mutations
regenerated through `emc_fusion_partner_pooling.py`, which is the edit that would really happen.
⚠ ONE FINDING FROM THE HARNESS ITSELF, recorded because it cost a restore: the generator writes its
artifact IN PLACE, the clone shares the inode, and the first run regenerated a MUTATED artifact
straight into the working tree. Break the link before regenerating — `cp -al` is not isolation.

⚠ WHAT IS DELIBERATELY NOT BOUND, AND WHY IT IS ENUMERATED RATHER THAN LEFT OUT.
Some printed numbers are not the artifact's to own: the 95 % confidence LEVEL, which the evidence
contract fixes and the artifact only ever echoes; the "≈27 %" the field quotes, which this paper
exists partly to correct; a figure whose one home is a different artifact; a DOI that happens to
contain a slash between digits; and a retained SUPERSEDED quotation whose whole purpose is to
preserve a number this document no longer asserts.
Excluding those silently would make the guard's coverage a matter of whatever happened to pass, so
they are declared in `DECLARED_NOT_ARTIFACT_OWNED` with a reason class, and
`test_every_fraction_and_percentage_is_bound_or_declared` fails on any printed fraction or rate that
is in neither bucket. That census is what stops the exclusion list growing to make the guard green.
"""
from __future__ import annotations

import json
import os
import re

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
MANUSCRIPTS = os.path.dirname(HERE)
FP = os.path.join(MANUSCRIPTS, "fusion-partner")

PAPER = os.path.join(FP, "emc-fusion-partner-stratification.md")
ARTIFACT = os.path.join(FP, "emc-fusion-partner-pooling.json")

pytestmark = pytest.mark.committed_artifact


def _required(path, what):
    """⛔ An artifact that is not there is a finding, never a silent pass.

    Both paths are `git ls-files`-tracked, so absence is a broken tree rather than a partial
    checkout, and a guard that disappears with its input is indistinguishable from one that never
    ran.
    """
    if not os.path.exists(path):
        pytest.fail(f"{what} is missing at {path}. It is committed, so restore or regenerate it "
                    "rather than passing over the assertions that depend on it.")
    return path


def _load_prose():
    return open(_required(PAPER, "the fusion-partner manuscript"), encoding="utf-8").read()


def _load_artifact():
    return json.load(open(_required(ARTIFACT, "the fusion-partner pooling artifact"),
                          encoding="utf-8"))


def _flat(text):
    """The prose with hard wrapping collapsed and markdown emphasis removed.

    Two normalisations, both for the same reason — a pattern must bind the SENTENCE, not the
    typography around it:

      * the manuscript wraps at ~110 columns, so nearly every construction worth binding straddles
        a line break ("mean size\\n(13.7 vs 7.3 cm, P = .024)");
      * the same quantity is bolded in one section and plain in another (the abstract's
        "**one enters the primary pool**" against §5's "**one** enters the primary pool"), so a
        pattern written against one placement of `**` silently stops matching at the other — and a
        pattern that has stopped matching is a guard that has silently stopped guarding.

    ⚠ Removing `*` is safe in THIS document and the census proves it rather than assuming it: the
    only asterisks it contains are emphasis and gene-name italics.
    """
    return re.sub(r"\s+", " ", text).replace("*", "")


def _pct(x):
    """A rate as the manuscript prints it. The artifact stores it already rounded to one decimal."""
    return f"{float(x):.1f}"


def _fisher(x):
    """A post-hoc Fisher p as both the artifact and the prose print it.

    ⚠ `%g` IS THE WRONG RENDER HERE and it was the first thing tried: it turns `1.0` into `1`, and
    the trial-alone contrast really does print "1.0" in the abstract and in §3.1's table. `repr` of
    the loaded float is the shortest round-trip form, which is exactly what the generator wrote.
    """
    return repr(float(x))


def _hr(x):
    """A hazard ratio as the prose prints it — two decimals ("HR 30.60") over a stored `30.6`."""
    return f"{float(x):.2f}"


def _pubp(x):
    """A SOURCE'S OWN p-value as the prose prints it: no leading zero ("P = .004" for `0.004`).

    ⚠ These are the published papers' tests quoted verbatim, not the post-hoc Fisher values this
    repository computes; the artifact keeps them apart (`published_p_values` versus
    `fisher_exact_two_sided_p`) and so does every binding below.
    """
    s = f"{float(x):g}"
    assert s.startswith("0."), f"a published p-value of {x} is not of the form 0.xxx"
    return s[1:]


_WORDS = {0: "zero", 1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven",
          8: "eight", 9: "nine", 10: "ten", 11: "eleven", 12: "twelve", 13: "thirteen",
          14: "fourteen", 58: "fifty-eight"}


def _word(n):
    """A count that reaches the page as a WORD is still a count, and binding it as one is the point.

    ⛔ RAISES ON AN UNMAPPED VALUE rather than falling back to digits: the failure this file exists
    for is a number changing, and a helper that quietly renders `four` as `4` when the artifact
    moves from three to four would make exactly that change invisible.
    """
    n = int(n)
    if n not in _WORDS:
        raise KeyError(f"{n} has no spelled-out form here; add it deliberately, do not guess")
    return _WORDS[n]


def _frac(stratum):
    """`events/denom` exactly as the prose prints a stratum."""
    return f"{int(stratum['events'])}/{int(stratum['denom'])}"


def _lr_pair(a):
    """Both cohorts' local-recurrence arms, in the order §3.3 states them.

    ⚠ ONE CONSTRUCTION, EIGHT GROUPS, ON PURPOSE. The sentence's whole point is that the two cohorts
    run in OPPOSITE directions; binding each rate separately would let a swap that keeps every digit
    correct pass, which is the arm-swap mutation class this file already carries two cases of.
    """
    pc = a["analyses"]["B_outcome_by_partner"]["local_recurrence"]["per_cohort"]
    out = []
    for cohort in ("agaram-2014-outcome", "huang-2023-outcome"):
        for arm in ("TAF15::NR4A3", "EWSR1::NR4A3"):
            out += [_frac(pc[cohort][arm]), _pct(pc[cohort][arm]["percent"])]
    return tuple(out)


def _prev_pooled(a):
    """The prevalence pool's TAF15 events and denominator, re-derived from the pooled records."""
    pooled = a["analyses"]["C_partner_prevalence"]["cohorts_pooled"]
    by_id = _by_id(a)
    ev = sum(by_id[c]["counts"]["TAF15::NR4A3"] for c in pooled)
    dn = sum(sum(by_id[c]["counts"].values()) for c in pooled)
    return ev, dn


def _prev_shares(a):
    """Per-cohort TAF15 share for every pooled prevalence series, as the prose rounds it."""
    by_id = _by_id(a)
    return {c: round(100.0 * by_id[c]["counts"]["TAF15::NR4A3"]
                     / sum(by_id[c]["counts"].values()), 1)
            for c in a["analyses"]["C_partner_prevalence"]["cohorts_pooled"]}


def _prev_pct(a, cohort_id):
    return _pct(_prev_shares(a)[cohort_id])


def _sjogren(a):
    c = _by_id(a)["sjogren-2003-prevalence"]["counts"]
    return c["TAF15::NR4A3"], sum(c.values())


def _sjogren_frac(a):
    ev, dn = _sjogren(a)
    return f"{ev}/{dn}"


def _sjogren_pct(a):
    ev, dn = _sjogren(a)
    return _pct(round(100.0 * ev / dn, 1))


def _prev_counterfactual_frac(a):
    ev, dn = _prev_pooled(a)
    sev, sdn = _sjogren(a)
    return f"{ev + sev}/{dn + sdn}"


def _prev_counterfactual_pct(a):
    ev, dn = _prev_pooled(a)
    sev, sdn = _sjogren(a)
    return _pct(round(100.0 * (ev + sev) / (dn + sdn), 1))


# =================================================================================================
# The bindings.
#
# Each is (what, pattern, value, fold) where `value` is computed FROM THE ARTIFACT and `pattern`
# captures the same quantity out of the construction that states it. A one-group pattern expects a
# string; a multi-group pattern expects a tuple, so a pair of numbers stated together cannot drift
# apart — which is why a table row is one binding rather than six.
# =================================================================================================

BINDINGS = []


def bind(what, pattern, value, fold=False):
    """Register one binding.

    `fold=True` compares case-insensitively and is used ONLY where the captured value is a count
    spelled as a WORD: the same count opens a sentence as "Three" in the abstract and sits
    mid-sentence as "three" in §2.5, and capitalisation is a typographic fact about position rather
    than a claim about the evidence. ⛔ It is never set on a binding that captures digits, where
    every character is part of the number.
    """
    BINDINGS.append((what, pattern, value, fold))
    return pattern


def _by_id(art):
    return {c["id"]: c for c in art["cohorts"]}


def _endpoint(art, endpoint):
    return [c for c in art["cohorts"] if c["endpoint"] == endpoint]


TKI = "objective_response_antiangiogenic_tki"
OUT = "outcome_by_partner"
PREV = "partner_prevalence"

# ------------------------------------------------------------------ A · TKI objective response ---

# ⛔ THE ROSTER IS RE-DERIVED FROM THE COHORT RECORDS, NOT READ OUT OF THE TYPED COUNT.
# `analyses.A_tki_objective_response` still TYPES `cohorts_identified: 3` and
# `cohorts_pooled_primary: 1` — the `_roster()` repair of 2026-08-26 was applied to analysis B and
# not to A, which is §8b.2's list-scoped fix regressing at a sibling. Binding the prose to the typed
# field would inherit the same blind spot, so the prose is bound to the RECORDS and the typed field
# is asserted against them separately, below.
bind("the number of TKI-response cohorts identified, and how many enter the primary pool "
     "(Abstract and Appendix A15)",
     r"(\w+) reports give objective response by partner and (\w+) enters the primary pool",
     lambda a: (_word(len(_endpoint(a, TKI))),
                _word(sum(1 for c in _endpoint(a, TKI) if c["pool"]))), fold=True)

bind("the same two counts as §3.1 states them",
     r"— (\w+), of which (\w+) enters the primary pool",
     lambda a: (_word(len(_endpoint(a, TKI))),
                _word(sum(1 for c in _endpoint(a, TKI) if c["pool"]))), fold=True)

bind("the TAF15 response arms of both analyses, as the abstract states them",
     r"(\d+) of (\d+) in the primary analysis, (\d+) of (\d+) if the two reports are independent",
     lambda a: (
         str(a["analyses"]["A_tki_objective_response"]["primary_non_overlapping"]["contrast"]
              ["taf15_arm"]["events"]),
         str(a["analyses"]["A_tki_objective_response"]["primary_non_overlapping"]["contrast"]
              ["taf15_arm"]["denom"]),
         str(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]["contrast"]
              ["taf15_arm"]["events"]),
         str(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]["contrast"]
              ["taf15_arm"]["denom"])))

# ⭐ THE UPPER-BOUND RANGE AND BOTH COMPARATOR POINT ESTIMATES IN ONE CONSTRUCTION, because the
# sentence's whole force is that the bound sits ABOVE both — checking them separately would let a
# repair move one and leave the comparison reading as though it still held.
bind("the TAF15 upper-bound range beside the two comparator point estimates it is claimed to exceed",
     r"upper bound on the TAF15 response rate is (\d+\.\d) % to (\d+\.\d) %, which sits above the "
     r"comparator arm's point estimate in both analyses \((\d+\.\d) % and (\d+\.\d) %\)",
     lambda a: (
         _pct(a["analyses"]["A_tki_objective_response"]["overlap_sensitivity_bounds"]
               ["taf15_upper_ci_range_percent"][0]),
         _pct(a["analyses"]["A_tki_objective_response"]["overlap_sensitivity_bounds"]
               ["taf15_upper_ci_range_percent"][1]),
         _pct(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]["contrast"]
               ["comparator_arm"]["percent"]),
         _pct(a["analyses"]["A_tki_objective_response"]["primary_non_overlapping"]["contrast"]
               ["comparator_arm"]["percent"])))

bind("both Fisher p-values for analysis A, as the abstract pairs them",
     r"Fisher exact two-sided p = (\d+(?:\.\d+)?) pooled, (\d+(?:\.\d+)?) for the trial alone",
     lambda a: (
         _fisher(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]["contrast"]["fisher_exact_two_sided_p"]),
         _fisher(a["analyses"]["A_tki_objective_response"]["primary_non_overlapping"]["contrast"]["fisher_exact_two_sided_p"])))

bind("§3.1's primary-analysis table row, whole",
     r"\| Primary \(pazopanib trial alone, POLICY-conformant\) \| (\d+)/(\d+) \| (\d+)/(\d+) = "
     r"(\d+\.\d) % \| (\d+\.\d) % \| (\d+(?:\.\d+)?) \|",
     lambda a: _row(a["analyses"]["A_tki_objective_response"]["primary_non_overlapping"]["contrast"],
                    a["analyses"]["A_tki_objective_response"]["overlap_sensitivity_bounds"]
                     ["taf15_upper_ci_range_percent"][1]))

bind("§3.1's secondary-analysis table row, whole — INCLUDING the per-cohort range added in round "
     "4, so the pooled rate and the two rates it averages cannot drift apart",
     r"\| Secondary \(both cohorts, assumes independence\) \| (\d+)/(\d+) \| (\d+)/(\d+) = "
     r"(\d+\.\d) % — per cohort \d+\.\d % \(pazopanib, \d+/\d+\) and \d+\.\d % "
     r"\(sunitinib, \d+/\d+\), spread \d+\.\d pts \| (\d+\.\d) % \| (\d+(?:\.\d+)?) \|",
     lambda a: _row(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]["contrast"],
                    a["analyses"]["A_tki_objective_response"]["overlap_sensitivity_bounds"]
                     ["taf15_upper_ci_range_percent"][0]))


def _row(contrast, upper):
    """A §3.1 table row: TAF15 events/denom, comparator events/denom = percent, upper bound, p."""
    return (str(contrast["taf15_arm"]["events"]), str(contrast["taf15_arm"]["denom"]),
            str(contrast["comparator_arm"]["events"]), str(contrast["comparator_arm"]["denom"]),
            _pct(contrast["comparator_arm"]["percent"]), _pct(upper),
            _fisher(contrast["fisher_exact_two_sided_p"]))


bind("the unevaluable-patient sensitivity analysis: both strata and the bound they move",
     r"the strata become (\d+)/(\d+) and (\d+)/(\d+); the TAF15 upper bound rises to (\d+\.\d) %",
     lambda a: _sens(a))


def _sens(a):
    s = a["analyses"]["A_tki_objective_response"]["sensitivity_analyses"]["taf15_patient_not_evaluable"]
    return (str(s["taf15_arm"]["events"]), str(s["taf15_arm"]["denom"]),
            str(s["comparator_arm"]["events"]), str(s["comparator_arm"]["denom"]),
            _pct(s["taf15_arm"]["ci95_hi_percent"]))


bind("§5's restatement of the response evidence, with the denominator range and both bounds",
     r"(\d+) of (\d+)–(\d+) TAF15::NR4A3 patients, with a 95 % upper bound of (\d+\.\d)–(\d+\.\d) %",
     lambda a: _bounds(a))


def _bounds(a):
    b = a["analyses"]["A_tki_objective_response"]["overlap_sensitivity_bounds"]
    return (str(b["taf15_events"]), str(b["taf15_denominator_range"][0]),
            str(b["taf15_denominator_range"][1]),
            _pct(b["taf15_upper_ci_range_percent"][0]), _pct(b["taf15_upper_ci_range_percent"][1]))


# ⚠ APPENDIX A15 RESTATES BOTH CONTRASTS' RAW STRATA — a fourth home for the primary pair and a
# third for the secondary. The appendix is not exempt from binding: A19 is in this document because
# an appendix row got a count wrong.
bind("Appendix A15's restatement of both contrasts' strata",
     r"the primary contrast was always the trial alone \((\d+)/(\d+) vs (\d+)/(\d+)\) and the "
     r"secondary always both \((\d+)/(\d+) vs (\d+)/(\d+)\)",
     lambda a: _strata(a))


def _strata(a):
    out = []
    for key in ("primary_non_overlapping", "secondary_assume_independent"):
        c = a["analyses"]["A_tki_objective_response"][key]["contrast"]
        for arm in ("taf15_arm", "comparator_arm"):
            out += [str(c[arm]["events"]), str(c[arm]["denom"])]
    return tuple(out)


bind("§4.5's statement that the headline denominator is a range",
     r"headline denominator is a range \((\d+) to (\d+)\)",
     lambda a: tuple(str(x) for x in a["analyses"]["A_tki_objective_response"]
                                      ["overlap_sensitivity_bounds"]["taf15_denominator_range"]))

# ⭐ THE FALSIFIER'S ARITHMETIC IS DERIVED, NOT QUOTED. "one response moves the point estimate to
# 20-33 %" is 1/5 and 1/3 at the two ends of the denominator range; typing it would make §6's
# shortest falsifier a third home for a fact the range already owns.
bind("§6's falsifier #1 — the denominator range and what one response would make of it",
     r"With a denominator of (\d+)–(\d+), a single response moves the point estimate to (\d+)–(\d+) %",
     lambda a: _falsifier(a))


def _falsifier(a):
    lo, hi = a["analyses"]["A_tki_objective_response"]["overlap_sensitivity_bounds"]["taf15_denominator_range"]
    return (str(lo), str(hi), str(round(100 / hi)), str(round(100 / lo)))


bind("§1.1's reading of the pazopanib trial: responders over the evaluable set",
     r"reported (\d+) objective responses among (\d+) evaluable patients",
     lambda a: (str(_by_id(a)["pazopanib-NCT02066285"]["strata"]["non-TAF15"]["events"]),
                str(_by_id(a)["pazopanib-NCT02066285"]["n_assessable"])))

bind("§3.1's comparator-arm denominator, at the site that warns what it may contain",
     r"the (\d+) comparator patients may include",
     lambda a: str(_by_id(a)["pazopanib-NCT02066285"]["strata"]["non-TAF15"]["denom"]))

bind("§3.2's inclusion-table row for the pazopanib trial",
     r"pazopanib phase 2, NCT02066285, (\d+) evaluable",
     lambda a: str(_by_id(a)["pazopanib-NCT02066285"]["n_assessable"]))

bind("§3.2's inclusion-table row for the sunitinib series",
     r"sunitinib named-use series, n = (\d+)",
     lambda a: str(_by_id(a)["sunitinib-2014"]["n_treated"]))

# ⛔ THE STRATUM EXTENT §2.5 REFUSES A RANDOM-EFFECTS MODEL ON. The artifact derives it on every
# regeneration (`_stratum_extent`) and states it inside `method.not_used`; the prose spells it out in
# words. Both halves are read from the artifact string rather than recomputed here, because
# recomputing it would be a SECOND implementation of the generator's own choice of which strata
# count — and that choice, not the arithmetic, is the thing that went stale for eighteen days.
bind("§2.5's per-stratum denominator and event range, spelled out",
     r"denominator runs from (\w+) \(TAF15, primary TKI analysis\) to ([\w-]+) \(EWSR1, pooled "
     r"outcome\) and the event count from (\w+) \(TAF15 response, either analysis\) to (\w+) "
     r"\(EWSR1 distant metastasis\)",
     lambda a: tuple(_word(int(x)) for x in _extent(a)), fold=True)


def _extent(a):
    m = re.search(r"the per-stratum denominator runs from (\d+) to (\d+) and the event count from "
                  r"(\d+) to (\d+)", a["method"]["not_used"])
    assert m, ("`method.not_used` no longer states the derived stratum extent in the form this "
               "guard reads; the generator's `_stratum_extent` output has moved")
    return (m.group(1), m.group(2), m.group(3), m.group(4))


# ----------------------------------------------------------------------- B · outcome by partner ---

bind("the abstract's pooled disease-specific-death contrast, whole: pool size, both arms, both "
     "intervals, the gap and its p",
     r"Pooled over (\d+) patients, disease-specific death is (\d+)/(\d+) = (\d+\.\d) % "
     r"\(95 % CI (\d+\.\d)–(\d+\.\d)\) with TAF15::NR4A3 against (\d+)/(\d+) = (\d+\.\d) % "
     r"\(95 % CI (\d+\.\d)–(\d+\.\d)\) with EWSR1::NR4A3 — a (\d+\.\d)-point gap, post-hoc "
     r"Fisher p = (\d+(?:\.\d+)?)",
     lambda a: (_pool_n(a),) + _contrast(a, "disease_specific_death"))


def _pool_n(a):
    """73 is the pooled outcome denominator and is DERIVED — the two arms summed, never typed."""
    d = a["analyses"]["B_outcome_by_partner"]["disease_specific_death"]
    return str(d["taf15_arm"]["denom"] + d["comparator_arm"]["denom"])


def _contrast(a, key):
    c = a["analyses"]["B_outcome_by_partner"][key]
    return (str(c["taf15_arm"]["events"]), str(c["taf15_arm"]["denom"]),
            _pct(c["taf15_arm"]["percent"]), _pct(c["taf15_arm"]["ci95_lo_percent"]),
            _pct(c["taf15_arm"]["ci95_hi_percent"]),
            str(c["comparator_arm"]["events"]), str(c["comparator_arm"]["denom"]),
            _pct(c["comparator_arm"]["percent"]), _pct(c["comparator_arm"]["ci95_lo_percent"]),
            _pct(c["comparator_arm"]["ci95_hi_percent"]),
            _pct(abs(c["comparator_minus_taf15_percentage_points"])),
            _fisher(c["fisher_exact_two_sided_p"]))


bind("the abstract's two no-separation endpoints, in the order it prints them",
     r"Local recurrence \((\d+\.\d) % vs (\d+\.\d) %\) and distant metastasis "
     r"\((\d+\.\d) % vs (\d+\.\d) %\)",
     lambda a: (_pct(a["analyses"]["B_outcome_by_partner"]["local_recurrence"]["taf15_arm"]["percent"]),
                _pct(a["analyses"]["B_outcome_by_partner"]["local_recurrence"]["comparator_arm"]["percent"]),
                _pct(a["analyses"]["B_outcome_by_partner"]["distant_metastasis_after_presentation"]["taf15_arm"]["percent"]),
                _pct(a["analyses"]["B_outcome_by_partner"]["distant_metastasis_after_presentation"]["comparator_arm"]["percent"])))

bind("§3.3's disease-specific-death table row, whole",
     r"\| disease-specific death \| (\d+)/(\d+) = (\d+\.\d) % \(95 % CI (\d+\.\d)–(\d+\.\d)\) \| "
     r"(\d+)/(\d+) = (\d+\.\d) % \(95 % CI (\d+\.\d)–(\d+\.\d)\) \| (\d+\.\d) pts \| (\d+(?:\.\d+)?) \|",
     lambda a: _contrast(a, "disease_specific_death"))

bind("§3.3's local-recurrence table row, whole",
     r"\| local recurrence \| (\d+)/(\d+) = (\d+\.\d) % \((\d+\.\d)–(\d+\.\d)\) \| "
     r"(\d+)/(\d+) = (\d+\.\d) % \((\d+\.\d)–(\d+\.\d)\) \| (\d+\.\d) pts \| (\d+(?:\.\d+)?) \|",
     lambda a: _contrast(a, "local_recurrence"))

bind("§3.3's distant-metastasis table row, whole",
     r"\| distant metastasis after presentation \| (\d+)/(\d+) = (\d+\.\d) % \((\d+\.\d)–(\d+\.\d)\) \| "
     r"(\d+)/(\d+) = (\d+\.\d) % \((\d+\.\d)–(\d+\.\d)\) \| (\d+\.\d) pts \| (\d+(?:\.\d+)?) \|",
     lambda a: _contrast(a, "distant_metastasis_after_presentation"))

bind("§3.3's per-cohort death readings, both cohorts and both arms in one construction",
     r"both point the same way: (\d+)/(\d+) = (\d+\.\d) % vs (\d+)/(\d+) = (\d+\.\d) % \(Agaram\) "
     r"and (\d+)/(\d+) = (\d+\.\d) % vs (\d+)/(\d+) = (\d+\.\d) % \(Huang\)",
     lambda a: _per_cohort(a, "disease_specific_death"))


def _per_cohort(a, key):
    """Both cohorts' arms for one endpoint, TAF15 first, in the order §3.3 prints them."""
    pc = a["analyses"]["B_outcome_by_partner"][key]["per_cohort"]
    out = []
    for cid in ("agaram-2014-outcome", "huang-2023-outcome"):
        for arm in ("TAF15::NR4A3", "EWSR1::NR4A3"):
            v = pc[cid][arm]
            out += [str(v["events"]), str(v["denom"]), _pct(v["percent"])]
    return tuple(out)


# ⛔ THE TWO COHORTS' METASTASIS READINGS ARE BOUND SEPARATELY AND IN THE ORDER EACH SENTENCE
# PRINTS THEM. §3.3 states Agaram EWSR1-first and Huang EWSR1-first; Appendix A7 restates Huang
# TAF15-first. A single order-blind pattern would pass on a swap, and a swap is exactly the defect —
# the sign of the reversal is the claim.
bind("§3.3's Agaram-alone metastasis reading, EWSR1 arm first",
     r"Agaram alone has distant recurrence (\d+)/(\d+) = (\d+\.\d) % in EWSR1 against "
     r"(\d+)/(\d+) = (\d+\.\d) % in TAF15",
     lambda a: _cell(a, "distant_metastasis_after_presentation", "agaram-2014-outcome",
                     ("EWSR1::NR4A3", "TAF15::NR4A3")))

bind("§3.3's Huang metastasis reading, EWSR1 arm first",
     r"Huang runs the other way \((\d+)/(\d+) = (\d+\.\d) % EWSR1 vs (\d+)/(\d+) = (\d+\.\d) % TAF15",
     lambda a: _cell(a, "distant_metastasis_after_presentation", "huang-2023-outcome",
                     ("EWSR1::NR4A3", "TAF15::NR4A3")))

bind("Appendix A7's Huang metastasis reading, TAF15 arm first",
     r"direction \((\d+)/(\d+) = (\d+\.\d) % TAF15 vs (\d+)/(\d+) = (\d+\.\d) % EWSR1, "
     r"metastasis after presentation\)",
     lambda a: _cell(a, "distant_metastasis_after_presentation", "huang-2023-outcome",
                     ("TAF15::NR4A3", "EWSR1::NR4A3")))


def _cell(a, key, cid, arms):
    pc = a["analyses"]["B_outcome_by_partner"][key]["per_cohort"][cid]
    out = []
    for arm in arms:
        v = pc[arm]
        out += [str(v["events"]), str(v["denom"]), _pct(v["percent"])]
    return tuple(out)


bind("§3.3's pooled metastasis gap with its p",
     r"the gap is (\d+\.\d) points with overlapping intervals and post-hoc p = (\d+(?:\.\d+)?)",
     lambda a: _gap(a))

bind("§5's restatement of the same gap, beside the published three-way p",
     r"the pooled gap is (\d+\.\d) points with overlapping intervals, and the largest series to "
     r"test it directly reports P = \.(\d+)",
     lambda a: _gap(a)[:1] + (_pubp(a["analyses"]["B_outcome_by_partner"]
                                     ["huang_only_metastasis_readings"]["published_three_way_p"])[1:],))


def _gap(a):
    m = a["analyses"]["B_outcome_by_partner"]["distant_metastasis_after_presentation"]
    return (_pct(abs(m["comparator_minus_taf15_percentage_points"])),
            _fisher(m["fisher_exact_two_sided_p"]))


bind("§3.3's citation of the source's own three-way metastasis p",
     r"reports P = \.(\d+) on its own three-way table",
     lambda a: _pubp(a["analyses"]["B_outcome_by_partner"]["huang_only_metastasis_readings"]
                      ["published_three_way_p"])[1:])

bind("§3.3's Huang-only any-metastasis reading, kept within cohort",
     r"figure \((\d+)/(\d+) vs (\d+)/(\d+)\) within-cohort only",
     lambda a: _any_met(a))


def _any_met(a):
    m = a["analyses"]["B_outcome_by_partner"]["huang_only_metastasis_readings"]["any_distant_metastasis"]
    return (str(m["taf15_arm"]["events"]), str(m["taf15_arm"]["denom"]),
            str(m["comparator_arm"]["events"]), str(m["comparator_arm"]["denom"]))


# ⚠ THE TWO FOLLOW-UP SITES PRINT THE SAME PAIR IN OPPOSITE ORDERS — §3.3 TAF15-first, §4.7
# EWSR1-first — so each is bound to the arm its own sentence names. An order-blind binding would
# pass on the swap that reverses which arm was observed longer, which is the whole caveat.
bind("§3.3's per-arm mean follow-up, TAF15 first",
     r"mean follow-up \((\d+\.\d) vs (\d+\.\d) months, biasing",
     lambda a: (_pct(_by_id(a)["agaram-2014-outcome"]["strata"]["TAF15::NR4A3"]["mean_followup_months"]),
                _pct(_by_id(a)["agaram-2014-outcome"]["strata"]["EWSR1::NR4A3"]["mean_followup_months"])))

bind("§4.7's per-arm mean follow-up, EWSR1 first",
     r"mean follow-up \((\d+\.\d) vs (\d+\.\d) months\) and one that publishes no per-arm follow-up",
     lambda a: (_pct(_by_id(a)["agaram-2014-outcome"]["strata"]["EWSR1::NR4A3"]["mean_followup_months"]),
                _pct(_by_id(a)["agaram-2014-outcome"]["strata"]["TAF15::NR4A3"]["mean_followup_months"])))

bind("the size covariate's published p and hazard ratio, at both sites that pair them",
     r"size > 10 cm \(P = \.(\d+), HR (\d+\.\d+)\)",
     lambda a: (_pubp(_mv(a)["independent_predictors"]["size >10 cm"])[1:],
                _hr(_mv(a)["hazard_ratios"]["size >10 cm"])))

bind("the metastasis-at-presentation covariate's published p and hazard ratio, at both sites",
     r"metastasis at presentation \(P = \.(\d+), HR (\d+\.\d+)\)",
     lambda a: (_pubp(_mv(a)["independent_predictors"]["metastasis at presentation"])[1:],
                _hr(_mv(a)["hazard_ratios"]["metastasis at presentation"])))

bind("§4.7's restatement of both hazard ratios, each against the covariate it belongs to",
     r"\(HR (\d+\.\d+) for size, HR (\d+\.\d+) for metastasis at presentation\)",
     lambda a: (_hr(_mv(a)["hazard_ratios"]["size >10 cm"]),
                _hr(_mv(a)["hazard_ratios"]["metastasis at presentation"])))


def _mv(a):
    return _by_id(a)["huang-2023-outcome"]["multivariable_result"]


def _size(a):
    return _by_id(a)["huang-2023-outcome"]["size_covariate"]


bind("the TAF15 >10 cm share, at every site that prints it",
     r"(\d+) % of (?:that series' )?TAF15 tumours were > 10 cm",
     lambda a: str(round(100 * _size(a)["TAF15::NR4A3"]["over_10cm"]["events"]
                         / _size(a)["TAF15::NR4A3"]["over_10cm"]["denom"])))

bind("§3.4's TAF15 >10 cm share with the source's own p",
     r"\((\d+) %, P = \.(\d+)\)",
     lambda a: (str(round(100 * _size(a)["TAF15::NR4A3"]["over_10cm"]["events"]
                          / _size(a)["TAF15::NR4A3"]["over_10cm"]["denom"])),
                _pubp(_size(a)["published_p_size_over_10cm"])[1:]))

bind("§3.4's exact TAF15 size cell, integers and the share they give",
     r"no such problem: (\d+)/(\d+) = (\d+\.\d) %, printed as (\d+) %",
     lambda a: (str(_size(a)["TAF15::NR4A3"]["over_10cm"]["events"]),
                str(_size(a)["TAF15::NR4A3"]["over_10cm"]["denom"]),
                _pct(round(100 * _size(a)["TAF15::NR4A3"]["over_10cm"]["events"]
                           / _size(a)["TAF15::NR4A3"]["over_10cm"]["denom"], 1)),
                str(round(100 * _size(a)["TAF15::NR4A3"]["over_10cm"]["events"]
                          / _size(a)["TAF15::NR4A3"]["over_10cm"]["denom"]))))

bind("§3.3's second statement of the EWSR1 size cell, beside the source's own p",
     r"were > 10 cm against (\d+)/(\d+) of EWSR1 ones \(P = \.(\d+)\)",
     lambda a: (str(_size(a)["EWSR1::NR4A3"]["over_10cm"]["events"]),
                str(_size(a)["EWSR1::NR4A3"]["over_10cm"]["denom"]),
                _pubp(_size(a)["published_p_size_over_10cm"])[1:]))

bind("§3.3's mean tumour sizes with their SDs and the source's p",
     r"mean size was (\d+\.\d) ± (\d+\.\d) cm vs (\d+\.\d) ± (\d+\.\d) cm \(P = \.(\d+)\)",
     lambda a: (_pct(_size(a)["TAF15::NR4A3"]["mean_cm"]), _pct(_size(a)["TAF15::NR4A3"]["sd_cm"]),
                _pct(_size(a)["EWSR1::NR4A3"]["mean_cm"]), _pct(_size(a)["EWSR1::NR4A3"]["sd_cm"]),
                _pubp(_size(a)["published_p_size_mean"])[1:]))

bind("§3.4's restatement of the two mean sizes",
     r"mean size \((\d+\.\d) vs (\d+\.\d) cm, P = \.(\d+)\)",
     lambda a: (_pct(_size(a)["TAF15::NR4A3"]["mean_cm"]), _pct(_size(a)["EWSR1::NR4A3"]["mean_cm"]),
                _pubp(_size(a)["published_p_size_mean"])[1:]))

# ⭐ THE EWSR1 SIZE CELL IS THE ONE PLACE THE SOURCE DISAGREES WITH ITSELF, AND THE PROSE'S JOB IS TO
# RECORD BOTH READINGS WITHOUT RESOLVING THEM. The integers and every share DERIVED from them are
# bound here; the paper's own printed "28 %" is not the artifact's to own and is declared below.
bind("§3.4's EWSR1 size cell: the integers, the share the SOURCE printed, and the share they give",
     r"> 10 cm cell as (\d+)/(\d+) \((\d+) %\), and (\d+)/(\d+) is (\d+\.\d) %",
     lambda a: _bad_cell(a))


def _bad_cell(a):
    """⭐ THE ONE PLACE THE SOURCE DISAGREES WITH ITSELF, WITH ALL THREE NUMBERS BOUND.

    Huang 2023 prints its EWSR1 >10 cm row as "12/46 (28%)" and 12/46 is 26.1 %. §2.1(2) forbids
    back-deriving a count from a percentage, so the artifact records the INTEGERS as fields and the
    source's printed percentage verbatim inside
    `size_covariate.internal_inconsistency_recorded_not_resolved` — the only home it has, because it
    is not a quantity this synthesis computes. The prose restates all three, so all three are read
    from the artifact: the integers from their fields and the 28 from the recorded sentence.
    """
    ev = _size(a)["EWSR1::NR4A3"]["over_10cm"]["events"]
    dn = _size(a)["EWSR1::NR4A3"]["over_10cm"]["denom"]
    note = _size(a)["internal_inconsistency_recorded_not_resolved"]
    m = re.search(r"as '(\d+)/(\d+) \((\d+)%\)'", note)
    assert m, ("the artifact no longer records the source's printed size row verbatim, so the "
               "prose's account of the discrepancy has nothing to be checked against")
    assert (int(m.group(1)), int(m.group(2))) == (ev, dn), \
        "the recorded sentence and the recorded integers disagree inside the artifact itself"
    return (str(ev), str(dn), m.group(3), str(ev), str(dn),
            _pct(round(100 * ev / dn, 1)))

bind("§3.4's two counterfactual readings of the same cell, both derived from the printed integers",
     r"a denominator of (\d+) gives (\d+\.\d) % and a numerator of (\d+) gives (\d+\.\d) %",
     lambda a: _counterfactuals(a))


def _counterfactuals(a):
    """The two ways the source's own "28 %" could be reconciled — DERIVED, so neither can drift.

    §2.1(2) forbids back-deriving a count from a percentage, so the manuscript names both candidate
    integers and computes neither into the pool. The candidates are the printed numerator and
    denominator moved by one and three respectively, which is what the sentence says.
    """
    ev = _size(a)["EWSR1::NR4A3"]["over_10cm"]["events"]
    dn = _size(a)["EWSR1::NR4A3"]["over_10cm"]["denom"]
    return (str(dn - 3), _pct(round(100 * ev / (dn - 3), 1)),
            str(ev + 1), _pct(round(100 * (ev + 1) / dn, 1)))


bind("§3.3's count of the cohorts publishing outcome event counts",
     r"(\w+) cohorts publish EMC outcome event counts by NR4A3 partner",
     lambda a: _word(sum(1 for c in _endpoint(a, OUT) if c["pool"])), fold=True)

bind("§1.2's pair: outcome series identified, and how many publish per-partner counts",
     r"(\w+) series test the partner against outcome and only (\w+) publish per-partner event counts",
     lambda a: (_word(len(_endpoint(a, OUT))),
                _word(sum(1 for c in _endpoint(a, OUT) if c["pool"]))), fold=True)

bind("§3.3's description of the Agaram cohort: cases tested and partner-assigned with follow-up",
     r"Agaram 2014 \(MSKCC, (\d+) consecutive cases, (\d+) partner-assigned with follow-up\)",
     lambda a: (str(_by_id(a)["agaram-2014-outcome"]["n_assessable"]), _followed(a, "agaram-2014-outcome")))

bind("§3.2's inclusion-table row for the Agaram cohort",
     r"Agaram 2014 \(MSKCC\), (\d+) partner-assigned with follow-up",
     lambda a: _followed(a, "agaram-2014-outcome"))

bind("§3.3's description of what Huang's table added",
     r"added (\d+) partner-assigned patients with follow-up",
     lambda a: _followed(a, "huang-2023-outcome"))

bind("§3.2's inclusion-table row for the Huang cohort",
     r"Huang 2023 \(Taiwan\), (\d+) partner-assigned with follow-up of (\d+)",
     lambda a: (_followed(a, "huang-2023-outcome"),
                str(_by_id(a)["huang-2023-outcome"]["n_assessable"])))


def _followed(a, cid):
    """The partner-assigned-with-follow-up count, DERIVED as the two arms' death denominators.

    ⛔ NOT READ FROM A FIELD BESIDE IT. 23 and 50 are the sums of the arms the pool actually uses,
    and stating them as sums is what keeps them true the day an arm's denominator moves.
    """
    s = _by_id(a)[cid]["strata"]
    return str(s["EWSR1::NR4A3"]["disease_specific_death"]["denom"]
               + s["TAF15::NR4A3"]["disease_specific_death"]["denom"])


bind("§4.7's statement of how much of the Huang cohort has follow-up",
     r"outcome only for the (\d+) of (\d+) patients with follow-up",
     lambda a: (str(_by_id(a)["huang-2023-outcome"]["n_with_followup"]),
                str(_by_id(a)["huang-2023-outcome"]["n_assessable"])))

bind("§4.1's four size statements: largest series, pooled outcome n, TAF15 arm range, pooled arm",
     r"synthesis has (\d+) patients, the pooled outcome analysis rests on (\d+), and every TAF15 "
     r"arm carrying an actual outcome is (\d+)–(\d+) patients — the pooled TAF15 outcome arm is (\d+)",
     lambda a: _sizes(a))


def _sizes(a):
    """All four DERIVED over the cohort records rather than remembered.

    "Every TAF15 arm carrying an actual outcome" is every cohort with a TAF15 stratum that has a
    denominator — the two response arms and the two outcome arms — so the range is over exactly
    those and widens by itself if a fifth is added.
    """
    largest = max(c["n_assessable"] for c in a["cohorts"] if "n_assessable" in c)
    arms = []
    for c in a["cohorts"]:
        s = (c.get("strata") or {}).get("TAF15::NR4A3")
        if not s:
            continue
        if "denom" in s:
            arms.append(s["denom"])
        else:
            arms += [v["denom"] for v in s.values() if isinstance(v, dict) and "denom" in v]
    pooled = a["analyses"]["B_outcome_by_partner"]["disease_specific_death"]["taf15_arm"]["denom"]
    return (str(largest), _pool_n(a), str(min(arms)), str(max(arms)), str(pooled))


bind("§4.1's pooled TAF15 mortality interval",
     r"pooled TAF15 mortality interval spans (\d+\.\d)–(\d+\.\d) %",
     lambda a: (_pct(a["analyses"]["B_outcome_by_partner"]["disease_specific_death"]["taf15_arm"]["ci95_lo_percent"]),
                _pct(a["analyses"]["B_outcome_by_partner"]["disease_specific_death"]["taf15_arm"]["ci95_hi_percent"])))

bind("§5's third statement of the death contrast, both arms and both intervals",
     r"disease-specific death is (\d+)/(\d+) = (\d+\.\d) % \(95 % CI (\d+\.\d)–(\d+\.\d)\) with "
     r"TAF15 against (\d+)/(\d+) = (\d+\.\d) % \((\d+\.\d)–(\d+\.\d)\) with EWSR1",
     lambda a: _contrast(a, "disease_specific_death")[:10])

bind("§5's fourth statement of the two death rates",
     r"The (\d+\.\d) % vs (\d+\.\d) % contrast is a crude proportion",
     lambda a: (_pct(a["analyses"]["B_outcome_by_partner"]["disease_specific_death"]["taf15_arm"]["percent"]),
                _pct(a["analyses"]["B_outcome_by_partner"]["disease_specific_death"]["comparator_arm"]["percent"])))

bind("§4.8's naming of the headline p-value as its own subject",
     r"p = (\d+(?:\.\d+)?) \(§3.3, the pooled disease-specific-death contrast\)",
     lambda a: _fisher(a["analyses"]["B_outcome_by_partner"]["disease_specific_death"]["fisher_exact_two_sided_p"]))

bind("the retired Agaram-only p, which the artifact still carries as a single-cohort contrast",
     r"The (\d+(?:\.\d+)?) in §3.3 in particular",
     lambda a: _fisher(a["analyses"]["B_outcome_by_partner"]["single_cohort_contrasts_retained"]["agaram2014"]["disease_specific_death"]["fisher_exact_two_sided_p"]))

bind("§5's statement of the two questions' population sizes",
     r"prognosis pool is (\d+) surgically managed patients from two pathology series, and the "
     r"response question is (\d+)–(\d+) patients",
     lambda a: (_pool_n(a),
                str(a["analyses"]["A_tki_objective_response"]["overlap_sensitivity_bounds"]["taf15_denominator_range"][0]),
                str(a["analyses"]["A_tki_objective_response"]["overlap_sensitivity_bounds"]["taf15_denominator_range"][1])))

bind("§6's falsifier #5 — the two TAF15 arms the pooled contrast rests on",
     r"rests on two TAF15 arms of (\d+) and (\d+) patients",
     lambda a: (str(a["analyses"]["B_outcome_by_partner"]["disease_specific_death"]["per_cohort"]
                     ["agaram-2014-outcome"]["TAF15::NR4A3"]["denom"]),
                str(a["analyses"]["B_outcome_by_partner"]["disease_specific_death"]["per_cohort"]
                     ["huang-2023-outcome"]["TAF15::NR4A3"]["denom"])))

# ------------------------------------------------------------------------- C · partner prevalence -


def _prev(a, partner):
    return a["analyses"]["C_partner_prevalence"]["pooled"][partner]


def _prev_row(a, partner):
    p = _prev(a, partner)
    return (str(p["events"]), str(p["denom"]), _pct(p["percent"]),
            _pct(p["ci95_lo_percent"]), _pct(p["ci95_hi_percent"]))


bind("the abstract's pooled TAF15 prevalence, whole",
     r"gives TAF15::NR4A3 in (\d+)/(\d+) = (\d+\.\d) % \(95 % CI (\d+\.\d)–(\d+\.\d)\)",
     lambda a: _prev_row(a, "TAF15::NR4A3"))

for _partner, _pat in (
        ("EWSR1::NR4A3", r"\| EWSR1::NR4A3 \| (\d+)/(\d+) \| (\d+\.\d) % \| (\d+\.\d)–(\d+\.\d) \|"),
        ("TAF15::NR4A3", r"\| TAF15::NR4A3 \| (\d+)/(\d+) \| (\d+\.\d) % \| (\d+\.\d)–(\d+\.\d) \|"),
        ("TCF12::NR4A3", r"\| TCF12::NR4A3 \| (\d+)/(\d+) \| (\d+\.\d) % \| (\d+\.\d)–(\d+\.\d) \|"),
        ("TFG::NR4A3", r"\| TFG::NR4A3 \| (\d+)/(\d+) \| (\d+\.\d) % \| (\d+\.\d)–(\d+\.\d) \|")):
    bind(f"§3.5's prevalence table row for {_partner}", _pat,
         (lambda p: (lambda a: _prev_row(a, p)))(_partner))

bind("§3.5's per-cohort TAF15 range and its spread",
     r"Per-cohort TAF15 share ranges (\d+\.\d) – (\d+\.\d) % \(spread (\d+\.\d) points\)",
     lambda a: (_pct(a["analyses"]["C_partner_prevalence"]["heterogeneity_TAF15"]["range_percent"][0]),
                _pct(a["analyses"]["C_partner_prevalence"]["heterogeneity_TAF15"]["range_percent"][1]),
                _pct(a["analyses"]["C_partner_prevalence"]["heterogeneity_TAF15"]["spread_percent"])))

bind("§3.5's outlier statement: the high cohort's share against the range of the other three",
     r"\((\d+\.\d) % of assigned cases, against (\d+\.\d)–(\d+\.\d) % elsewhere\)",
     lambda a: _outlier(a))


def _outlier(a):
    """The outlier's share and the range of THE OTHERS — derived, so 'elsewhere' cannot go stale.

    ⛔ NOT the artifact's `range_percent`, which spans all four and would include the outlier itself.
    The sentence's claim is that the other three sit below it, so the comparison set is the other
    three by construction rather than by a list somebody must remember to shorten.
    """
    per = a["analyses"]["C_partner_prevalence"]["heterogeneity_TAF15"]["per_cohort_percent"]
    hi_id = max(per, key=lambda k: per[k])
    others = [v for k, v in per.items() if k != hi_id]
    return (_pct(per[hi_id]), _pct(min(others)), _pct(max(others)))


bind("§3.5's two excluded congress abstracts, each as TAF15 over its partner-assigned total",
     r"\((\d+) of (\d+) partner-assigned in Valencia; (\d+) of (\d+) in Pilsen/Znojmo\)",
     lambda a: _abstracts(a))


def _abstracts(a):
    out = []
    for cid in ("llombart-bosch-2022-prevalence", "klubickova-2022-prevalence"):
        counts = _by_id(a)[cid]["counts"]
        out += [str(counts["TAF15::NR4A3"]), str(sum(counts.values()))]
    return tuple(out)


bind("§5's restatement of the pooled TAF15 prevalence",
     r"That TAF15::NR4A3 affects (\d+\.\d) % \(95 % CI (\d+\.\d)–(\d+\.\d)\) of partner-assigned EMC",
     lambda a: _prev_row(a, "TAF15::NR4A3")[2:])

bind("§3.2's inclusion-table row for the four pooled prevalence series",
     r"Agaram 2014 \((\d+) assigned\) · Huang 2023 \((\d+)\) · Lenz 2023 \((\d+)\) · Paioli 2021 \((\d+)\)",
     lambda a: tuple(str(a["analyses"]["C_partner_prevalence"]["partner_assigned_per_cohort"][c])
                     for c in ("agaram-2014-prevalence", "huang-2023-prevalence",
                               "lenz-2023-prevalence", "paioli-2021-prevalence")))

bind("§4.3's partner-unassigned residues, in the order it names the four series",
     r"residue \((\d+), (\d+), (\d+) and (\d+) cases respectively\)",
     lambda a: tuple(str(_by_id(a)[c]["not_partner_assigned"])
                     for c in ("agaram-2014-prevalence", "huang-2023-prevalence",
                               "lenz-2023-prevalence", "paioli-2021-prevalence")))

bind("§4.3's Lenz typing success count",
     r"molecular typing succeeded in (\d+) of 17 cases",
     lambda a: str(_by_id(a)["lenz-2023-prevalence"]["n_tested"]))

bind("§4.3's restatement of the pooled TAF15 share",
     r"pooled TAF15 share of (\d+\.\d) % is an underestimate",
     lambda a: _pct(_prev(a, "TAF15::NR4A3")["percent"]))

bind("Appendix A3's restatement of the pooled share and the outlier cohort's own",
     r"(\d+\.\d) % \(95 % CI (\d+\.\d)–(\d+\.\d)\) pooled over four independent series; (\d+\.\d) % "
     r"is that one referral cohort",
     lambda a: _prev_row(a, "TAF15::NR4A3")[2:] + (_outlier(a)[0],))

bind("§3.2's Sjögren counts, the series excluded on a ground of its own",
     r"nine patients; EWSR1 (\d+), TAF15 (\d+), TCF12 (\d+)\)",
     lambda a: tuple(str(_by_id(a)["sjogren-2003-prevalence"]["counts"][p])
                     for p in ("EWSR1::NR4A3", "TAF15::NR4A3", "TCF12::NR4A3")))

bind("§3.6's approximation of the EWSR1 prevalence share",
     r"what an ~(\d+) % EWSR1 population would look like",
     lambda a: str(round(_prev(a, "EWSR1::NR4A3")["percent"])))

bind("Appendix A4's correction: the high-grade share and the group it is actually over",
     r"The (\d+) % is over that paper's (\d+)-case variant group",
     lambda a: _variant_grade(a))


def _variant_grade(a):
    """Agaram 2014's own "80 % high grade" is over its 10-case VARIANT group, not its 7 TAF15 cases.

    Both the share and its denominator are read from the stratum the artifact records for exactly
    this correction, so the row cannot drift back to quoting it as a TAF15 figure.
    """
    v = _by_id(a)["agaram-2014-outcome"]["strata"][
        "variant non-EWSR1 (TAF15 + TCF12 + partner-unassigned)"][
        "moderate_to_high_cellularity_with_moderate_to_severe_atypia"]
    return (str(round(100 * v["events"] / v["denom"])), str(v["denom"]))


bind("§3.6's Brenca cohort sizes",
     r"profiled (\d+) EWSR1-NR4A3 and (\d+) TAF15-NR4A3 EMC",
     lambda a: _brenca(a))


def _brenca(a):
    """Read out of the cohort's own label, which is where this pair has its one home."""
    m = re.search(r"(\d+) EWSR1-NR4A3 vs (\d+) TAF15-NR4A3",
                  _by_id(a)["brenca-2019-mechanism"]["label"])
    assert m, "the Brenca cohort label no longer states its two arm sizes"
    return (m.group(1), m.group(2))


bind("§3.2's Suemitsu row: the series size and its TAF15 count",
     r"Suemitsu 2025 \(MSK, n = (\d+), PMID",
     lambda a: str(_by_id(a)["suemitsu-2025-outcome"]["n_assessable"]))

bind("§3.2's reading of why Suemitsu establishes nothing: its TAF15 count over its size",
     r"with only (\d+) TAF15 of (\d+)",
     lambda a: (str(_by_id(a)["suemitsu-2025-outcome"]["counts"]["TAF15::NR4A3"]),
                str(_by_id(a)["suemitsu-2025-outcome"]["n_assessable"])))

# ------------------------------------------------ §8 · counts the prose states about the ARTIFACT -
#
# ⛔ THESE ARE THE ONES THAT DRIFT SILENTLY, BECAUSE NOTHING ABOUT THE EVIDENCE CHANGES WHEN THEY GO
# WRONG. Adding a cohort or a citation moves every one of them, and the sentence stating them sits
# 700 lines away from the edit. Each is RE-DERIVED from the artifact's own contents; none is
# compared against a typed constant.


def _noted(a):
    return [k for k, v in a["citations"].items() if "verification_note" in v]


def _unnoted(a):
    return [k for k, v in a["citations"].items() if "verification_note" not in v]


def _slug_and_status(a):
    """Citations whose `verification_note` names BOTH a cache slug and an HTTP status.

    ⚠ THE PREDICATE IS THE SENTENCE'S OWN. `suemitsu2025` records an HTTP status and no slug, so a
    guard testing either alone would count five and pass a sentence that says four.
    """
    return [k for k, v in a["citations"].items()
            if "verification_note" in v
            and "literature/" in v["verification_note"]
            and re.search(r"HTTP \d{3}", v["verification_note"])]


bind("§8's census of the artifact's citation records: how many there are, how many carry a "
     "verification_note, and how many of those name both a slug and a status",
     r"of its (\d+) citation records, (\d+) carry a `verification_note` at all, and (\d+) of those",
     lambda a: (str(len(a["citations"])), str(len(_noted(a))), str(len(_slug_and_status(a)))))

bind("§8's census of the artifact's cohort records",
     r"its (\d+) cohort records, none carries",
     lambda a: str(len(a["cohorts"])))

bind("§8's count of the cache slugs the artifact lists",
     r"flat list of the (\w+) cache slugs",
     lambda a: _word(len(a["retrieval_provenance"]["cache_slugs_used"])), fold=True)

bind("§8's complementary count of the citations lacking a verification_note",
     r"the (\w+) that lack one are",
     lambda a: _word(len(_unnoted(a))), fold=True)


# =================================================================================================
# ------------------------------------------------- E · the ranges round 4 was forced to print ---
# ⛔⛔ ADDED 2026-08-27, CYC-0011 ROUND 4, AND THE REASON IS THE MEASUREMENT AND NOT THE PROSE.
# §2.5 promised the range of per-cohort rates "printed beside every pooled figure" and did not
# deliver it at the two pooled figures with the WIDEST spreads in the document — the TKI secondary
# pool (53.9 points) and local recurrence's comparator arm (22.4). Two blind seats, holding disjoint
# slices of the standing P1 list and unable to see each other, found it from opposite directions.
# The fix printed the missing ranges rather than softening the rule, which put ~20 new figures on
# the page — and `test_every_fraction_and_percentage_is_bound_or_declared` refused the commit until
# every one of them was bound here. That refusal is the instrument working exactly as intended:
# ⭐ A CORRECTION ROUND THAT ADDS PROSE ADDS UNWATCHED SURFACE UNLESS IT ADDS THE GUARDS IN THE SAME
# COMMIT. Measured that day across the whole document set: the fusion-partner endpoint went 46/259
# sentences read by an instrument to 46/271 — the covered count did not move while the document
# grew — so the UNCOVERED set rose 213 -> 225. That is `paper-hardening` §8a's trap in a second
# costume: rounds 1-3 sampled surfaces one lens at a time, and round 4 manufactured them while
# closing findings. Ledger: AUT-COV-001.

bind("§3.1's secondary row now carries its per-cohort range — the widest spread in this paper, and "
     "the one §2.5 promised was printed beside every pooled figure",
     r"per cohort (\d+\.\d+) % \(pazopanib, (\d+/\d+)\) and (\d+\.\d+) % \(sunitinib, (\d+/\d+)\), "
     r"spread (\d+\.\d+) pts",
     lambda a: (
         _pct(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]
              ["heterogeneity"]["per_cohort_percent"]["pazopanib-NCT02066285 (non-TAF15 arm)"]),
         _frac(_by_id(a)["pazopanib-NCT02066285"]["strata"]["non-TAF15"]),
         _pct(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]
              ["heterogeneity"]["per_cohort_percent"]["sunitinib-2014 (EWSR1 arm)"]),
         _frac(_by_id(a)["sunitinib-2014"]["strata"]["EWSR1::NR4A3"]),
         _pct(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]
              ["heterogeneity"]["spread_percent"])))

bind("Appendix A22's restatement of the same secondary-pool spread, which must not drift from the "
     "table it registers a correction to",
     r"averaged (\d+\.\d+) % \(pazopanib, (\d+/\d+)\) with (\d+\.\d+) % \(sunitinib, (\d+/\d+)\) "
     r"into (\d+/\d+) = (\d+\.\d+) %, a (\d+\.\d+)-point spread",
     lambda a: (
         _pct(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]
              ["heterogeneity"]["per_cohort_percent"]["pazopanib-NCT02066285 (non-TAF15 arm)"]),
         _frac(_by_id(a)["pazopanib-NCT02066285"]["strata"]["non-TAF15"]),
         _pct(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]
              ["heterogeneity"]["per_cohort_percent"]["sunitinib-2014 (EWSR1 arm)"]),
         _frac(_by_id(a)["sunitinib-2014"]["strata"]["EWSR1::NR4A3"]),
         _frac(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]
               ["contrast"]["comparator_arm"]),
         _pct(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]
              ["contrast"]["comparator_arm"]["percent"]),
         _pct(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]
              ["heterogeneity"]["spread_percent"])))

bind("§3.3's local-recurrence per-cohort rates — the DIRECTION FLIP the 4.3-point pooled gap was "
     "cancelling, stated as one construction so the two cohorts cannot drift apart",
     r"Agaram gives (\d+/\d+) = (\d+\.\d+) % TAF15 against (\d+/\d+) = (\d+\.\d+) % EWSR1; Huang "
     r"gives (\d+/\d+) = (\d+\.\d+) % against (\d+/\d+) = (\d+\.\d+) %",
     lambda a: _lr_pair(a))

bind("Appendix A22's restatement of the local-recurrence comparator spread",
     r"comparator arm ran (\d+\.\d+) % \(Agaram\) against (\d+\.\d+) % \(Huang\), (\d+\.\d+) points",
     lambda a: (
         _pct(a["analyses"]["B_outcome_by_partner"]["local_recurrence"]["per_cohort"]
              ["agaram-2014-outcome"]["EWSR1::NR4A3"]["percent"]),
         _pct(a["analyses"]["B_outcome_by_partner"]["local_recurrence"]["per_cohort"]
              ["huang-2023-outcome"]["EWSR1::NR4A3"]["percent"]),
         _pct(a["analyses"]["B_outcome_by_partner"]["local_recurrence"]
              ["heterogeneity_comparator_arm"]["spread_percent"])))

bind("§2.5's two named spreads, which are the whole reason that bullet was corrected",
     r"the secondary TKI pool \(spread (\d+\.\d+) points\) and local recurrence \(comparator\s+"
     r"arm, (\d+\.\d+) points\)",
     lambda a: (
         _pct(a["analyses"]["A_tki_objective_response"]["secondary_assume_independent"]
              ["heterogeneity"]["spread_percent"]),
         _pct(a["analyses"]["B_outcome_by_partner"]["local_recurrence"]
              ["heterogeneity_comparator_arm"]["spread_percent"])))

# ⛔ THE SJÖGREN COUNTERFACTUAL IS DERIVED, NEVER TYPED. §3.5 and A28 state what the prevalence pool
# WOULD read had the excluded series been pooled. That is an arithmetic claim about the artifact's
# own integers, so it is computed here from those integers — a typed "31/163 = 19.0 %" would go
# stale the moment a prevalence cohort is added, which is precisely how `cohorts_identified` drifted
# (see the roster note above).
bind("§3.5's Sjögren counterfactual: its own TAF15 share, the high pooled cohort it exceeds, and "
     "what pooling it would do to the headline",
     r"Sjögren 2003 is (\d+/\d+) = (\d+\.\d+) % TAF15 at patient level, above Agaram's (\d+\.\d+) %",
     lambda a: (_sjogren_frac(a), _sjogren_pct(a), _prev_pct(a, "agaram-2014-prevalence")))

bind("the counterfactual pool itself, stated twice and bound at both sites",
     r"would give \*?\*?(\d+/\d+) = \*?\*?(\d+\.\d+) %\*?\*? and (?:a per-cohort range of|widen "
     r"the per-cohort range to) (\d+\.\d+) – (\d+\.\d+) %",
     lambda a: (_prev_counterfactual_frac(a), _prev_counterfactual_pct(a),
                _pct(min(_prev_shares(a).values())), _sjogren_pct(a)))


bind("round 4's two restatements of Appendix A4's high-grade share, bound to the same stratum A4 is "
     "bound to so a correction's own restatement cannot drift from the correction",
     r"A4 records its (\d+) % high-grade variant group",
     lambda a: _variant_grade(a)[0])

bind("Huang 2023's own abstract sentence, quoted in §4.7a and A27 as the independent corroboration "
     "that keeps §3.3's defeater standing without the human-transcribed Discussion quotation — "
     "BOUND rather than declared, because the artifact holds the integers it renders (7/9 = 77.8 %, "
     "which the source prints as 78 %). If those integers ever move, the quotation must be re-read "
     "rather than silently left standing beside them.",
     r"size >10 cm \((\d+)%, P = (\.\d+)\)",
     lambda a: (str(round(100.0 * _huang_size(a)["events"] / _huang_size(a)["denom"])),
                _pubp(_by_id(a)["huang-2023-outcome"]["size_covariate"]
                      ["published_p_size_over_10cm"])))


def _huang_size(a):
    """Huang's TAF15 >10 cm stratum — the one side of that table with no internal inconsistency.

    ⚠ THE EWSR1 SIDE IS DELIBERATELY NOT USED HERE. The artifact records, and does not resolve, that
    Huang prints its EWSR1 >10 cm cell as "12/46 (28%)" while 12/46 is 26.1 % — POLICY-evidence.md
    §2.1(2) forbids back-deriving a count from a percentage to close the gap. Rendering a percentage
    from those integers would manufacture the very number the source disagrees with.
    """
    return _by_id(a)["huang-2023-outcome"]["size_covariate"]["TAF15::NR4A3"]["over_10cm"]


bind("the Paioli prevalence split named in the sentence describing the back-derivation this "
     "document REFUSES to perform. ⭐ IT WAS DECLARED NOT-ARTIFACT-OWNED AND THAT WAS WRONG: the "
     "declaration's own text conceded the two integers are the prevalence cohort's counts and are "
     "pooled under analysis C. A site that states a forbidden operation still states real integers, "
     "and if they move, the sentence describing what would be derived from them is stale.",
     r"across the (\d+)/(\d+) partner ratio",
     lambda a: (str(_by_id(a)["paioli-2021-prevalence"]["counts"]["EWSR1::NR4A3"]),
                str(_by_id(a)["paioli-2021-prevalence"]["counts"]["TAF15::NR4A3"])))


# ⚠ DECLARED NOT-ARTIFACT-OWNED NUMBERS.
#
# Every printed fraction and rate the census below finds must be covered either by a BINDING above
# or by one of these. They are declared with a reason class so that the exclusion set is a
# deliberate, reviewable list rather than "whatever failed" — a guard whose exclusion list grew to
# make it pass is a guard that measures nothing.
#
# ⛔ ADDING A ROW HERE IS A CLAIM THAT THE ARTIFACT DOES NOT OWN THAT NUMBER. If the artifact does
# own it, the right move is a binding, not a row.
# =================================================================================================

DECLARED_NOT_ARTIFACT_OWNED = [
    ("identifier",
     r"10261/214284",
     "A DIGITAL.CSIC repository handle, named in §6 and Appendix A25 as the one listed handle that "
     "is UNREAD rather than measured empty (an Anubis anti-bot challenge). It contains a slash "
     "between digits and is not a proportion — same class as the DOI row above."),

    ("source-quoted",
     r"Its abstract's aggregate (35)/(67) relapse split",
     "Paioli 2021's partner-BLIND relapse total, read from its abstract. It is barred from the pool "
     "by §2.1(2) and is quoted to say why, so it is not a pooled quantity and the artifact holds it "
     "only inside `retrieval_provenance.not_retrievable` prose."),

    ("identifier",
     r"doi:10\.1186/2045-3329-2-22",
     "A DOI. It contains a slash between digits and is not a proportion. Citation provenance is "
     "`lint_citations`' business, not this guard's."),

    ("method-constant",
     r"95 %",
     "The CONFIDENCE LEVEL, not a measurement. It is fixed by "
     "`systems/POLICY-evidence.md` §2.2 and recorded in every interval the artifact writes as "
     "`\"interval\": \"Wilson score, 95%\"`; the bounds themselves are bound above, at every site."),

    ("source-quoted",
     r"≈27 %",
     "The figure THE FIELD quotes, which this paper exists partly to correct. It is a "
     "characterisation of the literature, not a pooled quantity, and the artifact holds no such "
     "field — its `outlier_note` describes the same situation in prose. The pooled 18.2 % that "
     "replaces it, and the 29.2 % referral cohort it comes from, are both bound above."),

    ("source-quoted",
     r">\s?90% (?:of the cases an NR4A3 rearrangement|NR4A3-rearrangement statement)",
     "Reference [12]'s definitional statement — quoted verbatim in §1.1 inside its own quotation "
     "marks, and named again in Appendix A12 as one of the sourced facts that row does NOT touch. "
     "It is a statement about how EMC is defined, not a number this synthesis pools."),

    ("superseded-quotation",
     r"(?:\"80 % of TAF15 tumours are high grade\"|under 1 % of soft-tissue sarcomas)",
     "Retained superseded text in Appendix A — A4's misquoted high-grade share and A12's uncited "
     "prevalence figure, both RETIRED from the live document. Preserving the retracted wording is "
     "the appendix's whole job (CLAUDE.md rule 1.2), so these must not be corrected to anything. "
     "A4's live replacement IS bound above."),

    ("foreign-artifact",
     r"SEMA3C reads 1\.8× normal tissue and 1\.7× other sarcomas",
     "GSE28866's expression ratios. Their one home is "
     "`research/modalities/gse28866-tumour-vs-normal.json` -> `per_gene.values`, named in the same "
     "sentence. §3.6 states four separate times that this deposit touches no clinical claim, so it "
     "is not a fusion-partner pooled quantity."),
]


@pytest.fixture(scope="module")
def prose():
    return _load_prose()


@pytest.fixture(scope="module")
def flat(prose):
    return _flat(prose)


@pytest.fixture(scope="module")
def art():
    return _load_artifact()


@pytest.mark.parametrize("what,pattern,value,fold", BINDINGS, ids=[b[0] for b in BINDINGS])
def test_every_site_that_states_the_quantity_states_the_artifacts_value(what, pattern, value, fold,
                                                                       flat, art):
    """⛔⛔ EVERY SITE, NOT WHETHER THE VALUE APPEARS SOMEWHERE.

    `re.findall` returns one entry per site; a corruption at ONE of several sites therefore fails
    here, which an `in` test cannot see. That distinction is the whole reason this file is shaped
    the way it is — see the module docstring.

    ⚠ AT LEAST ONE MATCH IS REQUIRED. A pattern that has stopped matching is a guard that has
    silently stopped guarding, so a reworded sentence goes RED rather than quiet. ⛔ And when it
    does: check the MEANING first. Re-anchor only if the sentence says the same thing in different
    words; if the claim itself changed, the fix is in the prose or the artifact, not in the regex.
    """
    expected = value(art)
    found = re.findall(pattern, flat)
    assert found, (
        f"nothing in the manuscript matches the construction that states {what} (/{pattern}/). "
        "Either the sentence was reworded — check the MEANING before the regex — or the claim was "
        "dropped.")
    def same(got):
        if not fold:
            return got == expected
        if isinstance(expected, tuple):
            return tuple(g.casefold() for g in got) == tuple(e.casefold() for e in expected)
        return got.casefold() == expected.casefold()

    wrong = [f for f in found if not same(f)]
    assert not wrong, (
        f"{what}: the artifact gives {expected!r} and the manuscript states {wrong!r} at "
        f"{len(wrong)} of its {len(found)} site(s). The artifact is generated from the counts in "
        "`emc_fusion_partner_pooling.py`; fix the prose, or fix the generator and regenerate — "
        "never paste the prose's value into this test.")


def test_the_typed_rosters_equal_the_cohort_records_they_count(art):
    """⛔ A COUNT OF THE ARTIFACT'S OWN CONTENTS MUST BE DERIVED FROM THEM (CLAUDE.md rule 1.1).

    `_roster()` was added on 2026-08-26 after `B_outcome_by_partner` carried `cohorts_identified: 3`
    while holding four — adding `suemitsu-2025-outcome` left the typed pair untouched, so the
    artifact asserted that three outcome cohorts exist. The repair was applied to B and C and
    **not** to A, which still types `cohorts_identified: 3` and `cohorts_pooled_primary: 1`. That is
    the list-scoped fix regressing at a sibling: correct today, and free to go stale the moment a
    fourth response cohort is recorded.

    So the typed values are asserted against the records rather than trusted, and the prose is bound
    to the records directly (see the analysis-A bindings). This test is what makes the remaining
    typed pair safe without restructuring the generator.
    """
    a = art["analyses"]
    tki = _endpoint(art, TKI)
    assert a["A_tki_objective_response"]["cohorts_identified"] == len(tki), (
        "analyses.A_tki_objective_response.cohorts_identified is TYPED and no longer equals the "
        f"number of {TKI} cohort records ({len(tki)}) — derive it with `_roster()` as B and C do")
    assert a["A_tki_objective_response"]["cohorts_pooled_primary"] == sum(1 for c in tki if c["pool"]), \
        "analyses.A_tki_objective_response.cohorts_pooled_primary is TYPED and no longer equals " \
        "the number of pooled response cohorts"
    assert set(a["A_tki_objective_response"]["cohorts_excluded"]) == {c["id"] for c in tki if not c["pool"]}, \
        "the typed exclusion map for analysis A no longer names exactly the unpooled response cohorts"

    out = _endpoint(art, OUT)
    assert a["B_outcome_by_partner"]["cohorts_identified"] == len(out)
    assert a["B_outcome_by_partner"]["cohorts_pooled"] == sum(1 for c in out if c["pool"])
    assert set(a["B_outcome_by_partner"]["cohorts_excluded"]) == {c["id"] for c in out if not c["pool"]}

    prev = _endpoint(art, PREV)
    assert a["C_partner_prevalence"]["cohorts_pooled"] == [c["id"] for c in prev if c["pool"]]
    assert set(a["C_partner_prevalence"]["cohorts_excluded"]) == {c["id"] for c in prev if not c["pool"]}


def test_the_pooled_denominators_are_the_arms_the_cohorts_supply(art):
    """⛔ THE POOL IS THE SUM OF ITS COHORTS, RE-ADDED HERE RATHER THAN TRUSTED.

    Every pooled figure the manuscript quotes rests on this addition, and the manuscript states the
    pool size (73) and each cohort's contribution (23, 50) in four separate sections. Re-deriving
    the sum from the cohort records catches the case the prose bindings cannot: a pooled arm and its
    per-cohort breakdown moving apart inside the artifact itself.
    """
    b = art["analyses"]["B_outcome_by_partner"]
    for key, strat in (("disease_specific_death", "disease_specific_death"),
                       ("local_recurrence", "local_recurrence")):
        for arm, partner in (("taf15_arm", "TAF15::NR4A3"), ("comparator_arm", "EWSR1::NR4A3")):
            got = b[key][arm]
            want_e = sum(_by_id(art)[c]["strata"][partner][strat]["events"] for c in b["pooled_cohorts"])
            want_d = sum(_by_id(art)[c]["strata"][partner][strat]["denom"] for c in b["pooled_cohorts"])
            assert (got["events"], got["denom"]) == (want_e, want_d), (
                f"the pooled {key} {arm} is {got['events']}/{got['denom']} and the cohorts it names "
                f"supply {want_e}/{want_d}")

    c = art["analyses"]["C_partner_prevalence"]
    for partner, pooled in c["pooled"].items():
        want = sum(_by_id(art)[cid]["counts"].get(partner, 0) for cid in c["cohorts_pooled"])
        assert pooled["events"] == want, (
            f"the pooled prevalence numerator for {partner} is {pooled['events']} and its four "
            f"cohorts supply {want}")
    denoms = {p["denom"] for p in c["pooled"].values()}
    assert denoms == {sum(c["partner_assigned_per_cohort"].values())}, \
        "the prevalence denominator is not the sum of the per-cohort partner-assigned counts"


# =================================================================================================
# Pointer resolution.
# =================================================================================================

#: A backticked artifact path: `analyses.B_outcome_by_partner.metastasis_reading`,
#: `cohorts[huang-2023-outcome].size_covariate`, `citations.huang2023.verification_note`.
_POINTER = re.compile(r"`([A-Za-z_][A-Za-z0-9_]*(?:\[[^\]`]+\]|\.[A-Za-z0-9_]+)+)`")

#: ⚠ A FILENAME IS NOT A POINTER. `emc_fusion_partner_pooling.py` has the shape of a dotted path and
#: is a path on disk; excluding it by EXTENSION rather than by name keeps a file added tomorrow out
#: of scope without anybody remembering to list it.
_FILE_SUFFIX = re.compile(r"\.(?:py|json|md|mjs|ya?ml|csv|sh|txt|pdf)$")

#: ⚠ POINTERS INTO A DIFFERENT FILE, DECLARED SO THAT AN UNRESOLVABLE ROOT IS A FAILURE RATHER THAN
#: A SHRUG. Each is named beside its own artifact's path in the sentence that uses it.
FOREIGN_POINTERS = {
    "per_gene.values": "research/modalities/gse28866-tumour-vs-normal.json (§3.6)",
    "registry.citations.masunaga2025": "research/data/emc-clinical-registry.json (Appendix A11)",
}


def _resolve(art, path):
    """Walk one `a.b[id].c` path through the artifact. Returns (ok, where_it_broke)."""
    node = art
    for tok in re.findall(r"\[[^\]]+\]|[A-Za-z0-9_]+", path):
        if tok.startswith("["):
            key = tok[1:-1]
            if not isinstance(node, list):
                return False, f"{tok} indexes something that is not a list of records"
            hit = [c for c in node if isinstance(c, dict) and c.get("id") == key]
            if not hit:
                return False, f"no record with id {key!r}"
            node = hit[0]
        else:
            if not isinstance(node, dict) or tok not in node:
                return False, f"{tok!r} is not a key here"
            node = node[tok]
    return True, None


def test_every_artifact_pointer_the_prose_names_resolves(prose, art):
    """⛔ A POINTER TO A KEY THAT DOES NOT EXIST IS A BROKEN CITATION OF THE EVIDENCE.

    Two appendix rows in this document pointed at
    `analyses.B_outcome_by_partner.counter_signal.metastasis_reading`; there is no `counter_signal`
    node, and the real path is `analyses.B_outcome_by_partner.metastasis_reading`. A reader
    following it finds nothing and cannot tell whether the claim or the path is wrong. A blind seat
    found it; the check costs nothing and finds the whole class.

    ⚠ THE FOREIGN ROOTS ARE DECLARED, NOT SKIPPED. A path whose first segment is not a top-level key
    of this artifact is either a pointer into a different file — which must be in
    `FOREIGN_POINTERS` — or a typo. Skipping unknown roots silently would let a mistyped root pass
    as "not ours".
    """
    seen, broken, undeclared = 0, [], []
    for m in _POINTER.finditer(prose):
        path = m.group(1)
        if _FILE_SUFFIX.search(path):
            continue
        root = re.match(r"[A-Za-z0-9_]+", path).group(0)
        if root not in art:
            if path not in FOREIGN_POINTERS:
                undeclared.append(path)
            continue
        seen += 1
        ok, why = _resolve(art, path)
        if not ok:
            broken.append(f"{path} — {why}")
    assert not undeclared, (
        f"the manuscript names path-shaped references {undeclared} whose root is not a top-level "
        "key of the pooling artifact and which are not declared in FOREIGN_POINTERS. Either fix the "
        "path or declare which artifact it points into.")
    assert not broken, (
        "the manuscript points at artifact keys that do not exist: " + "; ".join(broken))
    assert seen >= 8, (
        f"only {seen} artifact pointers were found in the manuscript; this document cites its "
        "artifact by path throughout, so a collapse in that count means the pointer pattern has "
        "stopped matching rather than that the prose stopped pointing")


# =================================================================================================
# The census — what is NOT bound.
# =================================================================================================

#: The two drift-prone printed forms: an explicit `events/denom` fraction, and any printed rate —
#: integer percentages included, because the size defeater reaches the page as "78 %" and a census
#: that only read decimals would have called the paper's most-repeated share unwatched.
_CENSUS = re.compile(r"\d+/\d+|\d+(?:\.\d+)? ?%")


def _spans_by_bucket(flat):
    """(spans covered by a BINDING, spans covered by a DECLARATION) — kept apart on purpose.

    A figure inside a binding is WATCHED; a figure inside a declaration is only ACCOUNTED FOR. The
    census accepts either, and the ratchet below counts them separately so that moving a figure from
    the first bucket to the second is visible rather than silent.
    """
    bound, declared = [], []
    for _what, pattern, _value, _fold in BINDINGS:
        bound += [(m.start(), m.end()) for m in re.finditer(pattern, flat)]
    for _cls, pattern, _why in DECLARED_NOT_ARTIFACT_OWNED:
        declared += [(m.start(), m.end()) for m in re.finditer(pattern, flat)]
    return bound, declared


def _covered_spans(flat, art):
    bound, declared = _spans_by_bucket(flat)
    return bound + declared


def test_every_fraction_and_percentage_is_bound_or_declared(flat, art):
    """★★ THE SURFACE ENUMERATED, NOT SAMPLED (paper-hardening §8a).

    A guard is only as good as the set of sentences it reaches, and "how many did it reach" is a
    question you answer by counting, not by reading. Every `events/denom` fraction and every
    one-decimal rate in the manuscript is required to fall inside the span of a BINDING or of a
    declared not-artifact-owned construction. A new figure added to the prose with no binding fails
    here rather than joining the document unwatched.

    ⚠ THIS IS COVERAGE, NOT CORRECTNESS. It says only that something would notice a change; the
    bindings are what say the value is right.
    """
    spans = _covered_spans(flat, art)
    uncovered = []
    for m in _CENSUS.finditer(flat):
        if not any(s <= m.start() and m.end() <= e for s, e in spans):
            uncovered.append((m.group(0), flat[max(0, m.start() - 90):m.end() + 60]))
    assert not uncovered, (
        f"{len(uncovered)} printed figure(s) in the manuscript are bound to nothing and declared "
        "nowhere. Add a binding if the artifact owns the number, or a "
        "DECLARED_NOT_ARTIFACT_OWNED row with its reason class if it does not:\n"
        + "\n".join(f"  {v!r}  …{ctx}…" for v, ctx in uncovered))


def test_the_declared_exclusions_still_describe_real_sentences(flat):
    """⛔ AN EXCLUSION THAT NO LONGER MATCHES ANYTHING IS AN EXCLUSION NOBODY WILL EVER REMOVE.

    The list is meant to be short and reviewable. A row whose construction has left the document is
    dead weight that makes the exclusion set look larger — and, worse, hides the fact that the
    number it covered is gone.
    """
    dead = [pattern for _cls, pattern, _why in DECLARED_NOT_ARTIFACT_OWNED
            if not re.search(pattern, flat)]
    assert not dead, (
        "these declared exclusions match nothing in the manuscript any more, so delete them: "
        f"{dead}")


def test_no_share_above_one_hundred_percent_reaches_the_page(flat):
    """⛔ THE WRONG-DENOMINATOR CLASS, CAUGHT WHERE A REVIEWER WOULD SEE IT.

    A Wilson bound taken over the wrong denominator ran to 112.8 % once in this repository and
    reached a manuscript. This reads the shipped sentences rather than the module.
    """
    bad = [m for m in re.findall(r"\d+(?:\.\d+)? ?%", flat) if float(m.rstrip(" %")) > 100.0]
    assert not bad, f"the manuscript prints share(s) above 100 %: {bad}"


def test_the_guard_binds_a_material_share_of_the_documents_figures(flat, art):
    """★ A FLOOR UNDER COVERAGE, so that deleting bindings cannot quietly become the way to green.

    Not a target to chase — the census above is the real instrument. This is the ratchet that stops
    the file from being emptied: if a binding is removed, either the sentence went with it (and the
    census stays green while this falls) or the coverage really dropped.
    """
    bound, declared = _spans_by_bucket(flat)
    total = len(_CENSUS.findall(flat))
    assert total >= 100, (
        f"only {total} printed figures found; the census pattern has stopped matching the document")

    # ⚠ COUNT THE FIGURES A DECLARATION IS THE *ONLY* THING COVERING. Several declared patterns —
    # "95 %" above all — also fall inside bound constructions, so counting every declaration match
    # would report a document far less guarded than it is.
    only_declared = [m.group(0) for m in _CENSUS.finditer(flat)
                     if not any(s <= m.start() and m.end() <= e for s, e in bound)
                     and any(s <= m.start() and m.end() <= e for s, e in declared)]
    assert len(only_declared) <= 20, (
        f"{len(only_declared)} figures rest on a declaration alone: {sorted(set(only_declared))}. "
        "That list is meant to stay short and reviewable; a growing exclusion set is how a guard "
        "stops measuring anything.")
    in_bindings = sum(1 for m in _CENSUS.finditer(flat)
                      if any(s <= m.start() and m.end() <= e for s, e in bound))
    assert in_bindings >= 90, (
        f"only {in_bindings} of {total} printed figures sit inside a binding; bindings have been "
        "removed without the sentences they read going with them")
