"""MEASURE-ON-ARRIVAL: drop a host that cannot bank, and never condemn one on absence of evidence.

★ WHY THIS EXISTS RATHER THAN A BETTER THROUGHPUT TABLE. Host variance dwarfs card identity on this workload:
13 paired RTX 3090-vs-4090 measurements within 60 min, one system, span 0.50-2.67x against a 1.745x table
prediction — and the "slow" card won 6 of 13. `vast_cost_model.verify_and_abandon_threshold` already argued
for measuring on arrival and was wired to NOTHING (referenced only by its own unit tests).

⚠ THE NEGATIVE CONTROLS ARE THE POINT. Two guards in this repo have been caught today by their own negative
control (the durable blacklist, and a `spearman` that called a constant series a trend). A destroyer with no
negative control is the most dangerous thing that can be added to a billing lane, so most of this file is
cases where it must REFUSE to act.
"""
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import arrival_throughput as at  # noqa: E402
from inflight_usd_per_ns import APPROVED_USD_PER_NS  # noqa: E402


# =============================================================================================================
# ⛔ THE NEGATIVE CONTROLS — every way this must refuse to condemn
# =============================================================================================================
@pytest.mark.parametrize("spi", [None, 0, 0.0, "", "junk"])
def test_no_measured_rate_is_WATCHING_never_ABANDON(spi):
    """CLAUDE.md §4: an absent reading is not a reading of absence. A cold host that has printed no timing
    line yet has not been shown to be slow — it has not been shown anything."""
    v = at.verdict(spi, 16.0, iteration=100, interval=64)
    assert v["verdict"] == at.WATCHING
    assert "ABSENT" in v["why"]


def test_a_cpu_bound_staging_phase_survives():
    """The exact population on the board right now: three of four rows read STARTING / CPU-bound setup. They
    have no timing line because MD has not begun. Condemning them would reap healthy legs mid-stage — the
    failure `vast_idle_guard`'s inviolable rule exists to prevent."""
    assert at.verdict(None, 16.0, iteration=0, interval=64)["verdict"] == at.WATCHING


def test_gpu_utilisation_is_never_consulted():
    """The inviolable rule, asserted structurally rather than trusted: this module must not even be able to
    read GPU utilisation, so no future edit can quietly make idleness condemn a box."""
    import inspect
    # CODE lines only — the module docstring necessarily NAMES the rule it obeys, and a test that could not
    # tell a prohibition from a violation would have to be silenced the first time someone documented it.
    src = inspect.getsource(at)
    body = src.split('"""', 2)[-1]
    code = [ln for ln in body.splitlines()
            if ln.strip() and not ln.lstrip().startswith("#")]
    for forbidden in ("gpu_util", "utilization", "nvidia-smi", "gpu_busy"):
        assert not any(forbidden in ln for ln in code), \
            f"{forbidden!r} must never enter this decision"


def test_a_POOLED_expectation_may_not_raise_the_dollar_flag():
    """★ THE FALSE-POSITIVE THIS GUARD SHIPPED WITH, caught on the live board within minutes because it was
    report-only. The arm median is pooled across a mixed fleet and the table's own RTX 4090/RTX 3090 ratio is
    1.745, so a HEALTHY 3090 reads ~1.75x "slower than expected" against it. Two live 3090s were flagged at
    1.86x and 2.00x; rebased on their own card they are 0.97x and 1.04x. A pooled expectation therefore
    reports the rate and withholds the verdict."""
    pooled = at.verdict(31.0, 16.6, iteration=1100, interval=64, quoted_usd_per_ns=0.00412,
                        provenance=at.PROV_POOLED)
    assert pooled["verdict"] == at.KEEP
    assert "not comparable" in pooled["why"]
    assert "⚠" not in at.cell(pooled)
    # the same host against its OWN card's measured rate is unremarkable
    card = at.verdict(31.0, 31.8, iteration=1100, interval=64, quoted_usd_per_ns=0.00412,
                      provenance=at.PROV_CARD)
    assert card["slowdown_vs_expected"] < 1.1 and "⚠" not in at.cell(card)


def test_the_per_card_rate_is_read_from_by_gpu_not_the_arm_median():
    """★ THE ASSERTIONS ARE DERIVED FROM THE TABLE, NOT TYPED (rewritten 2026-08-01 — this test was RED on
    `main`, and structurally so).

    It used to read `assert tv.arm_card_rate(4.0, "ternary", "RTX 4090") == 16.6`. But
    `ternary-arm-iteration-rates.json` is REGENERATED BY CI on every `reps-diag` pass from whatever leg
    records exist, so the 4090 figure moved to 16.8 the moment another 5a-KS leg landed — and the test went
    red for the lane WORKING. A literal copy of a number whose one home is a regenerated artifact is exactly
    the duplication CLAUDE.md §1 forbids, and here it also inverts the signal: a landing leg turns the build
    red, so red stops meaning "something broke".

    What is actually being pinned is the WIRING — that `arm_card_rate` reads `by_gpu` rather than the pooled
    `s_per_iter`, that marketplace names normalise, and that an unbenched card yields None so it cannot
    condemn. Those are properties of the code and hold whatever the measurements say.
    """
    import ternary_vast_launch as tv
    entry = ((tv.arm_iteration_rates(4.0, path=tv._ARM_RATES_PATH) and
              tv._ARM_RATES_CACHE[tv._ARM_RATES_PATH]["rates"]["4.0"]["ternary"]))
    by_gpu, pooled = entry["by_gpu"], entry["s_per_iter"]

    # ⚠ THE GUARD ON THE TEST ITSELF. If every per-card rate happened to equal the pooled median, every
    # assertion below would pass against a `arm_card_rate` that returned the median — i.e. the exact bug
    # this test exists to catch would be invisible. So require at least one card that genuinely differs,
    # and use THAT card as the discriminating case.
    differing = [g for g, v in by_gpu.items() if v and abs(float(v) - float(pooled)) > 1e-9]
    assert differing, (
        f"every per-card rate equals the pooled median ({pooled}), so this test cannot tell `by_gpu` from "
        f"the median and proves nothing. by_gpu={by_gpu}")

    for market_name, rate in by_gpu.items():
        assert tv.arm_card_rate(4.0, "ternary", market_name) == float(rate), "marketplace names too"
        short = market_name.replace("NVIDIA GeForce ", "")
        assert tv.arm_card_rate(4.0, "ternary", short) == float(rate), "and the short names the board uses"

    probe = differing[0]
    assert tv.arm_card_rate(4.0, "ternary", probe) != pooled, "arm_card_rate fell back to the pooled median"
    got, prov, note = at.expected_s_per_iter("ternary", 4.0, card=probe)
    # ★ RE-EXPRESSED 2026-08-01, NOT WEAKENED. This used to assert `prov == PROV_CARD` outright, which
    # conflated two independent claims: "the VALUE came from `by_gpu`" (this test's subject) and "that value
    # is a like-for-like expectation" (the system question, which `by_gpu` cannot answer — see
    # `test_a_figure_pooled_across_SYSTEMS_may_not_raise_the_dollar_flag`). The wiring claim is asserted
    # unconditionally; the provenance claim is DERIVED from the table's own composition, so a re-generated
    # artifact moves the expectation with it instead of turning the build red for the lane working.
    assert got == float(by_gpu[probe]), "the VALUE must be the per-card figure whatever its provenance"
    single_system = len(at.contributing_systems(4.0, "ternary", card=probe)) == 1
    assert prov == (at.PROV_CARD if single_system else at.PROV_OFFSYSTEM)
    if not single_system:
        assert "UNVALIDATED" in note and "POOLED ACROSS SYSTEMS" in note

    # An UNBENCHED card must have no per-card rate at all — a guard that guessed one could condemn a host on
    # a number nobody measured. Chosen as a card absent from the table rather than named, for the same
    # reason as everything above.
    import vast_cost_model as _v
    benched = {_v.card_of(g) for g in by_gpu}
    unbenched = next((c for c in ("RTX 4080S", "RTX 4080", "RTX 3080", "L4") if _v.card_of(c) not in benched),
                     None)
    assert unbenched, f"every candidate card is benched ({benched}) — pick another for the negative control"
    assert tv.arm_card_rate(4.0, "ternary", unbenched) is None, "an unbenched card has no per-card rate"
    got, prov, note = at.expected_s_per_iter("ternary", 4.0, card=unbenched)
    # The pooled-across-CARDS fact must survive verbatim even when the system check downgrades on top of it —
    # two defects in one figure, and a note that reported only the newer one would delete the older evidence.
    assert got == float(pooled) and "POOLED ACROSS CARDS" in note
    assert prov == (at.PROV_POOLED if len(at.contributing_systems(4.0, "ternary")) == 1
                    else at.PROV_OFFSYSTEM)


# =============================================================================================================
# ⛔ THE SYSTEM AXIS — an expectation measured on a different molecule cannot be "drift" (2026-08-01)
# =============================================================================================================
# trimcrae: "If it's a bigger molecule than our estimates are based on, it's gonna be more expensive. It's
# more important that we rank based on relative price per ns than actual." The offset cancels out of a
# RANKING (every offer scored against one table) and does NOT cancel in a realised-vs-quoted comparison.
def test_an_off_system_expectation_asserts_neither_drift_nor_the_buy_line():
    """★ THE LIVE FALSE POSITIVE THIS FIXES. `nr4a1 r1` quoted $0.00412/ns (1.21x basis) printed
    `⚠ realised $0.00889/ns` — ~2.6x "drift" — against a 4 fs ternary expectation with no `nr4a1` leg in it.
    The delivered rate is still stated; what is withheld is the claim that it MEANS anything."""
    v = at.verdict(40.0, 16.6, iteration=1088, interval=64, quoted_usd_per_ns=0.00412,
                   session_s=36000.0, provenance=at.PROV_OFFSYSTEM)
    assert v["verdict"] == at.KEEP
    assert v["realised_usd_per_ns"] > APPROVED_USD_PER_NS, "the arithmetic is unchanged — only the claim is"
    assert "UNVALIDATED" in v["why"] and "no drift and no buy-line comparison is asserted" in v["why"]
    assert "⚠" not in at.cell(v) and "drift" not in at.cell(v).lower()
    assert "40.0 s/iter" in at.cell(v), "the measured rate is the one thing that IS evidence — keep showing it"


def test_the_off_system_cell_never_renders_like_a_graded_one():
    """CLAUDE.md §1's `⚠ PAYING` vs `⛔ REFUSED` rule, one axis over: a row we CANNOT grade and a row that
    PASSED must not render alike. An off-system row says so even when it is fast, or a reader would take a
    silent cell for a cleared one."""
    fast = at.cell(at.verdict(8.0, 16.6, iteration=1089, interval=64, quoted_usd_per_ns=0.004,
                              provenance=at.PROV_OFFSYSTEM))
    slow = at.cell(at.verdict(40.0, 16.6, iteration=1089, interval=64, quoted_usd_per_ns=0.004,
                              session_s=36000.0, provenance=at.PROV_OFFSYSTEM))
    graded = at.cell(at.verdict(8.0, 16.6, iteration=1089, interval=64, quoted_usd_per_ns=0.004,
                                provenance=at.PROV_CARD))
    assert "no like-for-like expectation" in fast and "no like-for-like expectation" in slow
    assert "no like-for-like expectation" not in graded


@pytest.mark.parametrize("uid,want", [
    ("5aks_d0_to_d__ternary_nr4a1_r1_dt4.0fs_wu1.0_5aks", "nr4a1"),
    ("5aks_d0_to_d__ternary_nr4a3_r0_dt4.0fs_wu1.0_5aks_smoke", "nr4a3"),
    ("calib_hi_to_lo__ternary_vhl_r2_dt4.0fs_wu1.0_edge_reps", "vhl"),
    ("calib_hi_to_lo__binary_vhl_r0_dt4.0fs_wu1.0_edge", "vhl"),
    ("5aks_d0_to_d__ternary_nr4a3", "nr4a3"),                    # the truncated `leg_id` form
    ("calib_hi_to_lo__solvent_r0_dt4.0fs_wu1.0_edge", None),     # the solvent arm carries no system token
    ("", None), (None, None),
])
def test_the_system_token_is_read_from_the_unit_id(uid, want):
    """⚠ IDENTITY, NOT SIZE. `nr4a1` and `nr4a3` are two assemblies of nearly equal particle count, so
    `ternary_arm_rates.system_buckets` merges them at its 15 % tolerance and `pooled_across_systems` reads
    FALSE on a figure pooled across `nr4a3` and `vhl`. Only the id can tell them apart."""
    assert at.system_of_unit(uid) == want


def test_a_leg_whose_own_system_is_ABSENT_from_the_table_is_off_system():
    """The exact `nr4a1` case, asserted through the real artifact. DERIVED, not typed: the expectation is
    computed from the table's own composition, so a future `nr4a1` leg landing in the table flips this to
    like-for-like and the test follows instead of going red for the lane working."""
    systems = at.contributing_systems(4.0, "ternary", card="RTX 4090")
    assert systems, "composition unreadable — this test proves nothing; check `legs` in the rate artifact"
    absent = next(s for s in ("nr4a1", "nr4a3", "vhl", "zzznotasystem") if s not in systems)
    uid = f"5aks_d0_to_d__ternary_{absent}_r1_dt4.0fs_wu1.0_5aks"
    _, prov, note = at.expected_s_per_iter("ternary", 4.0, card="RTX 4090", unit_id=uid)
    assert prov == at.PROV_OFFSYSTEM and "UNVALIDATED" in note


def test_a_leg_whose_system_IS_the_table_keeps_its_like_for_like_expectation():
    """✅ THE POSITIVE CONTROL FOR THE SYSTEM AXIS — the warning must SURVIVE where it is earned, or this
    change has simply blinded the guard. Host-to-host spread on ONE system is 0.50-2.67x against a 1.745x
    card prediction; that is the real signal and removing the system offset sharpens it, not hides it."""
    # Chosen by the table's own composition rather than named, for the reason in the test above.
    single = [(dt, arm) for dt in (2.0, 4.0) for arm in ("binary", "ternary", "solvent")
              if len(at.contributing_systems(dt, arm)) == 1]
    assert single, "no single-system figure in the table — the positive control cannot be built"
    dt, arm = single[0]
    sysname = next(iter(at.contributing_systems(dt, arm)))
    uid = f"calib_hi_to_lo__{arm}_{sysname}_r1_dt{dt}fs_wu1.0_edge_reps"
    exp, prov, _ = at.expected_s_per_iter(arm, dt, unit_id=uid)
    assert prov == at.PROV_POOLED, "a single-system figure is NOT downgraded by the system check"
    v = at.verdict(exp * 4.0, exp, iteration=1088, interval=64, quoted_usd_per_ns=0.005,
                   session_s=36000.0, provenance=at.PROV_CARD)   # same figure, taken per-card
    assert "⚠" in at.cell(v) and v["realised_usd_per_ns"] > APPROVED_USD_PER_NS, \
        "a genuinely slow host on a system the table HAS measured must still be flagged"


def test_provenance_is_CARD_only_where_the_figure_describes_one_system():
    """THE PROPERTY, over every figure in the real table — the invariant the re-expressed wiring test above
    now leans on. A `$/ns` comparison is licensed exactly when the expectation behind it was produced by legs
    of a single assembly."""
    import ternary_vast_launch as tv
    doc = (tv.arm_iteration_rates(4.0, path=tv._ARM_RATES_PATH) is not None
           and tv._ARM_RATES_CACHE[tv._ARM_RATES_PATH])
    checked = 0
    for dt, arms in (doc.get("rates") or {}).items():
        for arm, entry in arms.items():
            for market_name in (entry.get("by_gpu") or {}):
                _, prov, _ = at.expected_s_per_iter(arm, float(dt), card=market_name)
                one = len(at.contributing_systems(float(dt), arm, card=market_name)) == 1
                assert at.licenses_dollar_comparison(prov) is one, (dt, arm, market_name, prov)
                checked += 1
    assert checked >= 5, f"only {checked} figures checked — the table is too small to prove the property"


def test_an_UNREAD_composition_keeps_the_provenance_it_earned():
    """CLAUDE.md §4a: an absent reading is not a reading of absence. If the leg records cannot be read, that
    is NOT evidence the expectation is off-system — and it is equally not evidence it is fine, so the note
    must SAY the check did not run. Silently switching the warning off on an unreadable artifact would be the
    same class of bug as the fabricated `prod_ns` echo."""
    assert at.contributing_systems(4.0, "ternary", path="/nonexistent/rates.json") == {}
    # `rates=` injects a table with no leg records at all: nothing to downgrade, nothing claimed.
    _, prov, note = at.expected_s_per_iter("ternary", 4.0, rates={"ternary": 16.6})
    assert prov == at.PROV_POOLED and "UNVALIDATED" not in note


def test_contributing_systems_never_returns_a_rate():
    """⚠ ONE FACT, ONE HOME (§1). The RATE lives in `arm_card_rate` / `arm_iteration_rates`; this function
    reads the same document only for WHICH LEGS produced it. A second path to the number is a second home."""
    got = at.contributing_systems(4.0, "ternary")
    assert got and all(isinstance(k, str) and isinstance(n, int) for k, n in got.items())


def test_an_unmeasured_expectation_cannot_condemn():
    """No arm rate for this timestep => no slowdown, no realised $/ns. The TIME test may still fire, because
    it needs no expectation at all — that independence is deliberate."""
    v = at.verdict(16.0, None, iteration=100, interval=64, quoted_usd_per_ns=0.005,
                   provenance=at.PROV_NONE)
    assert v["slowdown_vs_expected"] is None and v["realised_usd_per_ns"] is None
    assert v["verdict"] == at.KEEP


def test_a_host_that_is_over_the_buy_line_but_WILL_bank_is_KEPT():
    """Abandoning costs a ~28 min cold start. A host banking real work at a poor rate is a bad trade to
    replace, so the dollar view REPORTS and the time test ACTS. If this ever flips to ABANDON, the guard has
    started destroying hosts that were making progress."""
    v = at.verdict(40.0, 16.0, iteration=1088, interval=64, quoted_usd_per_ns=0.005,
                   session_s=36000.0, provenance=at.PROV_CARD)   # long session: it will reach the boundary
    assert v["verdict"] == at.KEEP
    assert v["realised_usd_per_ns"] > APPROVED_USD_PER_NS
    assert "reported, not acted on" in v["why"]


# =============================================================================================================
# ✅ THE POSITIVE CONTROL — it must actually fire
# =============================================================================================================
def test_a_host_that_cannot_reach_a_boundary_is_ABANDONED():
    """⚠ NOTE WHAT IT TAKES TO FIRE, because it is a finding in itself: the WORST rate measured today
    (36.9 s/iter) on the real 64-iteration grid reaches its boundary in ~39 min, INSIDE a 48 min budget — so
    this guard would not have condemned any host on today's data. Legs are not failing because MD is slow;
    they are failing during the ~28 min cold start, before MD begins. The guard is for the genuinely
    pathological host, and 60 s/iter is one."""
    v = at.verdict(60.0, 16.6, iteration=1088, interval=64, quoted_usd_per_ns=0.005, session_s=3600.0)
    assert v["verdict"] == at.ABANDON
    assert "cannot bank" in v["why"]
    assert v["seconds_to_next_commit"] > v["session_budget_s"]


@pytest.mark.parametrize("prov", [at.PROV_CARD, at.PROV_POOLED, at.PROV_OFFSYSTEM, at.PROV_NONE])
def test_the_TIME_test_is_untouched_by_provenance(prov):
    """★ THE ONLY TEST THAT ACTS NEEDS NO EXPECTATION AT ALL, and the system axis must not reach it. A host
    that cannot bank is a guaranteed loss whatever molecule it is running, and the independence of the time
    test from the throughput table is the reason this guard survives every table confound."""
    v = at.verdict(60.0, 16.6, iteration=1088, interval=64, quoted_usd_per_ns=0.005, session_s=3600.0,
                   provenance=prov)
    assert v["verdict"] == at.ABANDON and "cannot bank" in v["why"]


def test_the_PURCHASE_gate_is_not_reachable_from_this_module():
    """⛔ THE BUY LINE BINDS ON **QUOTED** RATES AT THE MOMENT OF RENTING, and that is a different file. This
    module is a POST-HOC readout: it imports the threshold to REPORT against and must never call a launcher,
    a market gate or a rental path, or a readout change would become a change to what the lane will buy."""
    import inspect
    src = inspect.getsource(at)
    for forbidden in ("relaunch_market_gate", "gpu_backend", "protfep_vast_launch", "congeneric_fanout",
                      "submit(", "retire_host", "destroy"):
        assert forbidden not in src, f"{forbidden!r} would make this readout able to move money"
    assert at.verdict(1.0, 1.0)["buy_line_usd_per_ns"] == APPROVED_USD_PER_NS


def test_the_same_host_on_a_short_grid_is_KEPT():
    """The discriminator is the INTERVAL, not the card. Halve the commit interval and the identical host
    banks fine — which is why the cadence lever and this guard are the same problem seen twice."""
    slow = at.verdict(60.0, 16.6, iteration=1088, interval=64, session_s=3600.0)
    fast = at.verdict(60.0, 16.6, iteration=1088, interval=8, session_s=3600.0)
    assert slow["verdict"] == at.ABANDON and fast["verdict"] == at.KEEP


# =============================================================================================================
# the arithmetic
# =============================================================================================================
def test_the_boundary_is_the_NEXT_one_even_when_sitting_exactly_on_it():
    """A leg that has just committed owes a full interval, not zero. Off-by-one here would report every
    freshly-committed host as banking instantly and never condemn anything."""
    assert at.seconds_to_next_commit(1088, 64, 1.0) == 64
    assert at.seconds_to_next_commit(1089, 64, 1.0) == 63
    assert at.seconds_to_next_commit(1087, 64, 1.0) == 1


@pytest.mark.parametrize("bad", [(0, 64, 1), (100, 0, 1), (100, 64, 0), (None, 64, 1), (100, 64, None)])
def test_degenerate_inputs_return_None_rather_than_a_number(bad):
    it, iv, spi = bad
    got = at.seconds_to_next_commit(it, iv, spi)
    assert got is None or got > 0


def test_realised_is_the_quote_REBASED_not_a_fresh_division():
    """The unit trap (STRATEGY Appendix A 61): the buy line lives in reference-GPU nanoseconds, so dividing
    dollars by real-assembly nanoseconds and comparing would repeat the very error that row registers. A
    host exactly at expectation must return the quote unchanged."""
    assert at.realised_usd_per_ns(0.005, 16.0, 16.0) == pytest.approx(0.005)
    assert at.realised_usd_per_ns(0.005, 32.0, 16.0) == pytest.approx(0.010)
    assert at.realised_usd_per_ns(0.005, 8.0, 16.0) == pytest.approx(0.0025)


def test_the_buy_line_is_IMPORTED_not_re_typed():
    """§1 — the abandon threshold and the buy line are the same test at different times, so they share one
    home. A second copy of 0.006539 here is the rule-1 bug this repo has already paid for."""
    import inspect
    src = inspect.getsource(at)
    assert "from inflight_usd_per_ns import APPROVED_USD_PER_NS" in src
    assert "0.006539" not in src
    assert at.verdict(1.0, 1.0)["buy_line_usd_per_ns"] == APPROVED_USD_PER_NS


# =============================================================================================================
# the readout — a decision nobody can see is a decision nobody can grade
# =============================================================================================================
def test_the_cell_carries_the_number_that_caused_the_verdict():
    ab = at.cell(at.verdict(60.0, 16.6, iteration=1088, interval=64, session_s=3600.0))
    assert "60.0" in ab and "CANNOT BANK" in ab
    assert at.cell(at.verdict(None, 16.6)) == "—"
    ok = at.cell(at.verdict(8.0, 16.6, iteration=1089, interval=64, session_s=3600.0))
    assert "8.0" in ok and "CANNOT BANK" not in ok


# =============================================================================================================
# the wiring — inputs must come from THIS host's own window, not from a config the leg may not be running
# =============================================================================================================
def test_the_interval_is_the_one_the_driver_RESOLVED_to():
    """`rbfe_spot_checkpoint` fixes the checkpoint interval when the .nc is CREATED, and `effective_interval`
    reads it back from the committed file — so a resumed leg runs the OLD grid whatever the mode now asks for
    (the 2026-07-21 `resume iteration 520 != expected 540` incident). A guard that timed the REQUESTED grid
    would mis-time every resumed leg, which is most of them."""
    import inflight_board as ib
    log = "[spot-driver] warmup_target=1600 (ci=64) prod_target=2000 (ci=40)"
    assert ib.committed_intervals(log) == (64, 40)
    assert ib.interval_for_phase(log, "warmup") == 64
    assert ib.interval_for_phase(log, "production") == 40
    assert ib.committed_intervals("no such line") is None
    assert ib.interval_for_phase("no such line", "warmup") is None


def test_collect_feeds_the_guard_from_the_log_window_and_the_unit_id():
    """No S3 read, no API call, nothing remembered — the guard must be free, or a per-row check would add a
    round trip per host per pass."""
    import inspect

    import ternary_vast_launch as tv
    src = inspect.getsource(tv)
    assert "import arrival_throughput as _at" in src
    assert 'ifb.interval_for_phase(_b["log"], _b["phase"])' in src, \
        "the interval must come from the host's own resolved line"
    assert '_dtm = re.search(r"_dt([\\d.]+)fs_", _b["uid"] or "")' in src, \
        "the timestep must come from the unit id"


def test_the_verdict_is_rendered_into_the_row_not_just_computed():
    """A decision nobody can see is a decision nobody can grade — the same rule that made the tier a column."""
    import inspect

    import ternary_vast_launch as tv
    src = inspect.getsource(tv)
    assert '"arrival": _arr' in src, "the numbers must reach the committed artifact"
    assert "_acell = _at.cell(_arr)" in src and "_wtxt = (_wtxt" in src, \
        "and the human-readable verdict must reach the board row"


def test_it_is_report_only_for_now_and_says_so():
    """§6's ladder is smoke -> one real leg -> fleet. Acting on ABANDON would make this the lane's SECOND
    destroyer beside `vast_idle_guard`; the honest step is to publish the verdict on a live fleet and read it
    before letting it destroy anything. This test exists so enabling the action is a DELIBERATE edit that
    fails a test named for the decision, not a quiet one."""
    import inspect

    import ternary_vast_launch as tv
    src = inspect.getsource(tv)
    i = src.index("import arrival_throughput as _at")
    window = src[max(0, i - 1500):i]
    assert "REPORT-ONLY" in window, "the posture must be stated where the call is made"
    # the action is deliberately NOT wired yet
    assert "retire_host(_b" not in src and "_at.ABANDON" not in src


def test_the_arrival_cell_is_NOT_suppressed_on_a_healthy_row():
    """MEASURED 5:29 PM ET 2026-07-31: the board's `why` is emitted only when `_cell_unknown` (% or ETA
    missing), so appending the arrival verdict there hid it on exactly the rows that HAVE a delivered rate —
    a healthy RUNNING leg. Both RUNNING rows rendered an empty `why` and the cell vanished. The verdict is
    composed into the final string unconditionally now."""
    import inspect

    import ternary_vast_launch as tv
    src = inspect.getsource(tv)
    assert '"why": _wtxt}' in src, "the row must render the composed string, not the suppressed one"
    assert '_wtxt = _swhy or (_why if _cell_unknown else "")' in src
    i = src.index("_acell = _at.cell(_arr)")
    assert "MUST NOT RIDE" in src[max(0, i - 900):i], "the suppression trap must be documented at the site"
