#!/usr/bin/env python3
import datetime,hashlib,json,pathlib,shutil,subprocess
ROOT=pathlib.Path(__file__).resolve().parent
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(n,d):(ROOT/n).write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
plan=json.loads((ROOT/'PLAN.json').read_text())
sources=[
 {'source':'ThreeTimePointFAPI46','doi':'10.2967/jnumed.122.264941','citation':'Naeimi et al. J Nucl Med2023;64:618–623. PMC11927082','status':'evaluated','resolution':'All14 released categorical rows account for43donors; two sarcomas remain generic. All three FAPI acquisition conditions identified.','conditions':'68Ga-FAPI-46 at10min/1h/3h after one injection;171lesions are dependent repeated measurements. No within-patient FDG comparator, exact calendar scan dates, generic sarcoma subtype/individual measurement crosswalk or patient treatment chronology released in inspected source.','EMC_authenticated':0,'unresolved_ids':['Sarcoma donor1 (no source ID)','Sarcoma donor2 (no source ID)'],'limitations':'Cannot exclude EMC among generic sarcomas. Published aggregate temporal uptake is prior art, not EMC knowledge. Source narrative diagnoses differ from Table1 (ovarian/esophageal categories); table totals43.','overlap':'Heidelberg single-center ethicsS016/2018; possible earlier Heidelberg cohorts, no public donor crosswalk. Do not pool as independent.','analysis':'three-timepoint-roster.json; clinical-eligibility-excerpts.json','access':'R5 S3 failure reused without retry; current PMC recaptcha and EuropePMC500 preserved; original JNM HTML/table now successfully evaluated.'},
 {'source':'Hirmas2023','doi':'10.2967/jnumed.122.264689','citation':'J Nucl Med2023;64:711–716','status':'evaluated','resolution':'Complete released macro roster accounts for324donors/21tumor entities after Other expansion; all18sarcoma subtype categories sum131; Other footnote11x1 inspected.','conditions':'Essen Oct2018–Oct2021, FAPI-04 n21/FAPI-46 n303. FAPI median uptake14min vs FDG67min; paired n237 overall/n116sarcoma; median interval0days(IQR2);159same-day pairs >=4h apart. Individual dates, generic identities, lesion/tracer crosswalk and no-intervening-treatment criterion unresolved. Median interval is not eligibility for every patient.','EMC_authenticated':0,'unresolved_ids':['Chondrosarcoma10','Fibrosarcoma11','Spindle cell sarcoma7','Pleomorphic sarcoma9','Round cell sarcoma2','soft tissue sarcoma1','myofibroblastic sarcoma1','vulvar sarcoma1'],'limitations':'No explicit EMC label or individual EMC measurement. Full aggregate source evaluation does not resolve these generic/subtype labels. No localization/tissue analysis performed.','overlap':'Supplement expressly reuses earlier Kessler47, Ferdinandus69, pitfalls91 subsets. SameNCT04571086 Essen registry as later reports; potential Lanzafame/Pabst overlap, exact patient crosswalk absent.','analysis':'hirmas2023-roster.json; clinical-eligibility-excerpts.json','access':'Primary HTML/Table1/original supplement recovered by ordinary JNM URLs.'},
 {'source':'Hirmas2024','doi':'10.2967/jnumed.123.266652','citation':'J Nucl Med2024;65:372–378','status':'demonstrably unsuitable measurement','resolution':'Main explicitly excludes sarcoma/pancreas/pleural mesothelioma; complete eight-entity roster sums115donors, paired accuracy subset103.','conditions':'Essen Oct2018–Mar2022; FAPI-04 first4/FAPI-46 remaining111; median pair interval0days,IQR2,max35days. No eligibility inference for EMC because sarcoma excluded.','EMC_authenticated':0,'unresolved_ids':[],'limitations':'A relevant suspected broader source is resolved as containing no eligible source-labelled sarcoma analysis, not a negative EMC uptake result.','overlap':'SameEssen registry and explicitly cited prior cohorts; excluded sarcoma results reported separately.','analysis':'hirmas2024-roster.json; clinical-eligibility-excerpts.json','access':'Main/Table1/original supplement evaluated.'},
 {'source':'InternationalFAPIInterobserver2023','doi':'10.2967/jnumed.122.265245','citation':'Mei et al. J Nucl Med2023;64:1043–1048','status':'pending accessible analysis','resolution':'All five10patient macro groups (sarcoma/CRC/PDAC/genitourinary/misc) and all released demographics evaluated; no complete subtype roster for50. Every four teaching-case diagnosis/condition was visually verified despite PDF glyph extraction failure.','conditions':'Retrospectively selected50 from Essen/Bologna, prospective15reader assessment,NCT04990882; mean14±9min afterFAPI46,min10/max48;34diagnostic CT available within2weeks. Referenceexpert clinical/histopathology/followup composite; no released samepatientFDG comparison. Guide callsFAPI04 whereas main/teaching saysFAPI46.','EMC_authenticated':0,'unresolved_ids':['All10source generic sarcoma rows have no released full IDs/subtypes; teaching cases not crosswalked'],'limitations':'Reader guide namesFAPI interobserver.xlsm with PatientsA-I tumor/PET fields, but workbook/full50datasets not linked by inspected main/supp indexes. Public availability unresolved; this is a remaining coverage gap, not completed50patient subtype analysis. Main misc list differs from an ovarian figure example.','overlap':'Essen/Bologna retrospective selection; exact crosswalk to Kessler/Hirmas/Essen cohorts and teaching examples unknown. No independent pooling.','analysis':'interobserver-teaching-eligibility.json; clinical-eligibility-excerpts.json','access':'Main/Table1, Guide_for_Readers.pdf, Teaching_Cases.pdf evaluated; no request made. Full workbook still pending.'},
 {'source':'LiverMetastases2026','doi':'10.1007/s44178-026-00295-4','citation':'Head-to-head comparison... Holistic Integrative Oncology2026;5:74. Published16Sep2026.','status':'evaluated','resolution':'All19entity Table1 categories sum76donors/189lesions. Original DOCX TableS1 all61donors/173metastatic lesions andS2 all15donors/16nonmetastatic lesions evaluated, with each donor tracer lesion totals checked.','conditions':'FUSCC May2020–Apr2023; FDG/FAPI04 within1week on different days, sameBiograph64mCTFlow,1h uptake each; newly diagnosed or lasttherapy>=3months. No donor-specific dates or intervening-treatment crosswalk. Liver verification composite>=3monthfollowup, mainly imaging not lesion histology; uses treatment response and FDG/CT/MR in reference.','EMC_authenticated':0,'unresolved_ids':['S1ID4:pleomorphic sarcoma; no molecular crosswalk'],'limitations':'No explicit EMC in any released donor row; source labels are not molecular exclusions. Main/supp terminology differs and11sarcoma/37lesion grouping appears to includeG2NET1/5; preserve classification ambiguity rather than relabel.','overlap':'FUSCC sameinstitution/ethics and time window potentially overlap Gu2022; exact donor IDs absent. Do not count lesions as independent or pool sources.','analysis':'liver2026-rosters.json; clinical-eligibility-excerpts.json','access':'Primary Springer HTML/Table1/original DOCX supplement recovered and evaluated.'},
]
write('COVERAGE.json',{'date_utc':now,'search_cutoff':'2026-10-04','claim':'No advancing EMC claim; bounded continuation of five R5 pending clinical imaging sources','source_classes':['Primary journal main text/tables','Original supplements and source indexes','EuropePMC bibliographic/fulltext API','Crossref DOI metadata','R5 verified clinical evaluations and source receipts'],'aliases':['extraskeletal myxoid chondrosarcoma','EMC','NR4A3','NR4A2','myxoid','chondrosarcoma','sarcoma','fibrosarcoma','spindle cell'],'selection':'Five sources prospectively fixed in PLAN. No convenient EMC subset; every released relevant roster category or donor observation evaluated at actual resolution.','sources':sources,'reused':['R5 clinical imaging negative/inconclusive evaluations unchanged; no rereading unavailable raw sources or retrying unchanged failedS3 routes','R5 prospective pair gate<=28days and no intervening therapy; no authenticated pair passed identity gate'],'pending_gaps_block_promotion':True,'global_search_exhausted':False,'restricted_scopes':'No FAP tissue, glycan, structural-genomics or HLA-review takeover; no tissue/localization inference. TMEM266 remains shelved.'})
rawpins=[{'path':str(p.relative_to(ROOT)),'bytes':p.stat().st_size,'sha256':sha(p),'disposition':'cache_only_preserved_ignored'} for p in sorted((ROOT/'raw').rglob('*')) if p.is_file()]
fullsource=[{'path':p.name,'bytes':p.stat().st_size,'sha256':sha(p),'disposition':'cache_only_full_source_derivative_preserved_ignored'} for p in sorted(ROOT.glob('*-paragraphs.json'))]
for n in ['liver2026-supp-text.txt','liver2026_table1-rows.json','three_timepoint_table1-rows.json']:
 p=ROOT/n
 if p.exists():fullsource.append({'path':n,'bytes':p.stat().st_size,'sha256':sha(p),'disposition':'cache_only_preserved_ignored'})
retained=sum(x['bytes'] for x in rawpins+fullsource)
assert retained<=64*1024*1024
free=shutil.disk_usage(ROOT).free;assert free>=10*1024**3
write('PORTABILITY.json',{'utc':now,'raw_and_source_derivative_bytes_including_copies':retained,'cap_bytes':64*1024*1024,'free_bytes':free,'inputs':rawpins+fullsource,'recovery':'Ordinary source URLs and exact downloaded bytes hashes in four fetch receipt files; source files retained under ignoredraw/. Cloud local cache is not Git portable. Complete clinical roster rows/selected eligibility excerpts/scripts are Git export. Reacquisition may produce changed HTML hashes; compare original sources/citations rather than silently substituting bytes.','R5_reuse':'Original Windows raw cache unavailable; verified committed R5 evaluation reused. Handoff lead verified all1,176git-export hashes, no mismatch; no recovery archive assumed available.'})
decision={'utc':now,'decision':'Shelve the standalone paper','scope':'Maintain R5 clinical FAPI standalone-paper shelving; finish this bounded five-source pilot without advancing manuscript.','validity':'No authenticated EMC diagnosis-to-scan pair found in actual evaluated source rows. This is an identity/measurement gate outcome, not evidence of absentFAPI uptake, low sensitivity or absentFAP.','value':'Broad sarcoma/FAPI uptake and tracer contrast/temporal behavior are already published. New source access and roster coverage are durable research evidence, not a disease discovery. No worthwhile EMC empirical contribution survives this packet.','surviving_demonstrated_findings':[],'new_followup':'No further source-value pilot proposed in this packet. Named-source lane and independent omission evaluation remain lead-owned; suitable accessible EMC evidence cannot be ignored.','reopen':'Concrete public author/molecular EMC identity-to-patient/lesion/scan crosswalk plus complete conditions,<=28daypair/nointerveningtherapy and lesion validation; resolve donor reuse and enough independent observations to add useful knowledge beyond source publications. Complete all eligible conditions and contradictory observations before promotion.','unfinished_promising_idea':'Interobserver workbook/full50subtypes may clarifyEMC eligibility if actually public; genericHirmas2023 andThreeTimePoint identities also unresolved. Availability/measurements/value not established, so these are specific coverage gaps rather than ranked findings.','TMEM266':'remains shelved','exhaustion':'Search not exhausted.'}
write('DECISION.json',decision)
(ROOT/'RESULTS.txt').write_text('Broader clinical FAPI continuation — '+now+'\n\nDECISION: Maintain shelving of the standalone EMC FAPI paper. No new publication-worthy EMC finding demonstrated. The search is not exhausted.\n\nFour newly accessible released rosters were evaluated completely at their published resolution: ThreeTimePoint43, Hirmas2023all324/131sarcoma, Hirmas2024all115, and Liver2026all76donor rows/189lesions. None supplied an authenticated EMC diagnosis-to-scan pair; generic labels remain unresolved. Hirmas2024 explicitly excluded sarcoma and is demonstrably unsuitable for EMC measurement. No ratio, effect estimate or EMC inferential statistic was computed, and the immutable R5<=28day/no-intervening-therapy gate was retained.\n\nInterobserver2023 remains incomplete at patient-subtype resolution: all50macrocategory counts and four published teaching-case captions were evaluated, but the full50-ID/diagnosis roster and named reader workbook were not released by inspected indexes. Ten sarcoma identities remain unresolved. Teaching examples are not additional independent donors. This pending evidence blocks any advancing absence/phenotype claim.\n\nDonor overlap: Hirmas2023 explicitly reuses47/69/91earlier cohorts. SameEssen registry and potential laterco-enrolment prevent independent pooling; FUSCC liver report may reuse Gu2022donors. Acquisition medians do not certify perpatientpair timing, and composite lesion verification is not independent histologic confirmation. Liver study cohort-classification and source-label differences, ThreeTimePoint narrative/table discrepancy and interobserver tracer/case-list discrepancies remain visible in COVERAGE and rosters.\n\nWhat matters: recovering exact subtypes can discriminate missing EMC evidence from an ineligible comparison. Here it resolves one suspected source as unsuitable and documents other unresolved identities; it does not create novel EMC biology. A future worthwhile conclusion requires an authentic case/measurement crosswalk, complete eligible observations/conditions, prior-art comparison and an independent omission challenge.\n\nRestricted interrupted tasks were not reopened. No FAP tissue/localization interpretation, outreach, paid resource, publication, external-record edit, PR or push was performed. Raw originals, full-source extracts and caption renders remain preserved ignored cache. Source hashes, clinical rows, scripts, actual access receipts and decisions are durable export; Git does not contain all primary bytes.\n')
elapsed=(datetime.datetime.now(datetime.timezone.utc)-datetime.datetime.fromisoformat(plan['frozen_utc'])).total_seconds()
write('EXECUTION.json',{'utc':now,'base_revision':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),'worker':'fapi_broader','model':'Inherited parent model; exact runtime model not exposed','effort':'Inherited','pilot_cap_minutes':25,'elapsed_seconds_at_freeze':elapsed,'source_value_stop':'Pilot completed early: no authenticated EMC and no newly feasible measurement comparison; no quantitative followup executed.','checks':['extract_clinical.py complete roster/lesion arithmetic assertions passed','64MiBretention/>=10GiBfree asserted','PDFcaption visual reading checkedAmerica/New_York17:57outside dailyban; allfour teaching cases evaluated'],'subscription_usage':'not exposed','process_status':'No owned source retrieval/analysis/browser/automation process remains.','ownership':'Only scopedround6/fapi_broader outputs written. Integrating lead owns main/push.'})
write('MANIFEST.json',{'utc':now,'scope':'Committed focused clinical evidence and scripts; seePORTABILITY for ignoredcached originals','files':[{'path':p.name,'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(ROOT.iterdir()) if p.is_file() and p.name!='MANIFEST.json' and p.name not in {x['path'] for x in fullsource}]})
print('Frozen',now,'retained bytes',retained,'free bytes',free,'elapsed seconds',round(elapsed))
