"""Assemble source-only scientific decision and cache portability; no expression access."""
from pathlib import Path
import json,hashlib,datetime,shutil
P=Path(__file__).resolve().parent
R=P.parent
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(n,d):(P/n).write_text(json.dumps(d,indent=2)+'\n')
assert datetime.datetime.now(datetime.timezone.utc)<datetime.datetime.fromisoformat('2026-10-05T22:15:00+00:00')
fn=Path('/workspace/emc-r6-fapi_named/research/autonomy/fresh-discovery-2026-10-05-round9/clinical_measurements/gpnmb_culture_context_quantification/SCIENCE-FREEZE.json')
sc=Path('/workspace/emc-r6-single_cell/research/autonomy/fresh-discovery-2026-10-05-round9/rna_processing/gpnmb_culture_independent_replay/SCIENCE-FREEZE.json')
assert sha(fn)=='f4ce461ef0243df2baa4c19129a2560e9f016ef5eb5bb28608bd9286602f93f4'
bindings=[]
for p in [R/'gpnmb_source_access_status/SCIENCE-FREEZE.json',R/'gpnmb_source_access_status/GSE299349-ALL68-EVALUATED-SOURCE-FIELDS.json',fn,sc,R/'gpnmb_exploratory_analysis_results/SCIENCE-FREEZE.json']:
 bindings.append({'absolute_read_only_path':str(p),'bytes':p.stat().st_size,'sha256':sha(p),'use':'Prior source/measurement status and frozen provenance only; no expression cells or outcomes read in this stage.'})
write('PRIOR-STATUS-REUSE.json',{'created_utc':now,'bindings':bindings,'completed_core':'All45 native source contexts (13 Hofvander,6 GSE24369,10 GSE4303,four GSE28866 3SEQ,12 published TempO) and permitted three-culture GPNMB features are already evaluated in prior packets. No repeated numerical work.','culture_status_supersession':'The earlier access packet predated culture evaluation; its pending ready-culture status is now superseded by the bound completed owner and independent replay. Current USZ23 feature is evaluated, not pending solely because of this role gate.','broader_unchanged_gaps':[{'source':'Brenca2019','scope':'12 native clinical cases plus5 matched preparations and11 engineered constructs; exact23 deposited records,8 engineered mapped/15 run-to-native-preparation labels unresolved; these counts are not new donors.','status':'Authentic clinical/native declaration exists, but individual public run/case/processed matrix bridge unresolved. Prior original metadata and access failures reused.'},{'source':'Davis2017','scope':'6 metastatic cases,5 RNA QC','status':'Whole-gene processed input unlocated; not expression absence or EMC-negative.'},{'source':'Zullow2022','scope':'7 published EMC RNA observations/11 clinical rows versus all138 public metadata records previously reconciled','status':'Public22 primary RNA rows are12 MLPS and10 ES; no ES numeric transfer to EMC. The published EMC/file bridge remains pending.'},{'source':'Filion2009','scope':'3 expression-array source observations','status':'Processed whole-gene/probe/case input linkage unlocated; no new retrieval.'},{'source':'Nottley2025','scope':'Donors9 and29,each pre/post radiotherapy;four conditions,notfour donors','status':'Full gene input unlocated; no new retrieval.'},{'source':'Ngo1041','scope':'Published broader mesenchymal bulk cohort','status':'Public author code expects local matrices. Genuine published supplement request previously timed out, officialOA record404, no repeated failing route. Suitable actual workbook/case/control input remains unresolved, not inferred absent.'}],'limitation':'This GSE299349 identity gate does not independently re-evaluate or clear all other current source omissions. Other named-owner source reviews govern later claims; this packet cannot grant publication clearance.'})
role=json.loads((P/'ALL68-EVALUATED-ROLE-DISPOSITIONS.json').read_text())
write('COVERAGE.json',{'created_utc':now,'actual_scope':'Every exact GSE299349 membership record was reconciled against existing allowed GEO fields and newly returned official BioSample identity metadata.','all68':{'records':68,'returned_BioSamples':68,'missing_BioSamples':0,'explicit_cell_type_records':6,'remaining_explicit_source_name_tissue_records':62,'exact_two_source_identity_agreement':True,'already_evaluated_EMC_culture':1,'additional_source_labelled_EMC':0},'histotype62':role['previous62_tissue_label_counts'],'identity_conclusion':'All62 are explicitly submitted as MFS,SS,UPS,MPNST or LMS. Lack of a cell_type attribute does not erase source_name/tissue diagnoses. This is source-label eligibility, not independent histopathological verification.','condition_role_gaps':'Individual donor/sample lineage, native-versus-model provenance, repeat/passage/treatment/preparation and comparator exchangeability are not established by these short metadata fields. No undefined roles or accession arithmetic were used to create extra EMC conditions.','processed_access':'All68 retained GEO records declare processed quant.sf.gz links and polyA RNA. A declaration establishes a public source link, not transcript capture, case identity or additional ready EMC input. No quantities or archive were opened.','outward_link_scope':'Every accepted BioSample links only its corresponding GEO sample and common BioProject PRJNA1273954. No additional author case/condition manifest was linked by this schema.','primary_access':'Exact official PMID41651400 metadata has no PMC/OA copy and only subscription-required DOI full text. No primary body, alternate article, preprint or restricted scientific mechanism was pursued.','remaining_access_status':'No additional ready authentic EMC quantity established in this exact68 universe. Other authentic native/public-file bridges remain separately unresolved and cannot be declared exhausted or cleared here.','requests':{'actual_new_calls':2,'maximum_authorized':4,'timeouts_seconds_each':10,'scope':'One exact primary availability query and one batched efetch of all68 author-declared BioSamples.'},'no_new_values_or_statistics':True})
write('DECISION.json',{'created_utc':now,'status':'SOURCE-SPECIFIC NO ADDITIONAL EMC NUMERICAL STAGE','scientific_result':'The exact68 record metadata contains one already evaluated source-labelled EMC culture and67 source-labelled other sarcomas. No additional EMC observation or technical replicate is authenticated by these fields.','correction':'The earlier62-generic-identity classification was wrong at source-label scope: the retained GEO source_name/tissue fields already specified five non-EMC histotypes. BioSample confirms them. Original frozen packet remains intact and correction is additive.','practical_consequence':'There is no new native-EMC GPNMB feature to count from these62 records. Do not expand the exploratory RNA claim by treating generic library roles or model aliases as EMC, or use an unrelated low-grade sarcoma as LGFMS.','value':'Source eligibility correction improves claim-specific coverage but is not a discovery. The existing narrow bulk EMC–LGFMS RNA association is reused; this gate adds no phenotype, efficacy, localization or tumor-cell inference.','exposure':'Previously known GPNMB values are acknowledged. In this stage only allowed identity/method/access fields and source unit counts were inspected; no new expression, outcome matrix, mechanism body or numerical contrast was opened.','numerical_followthrough':'Not triggered because no additional source-labelled EMC record emerged. All currently ready three-culture features were already evaluated and independently replayed.','reopening':['A genuine author-published correction or case/library manifest directly labels an additional native EMC record and its preparation/condition role.','A source-linked public processed file supports ordinary GPNMB capture for that authenticated added EMC input. Freeze all added conditions,units,controls,normalization,alternative and defeat prospectively and obtain the integrating lead/independent scientific assessment before quantities.'],'claim_limits':'No global absence/exhaustion or complete coverage/novelty/publication clearance; submitted diagnoses are not independent pathological re-review or proof of donor independence. Missing protein pairing is not used as a veto on descriptive bulk RNA.','source_science_closed_utc':now,'new_quantities':0,'new_statistics':0,'new_primary_body_inspections':0})
raw=[]
for p in sorted((P/'raw-cache').iterdir()):
 if p.is_file():raw.append({'path':'raw-cache/'+p.name,'bytes':p.stat().st_size,'sha256':sha(p),'storage':'Ignored cache-only original metadata; not exported to Git.'})
retained=[Path('/workspace/emc-r6-single_cell/research/autonomy/fresh-discovery-2026-10-05-round9/rna_processing/model_population_processed_source_gate/raw/GSE299349-series-brief.txt'),R/'gpnmb_source_access_status/raw-cache/GSE299349-individual-GSM-brief.txt']
write('PORTABILITY.json',{'created_utc':now,'new_originals':raw,'new_raw_bytes':sum(r['bytes'] for r in raw),'raw_cap_bytes':67108864,'shared_originals_read_only':[{'absolute_path':str(p),'bytes':p.stat().st_size,'sha256':sha(p),'use':'Actual accession/publication links and whitelisted source_name/tissue/cell_type/library declarations only; full originals are not Git exports.'} for p in retained],'derived_cap_bytes':4194304,'free_bytes':shutil.disk_usage('/workspace').free,'source_links':'Exact official public URLs are frozen in query,access and BioSample link receipts. No credentials or paid/private access.','replay':'validate_cached_sources.py checks locked original bytes,source identity fields and all68 evaluated dispositions without network or biological quantities. Acquisition scripts require their frozen original routes and must not be re-run as unchanged requests.'})
(P/'REPORT.txt').write_text('All 68 GSE299349 library records were checked against retained GEO and current official BioSample identity metadata. The 62 previously called generic records already had explicit GEO source_name/tissue diagnoses: 14 myxofibrosarcoma, 12 synovial sarcoma, 13 undifferentiated pleomorphic sarcoma, 11 malignant peripheral nerve sheath tumor and 12 leiomyosarcoma. BioSample confirms those literal diagnoses. The earlier summary overlooked them because they lacked a separate cell_type attribute; that error is corrected additively, with the original packet preserved.\n\nThe remaining six records have direct cell_type labels, including the previously authenticated and now evaluated USZ23 EMC culture. No additional EMC observation or replicate is source-labelled among these 68. This is an eligibility conclusion from submitted diagnoses, not independent pathological verification. Individual donor, model, preparation, treatment and technical-repeat roles remain unestablished. The actual GSM9037835 alias is USZ-20_REA1 and its explicit BCOR-rearranged sarcoma label remains visible; no alias overrides the diagnosis and no underlying rearrangement mechanism was inspected.\n\nTwo bounded official calls were used: exact primary availability metadata and one all68 BioSample efetch. The primary has subscription-required full text, so no body or alternative copy was accessed. BioSample supplies only the corresponding GEO and common BioProject outward links; it supplies no new case/condition manifest. All68 declared processed quant links are retained without opening values. The three culture features and all45 native core RNA contexts were already evaluated and are reused.\n\nNo additional EMC numerical stage is warranted from this metadata universe. The existing narrow GPNMB bulk RNA association remains subject to the other source, mixture, dependence and prior-art limits. This source correction does not establish a new biological result or clear publication. A genuine author case/library correction directly identifying added EMC conditions with usable processed measurements would reopen this gate. No new quantities, effects, RNA matrices, primary mechanism bodies or biological outcome analyses were read here.\n')
print(json.dumps({'closed_utc':now,'raw_bytes':sum(r['bytes'] for r in raw),'free_bytes':shutil.disk_usage('/workspace').free,'decision_sha256':sha(P/'DECISION.json'),'coverage_sha256':sha(P/'COVERAGE.json')}))
