import json,pathlib,hashlib,datetime,shutil,re
B=pathlib.Path(__file__).resolve().parent
R=pathlib.Path('/workspace/Rare-cancers/research/autonomy')
W=pathlib.Path('/workspace/emc-r6-fapi_named/research/autonomy/fresh-discovery-2026-10-05-round9/clinical_measurements')
def read(p):return json.loads(p.read_text())
def put(n,j):(B/n).write_text(json.dumps(j,indent=2)+'\n')
def bind(p,scope):return {'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'scope':scope}
paths=[W/'clinical_adc_rna_coverage_review/OTHER-EMC-ASSAY-COVERAGE.json',W/'fusion_partner_rna_coverage_review/ADDITIONAL-NATIVE-RNA-IDENTITY-REUSE.json',W/'fusion_partner_rna_coverage_review/NATIVE-RNA-PENDING-COHORT-REUSE.json',R/'fresh-discovery-2026-10-05-round8/microenvironment/COVERAGE.json',R/'fresh-discovery-2026-10-05-round8/microenvironment/TEMPO-SOURCE-GATE.json',R/'fresh-discovery-2026-10-04-round6/single_cell/BO112-CORRECTED-CONDITION-DISPOSITIONS.json',R/'fresh-discovery-2026-10-04-round6/single_cell/BO112-RECONCILIATION-AMENDMENT.json',R/'fresh-discovery-2026-10-05-round9/public_resource_omissions/COVERAGE.json',R/'fresh-discovery-2026-10-05-round8/adc_targets/MODEL-RESULTS.json',R/'peerj21497-source-2026-09-06/article.xml']
put('SOURCE-BINDINGS.json',{'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sources':[bind(p,'Reused source identity/assay/access conditions only; no new GPNMB cells') for p in paths]})
j=read(paths[4]);rows=[{k:x[k] for k in ['sample_alias','run_accession','sample_accession','experiment_accession']} for x in j['all12_library_ids']]
put('TEMPO12-CONDITION-COVERAGE.json',{'source':bind(paths[4],'Si/run/BioSample identities only'),'primary':bind(paths[-1],'Selected source design/participant/TempO normalization methods and clinical Table1 metadata'),'conditions':rows,'source_patients':12,'patient_count_confidence':'Primary calls final cohort12 patients; all12 Si library columns. Individual Si-to-clinical-row/donor/purity/treatment linkage not shown by aggregated Table1; cross-cohort overlap unresolved. Do not infer partner from four EWSR1-negative cases.','cohort':'Archival FFPE2008-04-21 to2018-06-19; Siriraj/Columbia; two-pathologist WHO review; initial22,15 informative,one outlier excluded,two prognostic-record exclusions; selected final12. Selection and preservation affect generalization. No same-assay LGFMS/MLPS controls.','processing':'Whole-transcriptome targeted TempO probes; UQ-normalized log2CPM; published9909genes vs released9500 discrepancy; library units notTPM. Source S009 GPNMB row7134/header independently authenticated by single_cell; values unopened.','processed_source':{'path':str(R/'tmem266-tissue-2026-10-03/peerj-source-s009.xlsx'),'sha256':'20165fd3ff09ec2d5a24b3c20b78515f42a3309119f248ed055c7484deb45e75','bytes':1423709,'status':'suitable published processed native context pending prospective numerical evaluation'},'raw_reconstruction':'Old raw-estimator benchmark failure does not invalidate the published processed row; no raw stage reopened.','purity_treatment':'No numeric purity or per-Si pre-treatment assignment recovered in inspected source fields; treatment metadata collected but unresolved per processed column.'})
a=read(paths[1]);br=[{k:x[k] for k in ['case','NR4A3_partner','sex','age','site']} for x in a['conditions'] if x['source'].startswith('Brenca')]
put('NATIVE-TISSUE-SOURCE-CONDITIONS.json',{'scope':'Relevant identified native contexts outside13/6/10/4; source limits retained, no new expression values. Counts do not establish independence.','Brenca12':{'cases':br,'assay':'Native12 clinical RNA plus5 matched frozen preparations4EWS/1TAF; not17 donors. PRJNA692081 has23 retained sample associations,8 known engineered4EN/4TN and15 unmapped. Clinical preservation/library alias bridge unresolved.11 engineered/control design is not a23-row assignment by subtraction.','status':'Source-defined native cohort; public deposited sequences not a suitable processed GPNMB matrix; CRO processed route previous HTTPtimeout/HTTPS503/migration barriers reused, not retried. Native mapping pending.'},'other_sources':[
 {'source':'Davis2017 DOI10.18632/oncotarget.15568 PMC5400622','conditions':'6 male metastatic EMC;5 RNA QC-passing,5 fresh biopsies+1 archival source; one inadequate RNA notzero.','status':'Native published RNA source; exact whole-gene GPNMB processed case/control map unlocated; no new value. Somatic GPNMB mention is not RNA measurement.'},
 {'source':'Zullow2022 GSE179720','conditions':'7 declared EMC RNA observations versus11 clinical rows; exact RNA-specimen/donor mapping unresolved.','status':'Public source/potential processed context pending matrix-case linkage; not7 independent donors or absentRNA.'},
 {'source':'Nottley2025 UCL','conditions':[{'donor':'9','times':['pre-RT','post-RT']},{'donor':'29','times':['pre-RT','post-RT']}],'status':'2 donor paired treatment contexts; prior source has published selected differential genes, no authenticated per-donor full matrix/accession recovered. Actual GPNMB availability unresolved, notzero.'},
 {'source':'Crombe4 prior coverage shorthand','conditions':'Four native RNA observations cited in reused coverage; exact primary/source-column/treatment map not yet authenticated in this bounded review.','status':'Retained mandatory unresolved source pointer; not exclusion or pooled replication.'},
 {'source':'Filion2009 DOI10.1002/path.2445','conditions':'3 native expression arrays;3 displayed Western specimens one shared with arrays+4 additional Western conditions.','status':'Native expression source pending public GPNMB probe/processed specimen mapping; Western conditions are not RNA replication.'},
 {'source':'Sjogren2003 PMID12598313 PMC1868116','conditions':'2 different-fusion native EMC microarrays versusMLPS.','status':'Prior native source; detailed primary failed500/challenge routes reused, no repeat. GPNMB assay mapping unavailable through inspected routes, not measured negative.'},
 {'source':'Indio2018 DOI10.1200/JCO.2018.36.15_suppl.11561/Stacchiotti2019 DOI10.1016/S1470-2045(19)30319-5','conditions':'12 treatment-naive native7EWS/5TAF; published immune deconvolution/IHC.','status':'Whole-gene GPNMB processed RNA source/case map unlocated; potential clinical-study overlap unresolved; limited published immune endpoints not full GPNMB evidence.'},
 {'source':'PGR2022 PMC9489176 DOI10.1200/PO.22.00039','conditions':'One35F pregnancy-associated cellular authorEMC PGR-NR4A3 recurrent RNA-profile case.','status':'Rare native case relevant contrary context; full public GPNMB profile unlocated; known endocrine findings not transferred to typicalEMC.'},
 {'source':'Racanelli2020 DOI10.3389/fonc.2020.00489','conditions':[x['case'] for x in a['conditions'] if x['source'].startswith('Racanelli')],'status':'14 source clinical cases; targeted fusion-panel measurements do not demonstrate whole-gene GPNMB quantification. Released endpoint unsuitable for this RNA question; patient overlap unresolved.'},
 {'source':'Fusion-microarray2013 DOI10.1371/journal.pone.0070649','conditions':'168/97 native case; tentative known historical overlap with Hofvander168-97/MDB9736:4.','status':'Custom junction/intragenic assay not authenticated GPNMB gene expression; not independent tissue replication.'},
 {'source':'Barresi2025 DOI10.1007/s00428-025-04352-7','conditions':'Unusual author-labelled HSPA8-NR4A2 case, not canonicalNR4A3 cohort.','status':'Detailed transcriptome request-only; no canonical donor transfer.'}]})
b=read(paths[5]);bo=[{k:x.get(k) for k in ['accession','title','corrected_status','basis','donor_key','limitation']} for x in b['rows']]
put('BO112-CORRECTED26-CONDITIONS.json',{'source':bind(paths[5],'All26 corrected condition status/donor/source identity masks'),'amendment':bind(paths[6],'Supersedes original20nonEMC/6pending and unsafe numericcode transfer'),'rows':bo,'summary':{'library_conditions':26,'source_nonEMC':16,'pending':10,'pending_current_donors':6,'authenticated_EMC':0},'limit':'Library/sort/region/time conditions are not independent donors. Pending10 source diagnosis mapping may be resolvable and has public RNA; notnegative/unavailable. No prior-provider numericcode histology transfer.'})
put('BROADER-COHORT-OMISSIONS.json',{'sources':[
 {'source':'ORIEN1340 PMID40328759 PMC12055966','conditions':'Generic MyxoidChondrosarcoma12overall; RNA9samples/avatars7primary2metastatic,3FFPE6freshfrozen; no authenticatedEMC/patient crosswalk.','status':'Scientific identity pending; individual RNA request-only/Aster/ORIEN scope unavailable via inspected public release. Aggregate workbooks unsuitable for individual GPNMB comparison; not pending known accessible matrix.'},
 {'source':'Ngo2025 PMC12728484 DOI10.1002/cac2.70077','conditions':'External1041bulk mesenchymal cohort EMCS legend; scRNA8specimens7patients+4spatial EpS do not authenticate nativeEMC.','status':'Potential public bulkEMC source/case/overlap/processed expression mapping pending; no transfer from EpS spatial specimens.'},
 {'source':'CASSIS/CellSARC/GS001/Luthria','conditions':'Expanded CASSIS39subtype roster/70CITEselection; CellSARC Tx primary donor map; LuthriaGSE243380 fresh technical source/S1 outside prior21 GSE243381 libraries.','status':'Public relevant source identity/library-to-donor/assay schema pending; no subtypecode transfer or absence inference.'},
 {'source':'fmTLS2026 PMC13255587 DOI10.3390/cancers18111685','conditions':'219 limb/trunkprimary1990–2020; noinitialmet/neoadjuvant. EMC within39Other/15subtypes;RNA126of146extractable after20QCfail. CT/PT/R1/NT microdissected regions notEMC-mapped.','status':'All public primary/supp tables evaluated; individual data privacy restricted. ActualEMC count/regionGPNMB linkage unavailable through inspected public release, notabsence.'},
 {'source':'ADC2025 PMC12528890 DOI10.1016/j.esmoop.2025.105837','conditions':'2344 input cases/26datasets versus1664selected sixhistotypes LPS476/LMS341/UPS330/GIST286/SS126/MFS105; selection>100/histotype.','status':'Full26input roster/EMC mapping pending; declaredS1HEAD403 unavailable tested attachment, noGET/retry/alternate. MainMethods safe section does not authenticate GPNMB RNA inclusion; GPNMB body mention notassay. Four IHCmarkers other thanGPNMB.'},
 {'source':'GPNMB-IHC2025 PMID40389121 DOI10.1016/j.humpath.2025.105799','conditions':'Broader~1000sarcoma GPNMBIHC source, actual nativeEMC roster unresolved.','status':'Primary403/noOA inspected byRT; no duplicate retrieval. Published protein contextual endpoint distinct RNA; native identity/assay observations pending/unavailable through tested route.'},
 {'source':'PanAtlas1172 PXD054790/ProCan1260 PXD056810','conditions':'Prior annotation rosters fully evaluated; PanAtlas ninegenericSARC identities pending; literalEMC colorectal abbreviations not sarcoma. ProCan privateISKS11 individualhistology unresolved.','status':'Protein endpoints not interchangeableRNA; no authentic nativeGPNMB RNA source proven. Generic/private source coverage stayspending, no inaccessible bypass.'},
 {'source':'CPTAC-SAR/2026MASTER-CATCH-INFORM1998','conditions':'Prior305metadata/88CPTAC-SARcases noauthenticatedEMC, proteomicsinprogress;1998clinical release not established by fourCPTAC portal indexeddiagnosis lists.','status':'No public nativeGPNMB clinicalRNA manifest authenticated. Source-specific unknown roster/release, notglobalabsence.'},
 {'source':'SubramanianGSE213065/212527/212526 and released broader scRNA cohorts','conditions':'Prior87bulk/7single/4spatial and other exact released rosters evaluated; noauthenticatedEMC. Remaining broader352pediatricfamily/celllinePRJCA021248/GSE157220/89samplepreprint underlyingconditions pending.','status':'Reuse exact nonEMC identities at inspected source scope; unreviewed family/generic conditions not excluded by title.'}]})
model=read(paths[8]);put('CULTURE-COVERAGE-CORRECTION.json',{'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'original_wrong_file':bind(paths[0],'Historical shorthand USZ22/GSM2113319 is a typo; old freeze preserved'),'authoritative_model_map':bind(paths[8],'Accepted R8 condition_map not expression fields'),'correct_ids':{'V1-34':'GSM2113301','USZ22':'GSM6883080/GSE221532','USZ23':'GSM9037837'},'accepted_prior_rows_affected':False,'basis':'The accepted R8 condition_map already uses the correct IDs; only the later coverage shorthand was wrong. No accepted values transferred by typo.','prospective_contexts':[{'model':'V1-34','condition':'GSM2113301','measurement':'ARCHS4 gene-count row context currently available; gene identity and denominator require fixed GPNMB source gate; no values here.'},{'model':'USZ22','condition':'GSM6883080/GSE221532','measurement':'ARCHS4 context and newly authenticated unique USZ22 deposited count column (owner source gate); other ambiguous labels remain unresolved.'},{'model':'USZ23','condition':'GSM9037837','measurement':'Public RefSeq quantification present; GPNMB current official gene-to-transcript mapping/capture and historical accessions pending, no value accepted.'},{'model':'USZ20-EMC1/NCC-EMC1-C1','condition':'Distinct authentic drug-screen cultures','measurement':'No suitable whole-gene processed GPNMB RNA located in reviewed source; drug screens are not RNA assay.'}], 'units':'ARCHS4 roundedKallisto estimatedcounts notTPM/readcounts; USZ23RefSeq quantities not automatically comparable across annotation. Technicalruns do not increase donors; USZ23/USZ20lineage overlap unresolved; cultures not independent native tissue controls.','culture_alternative':'Adaptation versus native tissue must be tested where assays permit, never automatic excuse or pooled validation. H-EMC-SS disputed/engineered contexts remain separate.'})
put('DECISION.json',{'status':'PROSPECTIVE NUMERICAL STAGE MAY BE CONTRACTED; PUBLIC-COVERAGE PROMOTION HOLD','numerical_authorization':False,'use':'A fixed native bulkRNA EMC-vs-LGFMS/MLPS association could guide next tissue compartment/localization comparisons. Disease-specific enrichment is not universal ADC-use prerequisite and no therapy inference follows.','finite_comparison':'Root/owner may authorize source-qualified all13Hof+all6newarray/all10oldarray/allFOUR3SEQ as assay-separated comparisons with relevant source controls, plus mandatory published12TempO within-assay native context and nativecultures as separate adaptation contrasts after gene/capture gates. No merged standardized pool or donor-independence assertion. TempO has no same-assay LGFMS; cannot replicate that histology effect alone.','promotion_blockers':'Suitable public unresolved identity/measurement sources (BO11210/Ngoexternal1041/CASSIS/CellSARC/Luthria/Zullow and unknown broader inputs) must receive explicit final dispositions. Request-onlyORIEN/TLS and deniedADC2025S1 are distinct unavailable/pending identity cases. Brenca/native olderpublishedRNA remains case/processing unresolved. No new measurements made here.','reopening':'Resolve actual donor/condition/processed gene maps with authorized ordinary source access and fixed use/disproof; append evidence without changing frozen prior failed panels or selecting favorable subsets.','claim_boundary':'No new finding, no protein localization/dependency/benefit, no biologicalnegative from unmeasured/missing data, no exhausted search. TMEM266 remains shelved.'})
put('ACCESS-AND-READ-SCOPE.json',{'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'new_requests':0,'new_retained_original_bytes':0,'read_scope':'Reused metadata/source evaluative records; selected primary clinical/methods text; no GPNMB cells/new matrices/statistics.','incidental_exposure':'Initial broad section title filter exposed clinical survival/prognostic/methodology narrative and aggregateclinical followup Table1; none retained as phenotype values or used in GPNMB inference. Later whitelist limited primary read todesign/participants/TempO normalization. No denied content or images inspected.','source_methods':'Primary clinical source says selected12patientcohort; exact Si-to-purity/treatmentcase map remains unavailable from inspected aggregate metadata. No newly inferred independence.','restrictions':'NoGETon alreadydeniedADCattachment, no alternateworker route/no login/bypass. Fullsourceinputsreadinplace notcopied. >=10GiBfree checked.','free_bytes':shutil.disk_usage(B).free})
(B/'REPORT.txt').write_text('The broader gate retains published TempO-seq GPNMB readiness for all 12 selected native EMC samples. The source uses archival FFPE, upper-quartile normalized log2CPM and has no same-assay LGFMS controls; the individual Si-to-treatment/purity clinical map remains unresolved. The previous raw reconstruction failure does not invalidate this processed table.\n\nA bounded all-condition bulk-RNA comparison can be planned, with native cultures evaluated separately for adaptation and annotation limits. This gate authorizes no numerical stage and supplies no finding. Promotion remains on hold while suitable public case/measurement identities and relevant broader input cohorts are unresolved. BO112 coverage is the corrected 16 source-non-EMC/10 pending conditions, not the historical 20/6 split. The 2025 ADC study selected 1,664 cases from 2,344 inputs; its denied attachment leaves the full 26-dataset input roster unresolved, without evidence of EMC absence.\n\nThe historical USZ22/GSM2113319 coverage typo is corrected additively to GSM6883080/GSE221532; accepted R8 model maps already used the correct identities. No new gene values, source downloads, matrices or statistics were inspected. This checkpoint supplies source-bound coverage and uncertainty, not a manuscript or campaign exhaustion.\n')
