import {readFileSync} from "node:fs";
function auditHla(r){
 const samples=r.selected_sample_fields,patients=r.selected_patient_hla_fields,matrix=r.selected_hla_matrix_literal_cells,ids=r.hla_matrix_matching_columns,loci=["A","B","C"],fields=loci.flatMap(l=>[1,2].map(j=>"HLA-"+l+j)),sm=new Map(samples.map(s=>[s.SAMPLE_ID,s])),pm=new Map(patients.map(p=>[p.PATIENT_ID,p])),allowed=new Set(["ENTITY_STABLE_ID","HLA_GENE",...ids]);
 if(r.errors.length||r.source_revision!=="dca75cb3f32b82d54a6f78bf0a6323e5b975aca1")throw Error("Unverified retrieval");
 const hashes={"data_clinical_sample.txt":"22db6ca4689303e9178645df5f7a6a18f0b6b1288aff160097df688438760072","data_clinical_patient.txt":"64cd81c349345f1abb31e68fdeb8e068a742b20b4e36bfd9d8293218eea0de10","data_hla_loh.txt":"ebfd192cac394008c1691a86da58df69259a2a223b67c981032e48963e2e5b66"};
 for(const [file,hash]of Object.entries(hashes)){const source=r.sources.find(x=>x.file===file);if(!source||source.sha256!==hash||source.lfs_hash_and_size_verified!==true)throw Error("Unverified source "+file);}
 if(samples.some(s=>s.CANCER_TYPE_DETAILED!=="Extraskeletal Myxoid Chondrosarcoma"||s.ONCOTREE_CODE!=="EMCHS")||matrix.some(row=>Object.keys(row).some(k=>!allowed.has(k)))||sm.size!==samples.length||pm.size!==patients.length)throw Error("Projection/identifier problem");
 const typed=patients.filter(p=>p.HLA_GENOTYPE_AVAILABLE==="True"),twoField=a=>a.split("_").slice(0,4).join("_");
 const checked=ids.map(id=>{const s=sm.get(id),p=pm.get(s?.PATIENT_ID);if(!s||!p)throw Error("Unlinked sample");const alleles=fields.map(f=>p[f]),carried=matrix.filter(row=>alleles.includes(row.ENTITY_STABLE_ID)),other=matrix.filter(row=>!alleles.includes(row.ENTITY_STABLE_ID));if(carried.length!==6)throw Error("Allele join");return {patient:s.PATIENT_ID,concordant:carried.every(row=>row[id]===s["HLA_"+fields[alleles.indexOf(row.ENTITY_STABLE_ID)].slice(4)+"_LOH"]),allUnchanged:carried.every(row=>row[id]==="Unchanged"),otherAllelesNA:other.every(row=>row[id]==="NA")};});
 const qc=(called)=>Object.fromEntries([...new Set(samples.map(s=>s.FACETS_QC))].map(q=>[q,samples.filter(s=>ids.includes(s.SAMPLE_ID)===called&&s.FACETS_QC===q).length]));
 return {schema:"emc-hla-availability-audit/1",sourceRevision:r.source_revision,samples:sm.size,patients:pm.size,genotypedPatients:typed.length,patientsWithoutGenotype:pm.size-typed.length,allTypedHeterozygous:typed.every(p=>loci.every(l=>twoField(p["HLA-"+l+"1"])!==twoField(p["HLA-"+l+"2"]))),samplesWithPublishedCalls:ids.length,patientsWithPublishedCalls:new Set(checked.map(x=>x.patient)).size,samplesWithoutPublishedCalls:sm.size-ids.length,concordant:checked.every(x=>x.concordant),allUnchanged:checked.every(x=>x.allUnchanged),nonCarriedAllelesNA:checked.every(x=>x.otherAllelesNA),facetsQC:{called:qc(true),withoutCalls:qc(false)},decision:"Stop standalone EMC HLA prevalence paper; four selected patients insufficient",limitations:["Literal published Unchanged classifications; no independent allele recalling.","Non-carried allele NA cells are structural, not missing assay observations.","No inference about population prevalence, protein, antigen presentation, immune escape or treatment efficacy.","Original study HLA analysis restricted to96histologies with>=50patients; EMC13patients does not meet that criterion.","EMC absence checked in primarybody/keyresources only; supplementsS25/S6 unread."]};
}
console.log(JSON.stringify(auditHla(JSON.parse(readFileSync(process.argv[2],"utf8"))),null,2));
