import {readFileSync} from "node:fs";
import {createHash} from "node:crypto";
function parseCSV(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===","&&!quoted){row.push(cell);cell="";}else if(c==="\n"&&!quoted){row.push(cell.replace(/\r$/,""));rows.push(row);row=[];cell="";}else cell+=c;}if(quoted)throw Error("Unclosed quote");if(cell||row.length){row.push(cell.replace(/\r$/,""));rows.push(row);}const h=rows.shift();return rows.filter(r=>r.some(x=>x!=="")).map(r=>{if(r.length!==h.length)throw Error("CSV width");return Object.fromEntries(h.map((k,i)=>[k,r[i]]));});}
function methylationFeasibility(rows){
 const u=k=>new Set(rows.map(r=>r[k])).size;if(u("id")!==rows.length||u("idat")!==rows.length)throw Error("Duplicate specimen");
 const tally=(rs,k)=>Object.fromEntries([...new Set(rs.map(r=>r[k]))].sort().map(v=>[v,rs.filter(r=>r[k]===v).length]));
 const withChip=rows.map(r=>({...r,chip:r.idat.split("_")[0]})),groups=[...new Set(rows.map(r=>r.cls))].sort().map(cls=>{const rs=withChip.filter(r=>r.cls===cls),sup=tally(rs,"supplier"),chips=tally(rs,"chip"),feasible=counts=>Object.entries(counts).filter(([k,n])=>n>=3&&rs.length-n>=5).map(([k,n])=>({group:k,test:n,train:rs.length-n}));return {className:cls,n:rs.length,supplierCounts:sup,chipCounts:chips,oneSupplier:Object.keys(sup).length===1,supplierMajority:Math.max(...Object.values(sup))>rs.length/2,chipMajority:Math.max(...Object.values(chips))>rs.length/2,eligibleSupplierHoldouts:feasible(sup),eligibleChipHoldouts:feasible(chips)};});
 const rare=groups.filter(r=>r.n<=10),emc=groups.find(r=>r.className==="methylation class extraskeletal myxoid chondrosarcoma"),es=rows.filter(r=>r.cls===emc.className);
 return {schema:"sarcoma-methylation-metadata-feasibility/1",profiles:rows.length,uniqueIDAT:u("idat"),referenceClasses:groups.length,rareThreshold:10,rareClasses:rare.length,rareProfiles:rare.reduce((n,r)=>n+r.n,0),rareOneSupplier:rare.filter(r=>r.oneSupplier).length,rareSupplierMajority:rare.filter(r=>r.supplierMajority).length,rareChipMajority:rare.filter(r=>r.chipMajority).length,missing:Object.fromEntries(["batch","manifestation","site"].map(k=>[k,rows.filter(r=>r[k]==="").length])),exploratoryHoldoutCriterion:{minimumTest:3,minimumTrain:5,rareClassesWithAnyEligibleSupplier:rare.filter(r=>r.eligibleSupplierHoldouts.length).length,rareClassesWithAnyEligibleChip:rare.filter(r=>r.eligibleChipHoldouts.length).length,rareClassesWithEveryEligibleSupplier:rare.filter(r=>r.eligibleSupplierHoldouts.length===Object.keys(r.supplierCounts).length).length,rareClassesWithEveryEligibleChip:rare.filter(r=>r.eligibleChipHoldouts.length===Object.keys(r.chipCounts).length).length},emc:{...emc,dna:tally(es,"dna"),manifestation:tally(es,"manifestation")},classDetails:groups,limitations:["Reference classes include62tumorclasses and3controls; not65sarcomaentities.","Physical chip inferred fromIDAT basename is not asserted biological batch.","Metadata concentration does not demonstrate confounding, classifier failure or performance degradation.","No methylation signal matrix, classifier fit, CNV or new diagnostic result was analyzed.","Holdout thresholds are exploratory feasibility cutoffs, not power guarantees.","Original study included nested calibration and independent428case validation."]};
}
const bytes=readFileSync(process.argv[2]);
const expected="c3b102c078a1035f4589952ea8b50ff3a8fbbb63ed8edd425aed2ea343119a19";
if(createHash("sha256").update(bytes).digest("hex")!==expected)throw Error("Mirror hash mismatch");
const rows=parseCSV(bytes.toString("utf8")).map(r=>({id:r.ID,idat:r.IDAT,cls:r.Methylation_Class_Name,supplier:r.Supplier,dna:r.DNA,manifestation:r.Manifestation,site:r.Site,batch:r.Batch}));
console.log(JSON.stringify(methylationFeasibility(rows),null,2));
