import {readFileSync} from "node:fs";
import {createHash} from "node:crypto";
function auditRegistryUnits(inputs,corpus,reread,raw){
 const rows=corpus.C2_arms,rr=reread.R2_per_arm_rows,groups=new Map();
 for(const r of rows){const k=JSON.stringify([r.nct_id,r.arm_title]);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r);}
 const repeated=[...groups.values()].filter(v=>v.length>1),hist={};for(const rs of groups.values())hist[rs.length]=(hist[rs.length]||0)+1;
 const cells=r=>JSON.stringify(["CR","PR","SD","PD"].map(k=>r.cells[k])),ns=rows.map(r=>r.evaluable_n).sort((a,b)=>a-b),median=a=>a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2;
 const counts={tableRows:rows.length,trials:new Set(rows.map(r=>r.nct_id)).size,titleKeys:groups.size,repeatedTitleKeys:repeated.length,rowsInRepeatedKeys:repeated.reduce((n,v)=>n+v.length,0),extraRowsBeyondOnePerTitleKey:rows.length-groups.size,multiplicityHistogram:hist,trialsWithRepeatedTitles:new Set(repeated.map(rs=>rs[0].nct_id)).size,repeatedKeysWithSameSum:repeated.filter(rs=>new Set(rs.map(r=>r.evaluable_n)).size===1).length,repeatedKeysWithDifferentCells:repeated.filter(rs=>new Set(rs.map(cells)).size>1).length,medianReconstructedN:median(ns),nBelow10:ns.filter(n=>n<10).length,nBelow20:ns.filter(n=>n<20).length,zeroResponses:rows.filter(r=>r.cells.CR+r.cells.PR===0).length,zeroAmongNAtLeast10:{zero:rows.filter(r=>r.evaluable_n>=10&&r.cells.CR+r.cells.PR===0).length,total:ns.filter(n=>n>=10).length},zeroAmongNAtLeast20:{zero:rows.filter(r=>r.evaluable_n>=20&&r.cells.CR+r.cells.PR===0).length,total:ns.filter(n=>n>=20).length}};
 const consistency={inputsEqualCorpus:JSON.stringify(inputs.arms)===JSON.stringify(rows),rereadAligned:rows.length===rr.length&&rows.every((r,i)=>r.nct_id===rr[i].nct_id&&r.arm_title===rr[i].arm_title&&cells(r)===cells(rr[i])&&r.evaluable_n===rr[i].n),rereadDropsOutcomeTitle:rr.every(r=>!("outcome_measure_title"in r)),fourCategorySumMatches:rows.every(r=>r.evaluable_n===["CR","PR","SD","PD"].reduce((s,k)=>s+r.cells[k],0)),allUnitsParticipants:rows.every(r=>r.unit_of_measure==="Participants")};
 if(Object.entries(consistency).some(([k,v])=>!v))throw Error("Source consistency failed");
 const patterns={CR:/^\s*(complete response|complete remission|CR)\b/i,PR:/^\s*(partial response|partial remission|PR)\b/i,SD:/^\s*(stable disease|SD)\b/i,PD:/^\s*(progressive disease|disease progression|PD)\b/i};
 const primary=["NCT05323656","NCT04268277"].map(id=>{const s=raw.studies.find(s=>s.protocolSection.identificationModule.nctId===id);if(!s)throw Error("Missing primary case");return {nctId:id,enrollment:s.protocolSection.designModule?.enrollmentInfo?.count,responseTables:s.resultsSection.outcomeMeasuresModule.outcomeMeasures.map((o,index)=>({o,index})).filter(({o})=>(o.classes||[]).some(cl=>(cl.categories||[]).some(c=>patterns.SD.test(c.title||"")))).map(({o,index})=>({sourceOutcomeIndex:index,title:o.title,type:o.type,timeFrame:o.timeFrame,populationDescription:o.populationDescription||null,paramType:o.paramType,unit:o.unitOfMeasure,groups:o.groups.map(g=>{const cats=(o.classes||[]).flatMap(cl=>cl.categories||[]),all=cats.map(c=>({title:c.title,value:c.measurements.find(m=>m.groupId===g.id)?.value??null})),cc={};for(const c of all){const k=Object.keys(patterns).find(k=>patterns[k].test(c.title||""));if(k&&c.value!==null&&Number.isInteger(Number(c.value)))cc[k]=Number(c.value);}const complete=Object.keys(patterns).every(k=>k in cc),den=(o.denoms||[]).filter(d=>d.units==="Participants").flatMap(d=>d.counts).find(c=>c.groupId===g.id);return {groupId:g.id,title:g.title,postedDenominator:den?Number(den.value):null,cells:cc,allFourLabels:complete,reconstructedSum:complete?Object.values(cc).reduce((n,x)=>n+x,0):null,allPostedCategories:all,corpusRows:rows.filter(r=>r.nct_id===id&&r.arm_title===g.title&&r.outcome_measure_title===o.title).length};})}))};});
 return {schema:"response-table-unit-audit/1",baseCommit:"af7211708205b5189d8c537c1ce2a23aa4bea076",counts,consistency,primaryRegistryChecks:primary,repeatedTitleGroups:repeated.map(rs=>({nctId:rs[0].nct_id,title:rs[0].arm_title,records:rs.map(r=>({outcome:r.outcome_measure_title,n:r.evaluable_n,cells:r.cells,source:r.retrieved_file}))})),limitations:["Posthoc exploratory extraction audit, not a preregistered solid-tumor benchmark.","Repeated title keys are not confirmed duplicate patients or independent arms.","Purposive source cases do not estimate discrepancy prevalence.","Four-category sum is reconstructed, not automatically posted analysis denominator.","No unique-patient count, pooled response or efficacy inference."]};
}
const expected=["d66060ca0acea0bb70fbb0e478ca5a3a5a8c4309","343922742f88f63a1803dba26904c45369c73d07","79c82a02cf5ce8534154896db140c9b67e88a892","f125b25e71104dc7db4f3134c3632406e88a9033"];
if(process.argv.length!==6)throw Error("Pass inputs.json corpus.json reread.json rawBOR2022.txt");
const texts=process.argv.slice(2).map((path,i)=>{const b=readFileSync(path),h=createHash("sha1").update(Buffer.from("blob "+b.length+"\0")).update(b).digest("hex");if(h!==expected[i])throw Error("Git blob mismatch "+path);return b.toString("utf8");});
const marker=texts[3].indexOf("=".repeat(30)),raw=JSON.parse(marker<0?texts[3]:texts[3].slice(texts[3].indexOf("\n",marker)+1));
console.log(JSON.stringify(auditRegistryUnits(...texts.slice(0,3).map(t=>JSON.parse(t)),raw),null,2));
