// From repository root: node research/autonomy/data-opportunities-2026-09-30/analysis/registry_search.mjs
import {readFileSync} from "node:fs";
import {createHash} from "node:crypto";
function analyzeRegistrySearch(conditionText,phraseText){
 const docs=[JSON.parse(conditionText),JSON.parse(phraseText)];
 const id=s=>s.protocolSection.identificationModule.nctId;
 const strings=(v,path=[],out=[])=>{if(typeof v==="string")out.push({path:path.join("."),value:v});else if(Array.isArray(v))v.forEach((x,i)=>strings(x,[...path,i],out));else if(v&&typeof v==="object")Object.entries(v).forEach(([k,x])=>strings(x,[...path,k],out));return out;};
 const summaries=docs.map((d,i)=>{const ids=d.studies.map(id).sort();if(ids.length!==new Set(ids).size||d.totalCount!==ids.length||d.nextPageToken!==undefined)throw Error("Incomplete/duplicate archived response");const hits=d.studies.flatMap(s=>strings(s.resultsSection).filter(x=>/extraskeletal\s+myxoid/i.test(x.value)).map(x=>({nctId:id(s),...x})));return {strategy:i?"phrase":"condition",query:i?'query.term="extraskeletal myxoid"':"query.cond=extraskeletal myxoid chondrosarcoma",total:ids.length,ids,hasResults:d.studies.filter(s=>s.hasResults===true).length,resultsSectionCount:d.studies.filter(s=>s.resultsSection!==undefined).length,versionHolders:[...new Set(d.studies.map(s=>s.derivedSection?.miscInfoModule?.versionHolder))],phraseStringHits:hits.length,recordsWithExplicitPhrase:[...new Set(hits.map(x=>x.nctId))],resultIDs:d.studies.filter(s=>s.hasResults).map(id).sort()};});
 const a=summaries[0].ids,b=summaries[1].ids;
 const extra=docs[1].studies.find(s=>id(s)==="NCT00642941");if(!extra)throw Error("Missing example");
 const outcomes=extra.resultsSection.outcomeMeasuresModule.outcomeMeasures.flatMap((o,index)=>{const gs=(o.groups||[]).filter(g=>/extraskeletal\s+myxoid/i.test(g.title||""));if(!gs.length)return [];const ids=new Set(gs.map(g=>g.id));return [{sourceIndex:index,title:o.title,type:o.type,unitOfMeasure:o.unitOfMeasure,timeFrame:o.timeFrame,groups:gs,denoms:(o.denoms||[]).map(d=>({...d,counts:d.counts.filter(c=>ids.has(c.groupId))})),classes:(o.classes||[]).map(c=>({...c,categories:(c.categories||[]).map(cat=>({...cat,measurements:(cat.measurements||[]).filter(m=>ids.has(m.groupId))}))}))}];});
 const flow=extra.resultsSection.participantFlowModule;const fg=flow.groups.find(g=>/extraskeletal\s+myxoid/i.test(g.title||""));
 return {schema:"registry-search-audit/1",baseRevision:"af7211708205b5189d8c537c1ce2a23aa4bea076",archivedRetrievalDate:"2026-09-12",retrievalDateProvenance:"Committed trial-subgroup-extraction.json and scripts/emc_trial_results.py, not embedded response timestamp",summaries,conditionOnly:a.filter(x=>!b.includes(x)),phraseOnly:b.filter(x=>!a.includes(x)),commonRecordsIdentical:docs[0].studies.every(s=>JSON.stringify(s)===JSON.stringify(docs[1].studies.find(x=>id(x)===id(s)))),extraRecord:{nctId:id(extra),conditions:extra.protocolSection.conditionsModule,flowGroup:fg,flowPeriods:flow.periods.map(p=>({title:p.title,milestones:p.milestones.map(m=>({...m,achievements:m.achievements.filter(a=>a.groupId===fg.id)})).filter(m=>m.achievements.length)})),emcOutcomes:outcomes},limitations:["Queries change field and expression together; no isolated field effect or retrieval sensitivity estimated.","No fresh registry query or exhaustive alias adjudication.","Outcome group IDs are scoped to individual modules/outcomes.","R1507 clinical outcomes were published previously; registry and article are same study."]};
}
const root="research/literature/emc-census-2026-09-12/sources/";
function load(name,hash){const b=readFileSync(root+name);if(createHash("sha256").update(b).digest("hex")!==hash)throw Error("Input hash mismatch");return b.toString("utf8");}
console.log(JSON.stringify(analyzeRegistrySearch(load("clinicaltrials-discovery.json","f45b8eb11625e2f2049c43086032951dfaf955bc63683b78dfdba8d87999bb9d"),load("clinicaltrials-fulltext-discovery.json","b1beb99dcc3a9a5ad006ed810ebb2fec68a56d222bc12987b5acf954a46f11bc")),null,2));
