#!/usr/bin/env python3
"""Re-derive the PROXIMITY clause of km_risk_row_detect.decide() from preserved geometry alone.

IPD-SURVIVAL-2 established that 11 of 15 figure verdicts re-derive from what the committed artifact
preserves, with ONE clause exempt: `near_enough_to_tick_labels`, which needs each mark's y0/y1 and
only cy was recorded. This script consumes the artifact REGENERATED by the additive y0/y1 change and
re-computes that clause independently, then re-checks the full conjunction that decides `present`.

The clause, copied structurally from decide():

    near_enough = min(t.y0 for t in band) - max(t.y1 for t in bands[ref]) <= max_risk_gap

and at the pixel call sites `max_risk_gap = MAX_RISK_GAP * <figure height in px>`. For an EMBEDDED
image the recorded `image_px` is `el.srcsize`, which is the same (w, h) `_image_from` builds the
Image with, so image_px[1] IS img.height; for a page-raster crop `image_px` is literally
[crop.width, crop.height]. For the TEXT arm the denominator is `page.bbox[3]`, which the artifact
does not record -- those rows are reported NOT re-derivable rather than agreed.

⛔ Nothing is loosened. Constants are parsed out of the source file, never retyped.
"""
import json, re, sys

SRC = "research/modalities/km_risk_row_detect.py"


def const(name):
    m = re.search(rf"^{name}\s*=\s*([0-9.]+)", open(SRC).read(), re.M)
    return float(m.group(1))


MAX_RISK_GAP = const("MAX_RISK_GAP")
MIN_MARKS = const("MIN_MARKS")
MIN_MATCHED_TICKS = const("MIN_MATCHED_TICKS")
MAX_MARK_WIDTH = const("MAX_MARK_WIDTH")

doc = json.load(open(sys.argv[1]))
rows, agree, disagree, notderiv = [], 0, 0, 0
for src in doc["sources"]:
    for fi, f in enumerate(src["figures"]):
        row = {"source_id": src["source_id"], "figure_index": fi, "page": f.get("page"),
               "arm": f.get("arm"), "caption_head": f.get("caption_head"),
               "recorded_verdict": f["verdict"], "bands": []}
        ref = f.get("tick_label_band_index")
        H = f.get("image_px", [None, None])[1]
        if ref is None or not f.get("bands"):
            row["proximity_rederivable"] = False
            row["why"] = "no band geometry recorded (undetermined before any band was measured)"
            notderiv += 1
            rows.append(row); continue
        if f.get("arm") != "pixel" or H is None:
            row["proximity_rederivable"] = False
            row["why"] = ("text arm: the proximity denominator is page.bbox[3], which the artifact "
                          "does not record")
            notderiv += 1
            rows.append(row); continue
        thr = MAX_RISK_GAP * H
        refband = f["bands"][ref]
        if any("y1" not in m for m in refband["marks"]):
            row["proximity_rederivable"] = False
            row["why"] = "y0/y1 absent -- artifact predates the additive change"
            notderiv += 1
            rows.append(row); continue
        ref_bottom = max(m["y1"] for m in refband["marks"])
        row["figure_height_px"] = H
        row["max_risk_gap_px"] = round(thr, 2)
        row["tick_label_band_bottom_y1"] = ref_bottom
        ok = True
        for b in f["bands"]:
            if b["index"] <= ref:
                continue
            top = min(m["y0"] for m in b["marks"])
            gap = top - ref_bottom
            derived = gap <= thr
            rec_ = b.get("near_enough_to_tick_labels")
            match = (rec_ == derived)
            ok &= match
            # the full present-conjunction, re-derived
            conj = (b["n_marks"] >= MIN_MARKS and b["matched_ticks"] >= MIN_MATCHED_TICKS
                    and b["median_mark_width_frac"] <= MAX_MARK_WIDTH and derived)
            row["bands"].append({
                "index": b["index"], "n_marks": b["n_marks"],
                "matched_ticks": b["matched_ticks"],
                "median_mark_width_frac": b["median_mark_width_frac"],
                "band_top_y0": top, "gap_px": round(gap, 2),
                "gap_as_fraction_of_height": round(gap / H, 4),
                "derived_near_enough": derived, "recorded_near_enough": rec_,
                "agrees": match,
                "truncated_marks": b["n_marks"] > len(b["marks"]),
                "derived_qualifies_as_risk_row": conj,
                "margin_px_to_proximity_boundary": round(thr - gap, 2),
            })
        derived_present = [b["index"] for b in row["bands"] if b["derived_qualifies_as_risk_row"]]
        row["proximity_rederivable"] = True
        row["all_proximity_flags_agree"] = ok
        row["derived_risk_row_band_index"] = derived_present[0] if derived_present else None
        row["recorded_risk_row_band_index"] = f.get("risk_row_band_index")
        row["derived_verdict_from_geometry"] = "present" if derived_present else "absent"
        row["verdict_agrees"] = (row["derived_verdict_from_geometry"] == f["verdict"]
                                 or f["verdict"] == "undetermined")
        agree += ok
        disagree += (not ok)
        rows.append(row)

out = {
    "_what": ("re-derivation of the proximity clause of km_risk_row_detect.decide() from the "
              "per-mark y0/y1 that the additive change preserves"),
    "_not_medical_advice": ("Instrument provenance only. Nothing here is a clinical, efficacy, "
                            "safety, selectivity or prognosis claim, and no curve was digitised."),
    "constants_parsed_from_source": {"MAX_RISK_GAP": MAX_RISK_GAP, "MIN_MARKS": MIN_MARKS,
                                     "MIN_MATCHED_TICKS": MIN_MATCHED_TICKS,
                                     "MAX_MARK_WIDTH": MAX_MARK_WIDTH},
    "n_figures": len(rows),
    "n_proximity_rederivable": agree + disagree,
    "n_all_flags_agree": agree,
    "n_disagree": disagree,
    "n_not_rederivable": notderiv,
    "figures": rows,
}
print(json.dumps(out, indent=2, ensure_ascii=False))
sys.exit(0 if disagree == 0 else 1)
