"""Freeze metadata and choices without reading any expression values."""
from pathlib import Path
import json,hashlib,datetime,collections
D=Path(__file__).resolve().parent
R=Path('C:/Projects/EMC-Research/research/autonomy')
paths=[R/'atlas-hofvander-validation-2026-09-06/metadata-manifest.json',R/'atlas-hofvander-validation-2026-09-06/replication-manifest.json']
m=json.loads(paths[0].read_text());a=json.loads(paths[1].read_text())
emc=[s for s in m['samples'] if s['diagnosis']=='Extraskeletal myxoid chondrosarcoma']
primary=[s for s in emc if s['primary_lesion']]
hist=['Myxoid liposarcoma','Low-grade fibromyxoid sarcoma','Myxofibrosarcoma']
context=['MPNST','Rhabdomyosarcoma, embryonal','Rhabdomyosarcoma, alveolar','Rhabdomyosarcoma, NOS','Rhabdomyosarcoma, sclerosing','Lipoma','Hibernoma','Myxoma Class 1','Myxoma Class 2','Schwannoma','Lipoblastoma']
allocation={h:[s['sample_id'] for s in m['samples'] if s['diagnosis']==h and s['primary_lesion']] for h in hist+context}
plan={'frozen_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'question':'Is appreciable DLK1 gene-level RNA reproducibly present in EMC tissue, and is its pattern consistent enough across assays and authentic models to motivate a specific direct isoform/protein-localization experiment?',
'prior_art_gate':'Searches found no explicit EMC DLK1 primary finding. Subramanian2005 full SAM list lacks searched DLK1 identifiers; this is not a negative measurement. Original reports already establish a neural/neuroendocrine expression phenotype in EMC, so that broad phenotype is not new. Filion supplementary tables and Sjogren source completeness remain visible coverage gaps; independence reviewer is searching broader DLK1 cohorts. Proceed with a bounded empirical pilot, not manuscript advancement.',
'gene':{'symbol':'DLK1','entrez':'8788','aliases':['FA1','PREF1','Pref-1','preadipocyte factor 1','fetal antigen 1']},
'composition_context_genes':['COL1A1','ACTA2','PTPRC','DES','MYOD1','PAX7'],
'primary':{'source':'Hofvander2026 retained TPM matrix','sample_ids':[s['sample_id'] for s in primary],'n':len(primary),'unit':'TPM','operational_abundance_gate':'At least 8/12 primary specimens >=10 TPM AND median >=10 TPM. These are prospective resource-allocation thresholds, not validated biological or target thresholds. A failed gate does not prove no expression.','independence':'12 specimen labels; patient_group equals sample_id in metadata, not a definitive external donor crosswalk. Do not pool across studies or count historical subset as independent.'},
'sensitivities':{'historical_no_known_discovery_overlap_ids':[s['sample_id'] for s in emc if s['eligible']],'all13_ids':[s['sample_id'] for s in emc],'purpose':'Retain all eligible EMC measurements; historical 9 is a sensitivity, not a new independent cohort. Recurrent specimen 5081-14 shown separately.'},
'comparisons':{'same_study_primary_ids_by_histology':allocation,'primary_histologies':hist,'context_histologies':context,'metrics':['raw values, n, median, range','A=Pr(EMC>control)+0.5*Pr(tie), descriptive','2000 resample specimen bootstrap percentile95% intervals for primary median and A, seed41026','same-sequencing-year A where both groups exist','leave-one-EMC-out A range'],'inference':'No confirmatory p-value threshold; one biologically chosen gene, several exploratory contrasts. Enrichment and disease exclusivity are not required for an appreciable RNA phenotype. Bootstrap reflects sampled specimens and cannot repair batch/confounding/overlap.'},
'cross_assay':{'GSE24369':'All6 EMC, all available LGFMS17/MFS6/desmoid6/SFT5 and2 skeletal-muscle pools. Original RMA log2 signal. Map all unambiguous DLK1/Entrez8788 probes from GPL6244, retain each; median probes only as transparent summary. Direction/heterogeneity descriptive, donor overlap with Hofvander unresolved; no independent replication claim.','GSE4303':'All10 labelled EMC; audit every platform, probe and channel/reference before contrast. Do not compare different reference pools as common-scale ratios. All suitable accessible EMC values must be evaluated before any claim advancement.','PeerJ12':'All12 published filtered matrix; absence of DLK1 row is filtered absence, not zero. Raw TempOSeq gene measurement remains pending if absent.','GSE71119':'Verify source and every eligible EMC condition; metadata-only source pointer not treated as evaluation.'},
'models':{'V1-34_GSM2113301':'One biological library, two technical SRA runs; archived ARCHS4 rounded estimated counts and CPM using all-row denominator.','USZ22_GSM6883080':'One authentic TAF15::NR4A3 culture; ARCHS4 CPM descriptive, not TPM.','USZ23_GSM9037837':'One original RefSeq Salmon quantification; DLK1 transcript mapping must be source-verified; sum mapped TPM, retain all mapped rows. Unknown donor independence from USZ20.','unavailable_authentic':'USZ20 and NCC-EMC1-C1 public expression not yet recovered; source-verified unavailability must remain visible.','uncertain_identity':'HEMC-SS is separate context, never proof of EMC expression or absence.','interpretation':'No formal across-model replicate test. Culture expression may support tumor-intrinsic plausibility but does not locate expression in original tissue. Culture absence prompts source/condition checks; cannot be explained away.'},
'defeaters':['Same useful DLK1 EMC finding already published','Weak or heterogeneous tissue abundance fails operational allocation; do not change threshold','Probe/reference ambiguity prevents claimed cross-assay result','Material contrary authentic tissue/model evidence unexplained','Composition dependence or normal-tissue signal prevents claimed tumor localization','No worthwhile new biological interpretation beyond an RNA nomination'],
'automatic_followup':'Audit adverse/probe/identity/condition evidence, source-linked published measurements, all eligible EMC and independent challenge. A technical pass is insufficient; explicitly reassess scientific value. Do not replace DLK1 with another gene. No manuscript while suitable accessible EMC remains pending.',
'limits':['RNA does not establish cell-surface or membrane isoform, protein abundance, dependency, therapeutic window or response.','Expression in other cancers alone does not defeat EMC phenotype value.','Known RMS/MPNST/normal progenitor expression and sarcoma RNA-protein discordance are material alternatives.'],
'metadata_hashes':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths},'all_emc_metadata':emc,'array_metadata':a['array_samples']}
assert len(primary)==12 and len(emc)==13
target=D/'PLAN.json';assert not target.exists(),'Immutable plan already exists'
target.write_text(json.dumps(plan,indent=2)+'\n')
print(json.dumps({'frozen_utc':plan['frozen_utc'],'sha256':hashlib.sha256(target.read_bytes()).hexdigest(),'n_primary':12,'comparison_counts':{k:len(v) for k,v in allocation.items()}}))
