import datetime,hashlib,json,pathlib,re
expected=[('PROTAC','result_20240515193524.txt','dcf19e2d71ad98055770c2aa40ab6aded039f67fe80954eadb2a5220d9756cf2',12316),('MGD','result_20240515203824.txt','16e4c0a3aa866040d55ec6374395974a68d97326203e08b047e766cb3c1d2b16',19032)]
out={'schema':'deepternary-released-embedded-config-metadata/1','completedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'embeddedConfigs':[],'limits':['Metadataonly repair; no inference/scoring/geometryreplay.','Configuredvalidation/testoverlap nothistoricaltraining/selectionreconstruction.']}
for task,name,digest,size in expected:
 paths=list(pathlib.Path('campaign-output/deepternary-released-files').rglob(name));assert len(paths)==1,name;path=paths[0];raw=path.read_bytes();assert len(raw)==size and hashlib.sha256(raw).hexdigest()==digest;lines=raw.decode().splitlines();matches=[{'line':i+1,'text':s} for i,s in enumerate(lines) if re.search(r'test_dataloader|val_dataloader|protac22\.txt|test_all\.txt|val_interval|max_epochs|train_clusters|known_pocket_info',s)]
 def section(label):
  starts=[i for i,s in enumerate(lines) if re.match(r'^'+re.escape(label)+r'\s*=',s)];assert len(starts)==1;start=starts[0];end=next((i for i in range(start+1,len(lines)) if re.match(r'^[A-Za-z_]\w*\s*=',lines[i])),len(lines));m=re.findall(r"complex_names_path\s*=\s*['\"]([^'\"]+)['\"]",'\n'.join(lines[start:end]));assert len(m)==1;return {'sectionLine':start+1,'complexNamesPath':m[0]}
 test=section('test_dataloader');val=section('val_dataloader');out['embeddedConfigs'].append({'task':task,'sourceReceipt':{'path':str(path),'bytes':size,'sha256':digest},'lines':matches,'testDataloader':test,'validationDataloader':val,'sameConfiguredTestAndValidationDataset':test['complexNamesPath']==val['complexNamesPath']})
path=pathlib.Path('campaign-output/deepternary-embedded-config-metadata.json');path.parent.mkdir(parents=True,exist_ok=True);path.write_text(json.dumps(out,indent=2));print('DEEPTERNARY_CONFIG_METADATA_BEGIN');print(json.dumps(out,separators=(',',':')));print('DEEPTERNARY_CONFIG_METADATA_END')
