suppressPackageStartupMessages({library(minfi);library(conumee);library(GenomicRanges);library(AnnotationDbi);library(org.Hs.eg.db);library(TxDb.Hsapiens.UCSC.hg19.knownGene);library(jsonlite)})
stopifnot(as.character(packageVersion('conumee'))=='1.6.0');set.seed(2601003)
out<-'campaign-output/methylation-emc-MTAP-author-BAF';dir.create(out,recursive=TRUE,showWarnings=FALSE);m<-fromJSON(file.path(out,'source-and-IDAT-manifest.json'),simplifyVector=FALSE);rr<-m$raw_profiles
stopifnot(length(rr)==28,all(vapply(rr,function(r)length(r$channels)==2&&all(vapply(r$channels,function(z)identical(z$status,'acquired'),logical(1))),logical(1))))
writeLines(capture.output(print(minfi::read.metharray)),file.path(out,'minfi-raw-IDAT-loader-source.txt'))
meta<-data.frame(ID=vapply(rr,function(r)r$ID,character(1)),IDAT=vapply(rr,function(r)r$IDAT,character(1)),platform=vapply(rr,function(r)r$geo$platform,character(1)),role=vapply(rr,function(r)r$analysis_role,character(1)),class=vapply(rr,function(r)r$Meth_Class,character(1)),DNA=vapply(rr,function(r)r$DNA,character(1)),stringsAsFactors=FALSE)
stopifnot(sum(meta$role=='EMC_query')==10,sum(meta$role!='EMC_query')==18,!anyDuplicated(meta$IDAT));qc<-list();mat<-list();qd<-list()
for(p in unique(meta$platform)){
 ids<-meta$IDAT[meta$platform==p];rg<-read.metharray(basenames=file.path(out,'uncompressed-idats',ids),extended=TRUE,verbose=TRUE,force=TRUE);colnames(rg)<-ids;dp<-detectionP(rg);snps<-getSnpBeta(rg);stopifnot(identical(colnames(snps),ids));ms<-preprocessIllumina(rg,bg.correct=TRUE,normalize='controls')
 if(p=='GPL21145')annotation(ms)<-c(array='IlluminaHumanMethylationEPIC',annotation='ilm10b2.hg19')
 z<-getMeth(ms)+getUnmeth(ms);stopifnot(identical(colnames(z),ids));mat[[p]]<-z
 for(i in seq_along(ids)){one<-CNV.load(ms[,i,drop=FALSE],as.data.frame(snps[,i,drop=FALSE]),names=ids[i]);stopifnot(ncol(one@intensity)==1,'BAF'%in%names(one@BAFsnps));qd[[ids[i]]]<-one}
 qc[[p]]<-data.frame(IDAT=ids,platform=p,raw_address_rows=nrow(rg),n_detection_probes=nrow(dp),detection_P_above_0.01_fraction=colMeans(dp>0.01,na.rm=TRUE),SNP_BAF_n=nrow(snps),SNP_BAF_missing=colSums(!is.finite(snps)),stringsAsFactors=FALSE);rm(rg,dp,ms,snps);gc()
}
common<-Reduce(intersect,lapply(mat,rownames));stopifnot(length(common)>300000);zz<-do.call(cbind,lapply(mat,function(z)z[common,,drop=FALSE]));zz<-zz[,meta$IDAT,drop=FALSE];stopifnot(all(is.finite(zz)))
d<-CNV.load(as.data.frame(zz),data.frame(),names=colnames(zz));for(id in names(qd))qd[[id]]@intensity<-d@intensity[,id,drop=FALSE]
genes_frozen<-c('MTAP','CDKN2A','CDKN2B');gm<-unique(AnnotationDbi::select(org.Hs.eg.db,keys=genes_frozen,keytype='SYMBOL',columns='ENTREZID')[,c('SYMBOL','ENTREZID')]);stopifnot(nrow(gm)==3,!anyNA(gm$ENTREZID));gr<-GenomicFeatures::genes(TxDb.Hsapiens.UCSC.hg19.knownGene);genegr<-gr[gm$ENTREZID];genegr$name<-gm$SYMBOL;names(genegr)<-gm$SYMBOL;stopifnot(all(as.character(seqnames(genegr))=='chr9'))
data(exclude_regions,package='conumee');a0<-CNV.create_anno(array_type='overlap',exclude_regions=exclude_regions,detail_regions=genegr);unavailable<-a0@probes[!names(a0@probes)%in%common];a<-if(length(unavailable))CNV.create_anno(array_type='overlap',exclude_regions=c(exclude_regions,unavailable),detail_regions=genegr)else a0;stopifnot(all(names(a@probes)%in%common))
qids<-meta$IDAT[meta$role=='EMC_query'];refs<-meta$IDAT[meta$role!='EMC_query'];rows<-list();errors<-list();receipts<-list()
run_one<-function(id,refids,label){
 key<-paste(label,id,sep='__');tryCatch({
  stopifnot(length(refids)>=2,!id%in%refids);x<-CNV.detail(CNV.bin(CNV.fit(qd[[id]],d[refids],a,name=id)));co<-x@fit$coef;effective<-sum(is.finite(co)&names(co)!='(Intercept)');stopifnot(effective>=2)
  x<-CNV.segment(x);saveRDS(x,file.path(out,paste0(key,'__before-baseline.rds')));before<-as.numeric(x@detail$ratio);beforeprobe<-x@fit$ratio;beforeseg<-x@seg$summary;warnings_seen<-character();baseline_error<-NULL
  y<-tryCatch(withCallingHandlers(CNV.adjustbaseline(x,method.baseline.correction='BAF'),warning=function(w){warnings_seen<<-c(warnings_seen,conditionMessage(w))}),error=function(e){baseline_error<<-conditionMessage(e);NULL})
  method<-if(is.null(y))'BAF error'else y@method.baseline.correction;shift<-if(is.null(y))NA_real_ else as.numeric(y@bin$shift);package_value<-if(is.null(y))rep(NA_real_,length(before))else as.numeric(y@detail$ratio)
  invalid<-if(method=='BAF')!is.finite(2^before+1-2^shift)|(2^before+1-2^shift)<=0 else rep(FALSE,length(before));qualified<-package_value;qualified[invalid]<-NA_real_
  dt<-data.frame(IDAT=id,analysis=label,gene=a@detail$name,chr=as.character(seqnames(a@detail)),start_1based=start(a@detail),end_inclusive=end(a@detail),n_probes=as.integer(x@detail$probes),pre_baseline_log2=before,package_post_baseline_log2=package_value,qualified_BAF_log2=if(method=='BAF')qualified else rep(NA_real_,length(before)),package_invalid_correction=invalid,MAD_centered_sensitivity=if(method=='MAD')before-shift else rep(NA_real_,length(before)),baseline_method=method,baseline_shift=shift,reference_intended_n=length(refids),reference_coefficients_n=length(co)-as.integer('(Intercept)'%in%names(co)),reference_finite_coefficients_n=effective,fit_noise=x@fit$noise,SNP_BAF_n=nrow(x@BAFsnps),SNP_BAF_missing=sum(!is.finite(x@BAFsnps$BAF)),stringsAsFactors=FALSE)
  dt$n_probes[is.na(dt$n_probes)]<-0L;for(col in c('pre_baseline_log2','package_post_baseline_log2','qualified_BAF_log2','MAD_centered_sensitivity'))dt[dt$n_probes==0,col]<-NA_real_;rows[[key]]<<-dt
  ov<-findOverlaps(a@detail,a@probes);ix<-subjectHits(ov);postprobe<-if(is.null(y))rep(NA_real_,length(beforeprobe))else y@fit$ratio;badprobe<-if(method=='BAF')!is.finite(2^beforeprobe+1-2^shift)|(2^beforeprobe+1-2^shift)<=0 else rep(FALSE,length(beforeprobe));pp<-data.frame(gene=a@detail$name[queryHits(ov)],probe=names(a@probes)[ix],pre_baseline_log2=as.numeric(beforeprobe[ix]),package_post_baseline_log2=as.numeric(postprobe[ix]),package_invalid_correction=badprobe[ix]);write.table(pp,file.path(out,paste0(key,'__locus-probes.tsv')),sep='\t',quote=FALSE,row.names=FALSE)
  write.table(beforeseg,file.path(out,paste0(key,'__pre-baseline-segments.tsv')),sep='\t',quote=FALSE,row.names=FALSE);if(!is.null(y)){saveRDS(y,file.path(out,paste0(key,'__after-baseline.rds')));write.table(y@seg$summary,file.path(out,paste0(key,'__package-post-baseline-segments.tsv')),sep='\t',quote=FALSE,row.names=FALSE)}
  receipts[[key]]<<-list(IDAT=id,analysis=label,reference_ids=refids,coefficients=setNames(as.list(as.numeric(co)),names(co)),baseline_method=method,baseline_error=baseline_error,warnings=warnings_seen,invalid_locus_n=sum(invalid),invalid_genomewide_probe_n=sum(badprobe),SNP_BAF=x@BAFsnps)
  if(!is.null(baseline_error))errors[[key]]<<-list(IDAT=id,analysis=label,stage='author baseline correction',error=baseline_error);message('COMPLETED_AUTHOR_FORK ',label,' ',id,' ',method)
 },error=function(e){errors[[key]]<<-list(IDAT=id,analysis=label,stage='read/fit/CBS',error=conditionMessage(e));message('SCIENTIFIC_ERROR ',key,': ',conditionMessage(e))})
}
for(id in qids)run_one(id,refs,'author_fork_18_FFPE_controls');for(id in refs)run_one(id,setdiff(refs,id),'author_fork_leave_one_control_out')
locus<-if(length(rows))do.call(rbind,rows)else data.frame();if(nrow(locus))write.table(locus,file.path(out,'author-fork-locus-measurements.tsv'),sep='\t',quote=FALSE,row.names=FALSE);writeLines(capture.output(sessionInfo()),file.path(out,'R-session-info.txt'))
result<-list(schema='emc-ten-author-conumee-BAF-sensitivity/1',status=if(length(errors))'partial; exact author-fork runtime errors retained'else'completed',source_commit='372c3f0342ce8eec3e7eca03c45d5bce2f1d0a3a',expected_fit_n=28,completed_fit_n=length(rows),error_n=length(errors),errors=errors,common_probe_n=length(common),annotation_probe_n=length(a@probes),source_metadata_sha256=m$metadata_sha256,source_primary_xml_sha256=m$primary_xml_sha256,locus_measurements=locus,raw_QC=do.call(rbind,qc),fit_receipts=receipts,method_caveats=c('Publication cites this fork without a historical commit; pinned source-defined sensitivity is not proof of exact published execution','Historical CNV.fit unbraced-if removes highest-correlated reference on every fit; behavior preserved and coefficient counts reported','BAF adds 1-2^baseline in intensity space; invalid results become -1.2 in package; qualified values withheld','Historical MAD fallback leaves ratios unmodified while storing shift; literal and ancillary centered values separated','CBS default alpha .001, permutations50000,minwidth5,undoSD2.2; fork separates chromosome arms','No absolute/biallelic CN, protein, MTA, dependency or drug-response claims','Reference CN neutrality/purity/ploidy unverified; all normal LOO measurements retained'))
write_json(result,file.path(out,'author-BAF-sensitivity-results.json'),pretty=TRUE,auto_unbox=TRUE,na='null',digits=16);cat('EMC_MTAP_AUTHOR_BAF_BEGIN\n');cat(toJSON(result,auto_unbox=TRUE,na='null',digits=16));cat('\nEMC_MTAP_AUTHOR_BAF_END\n');if(length(errors))quit(status=2)
