suppressPackageStartupMessages({library(minfi);library(conumee);library(GenomicRanges);library(AnnotationDbi);library(org.Hs.eg.db);library(TxDb.Hsapiens.UCSC.hg19.knownGene);library(jsonlite)})
stopifnot(as.character(packageVersion('conumee'))=='1.6.0');set.seed(2601002)
out<-'campaign-output/methylation-emc-MTAP';dir.create(out,recursive=TRUE,showWarnings=FALSE);m<-fromJSON(file.path(out,'source-and-IDAT-manifest.json'),simplifyVector=FALSE);rr<-m$raw_profiles
stopifnot(length(rr)==28,all(vapply(rr,function(r)length(r$channels)==2&&all(vapply(r$channels,function(z)identical(z$status,'acquired'),logical(1))),logical(1))))
writeLines(capture.output(print(minfi::read.metharray)),file.path(out,'minfi-raw-IDAT-loader-source.txt'))
meta<-data.frame(ID=vapply(rr,function(r)r$ID,character(1)),IDAT=vapply(rr,function(r)r$IDAT,character(1)),platform=vapply(rr,function(r)r$geo$platform,character(1)),role=vapply(rr,function(r)r$analysis_role,character(1)),class=vapply(rr,function(r)r$Meth_Class,character(1)),DNA=vapply(rr,function(r)r$DNA,character(1)),stringsAsFactors=FALSE)
stopifnot(sum(meta$role=='EMC_query')==10,sum(meta$role!='EMC_query')==18,!anyDuplicated(meta$IDAT));qc<-list();mat<-list()
for(p in unique(meta$platform)){
 ids<-meta$IDAT[meta$platform==p];rg<-read.metharray(basenames=file.path(out,'uncompressed-idats',ids),extended=TRUE,verbose=TRUE,force=TRUE);colnames(rg)<-ids;dp<-detectionP(rg);qs<-data.frame(IDAT=ids,platform=p,raw_address_rows=nrow(rg),n_detection_probes=nrow(dp),detection_missing_fraction=colMeans(!is.finite(dp)),detection_P_above_0.01_fraction=colMeans(dp>0.01,na.rm=TRUE),stringsAsFactors=FALSE);ms<-preprocessIllumina(rg,bg.correct=TRUE,normalize='controls');z<-getMeth(ms)+getUnmeth(ms);stopifnot(identical(colnames(z),ids),!anyDuplicated(rownames(z)));qs$total_intensity_nonpositive_or_missing<-colSums(!is.finite(z)|z<1);qs$total_intensity_mean<-colMeans(z,na.rm=TRUE);qc[[p]]<-qs;mat[[p]]<-z;rm(rg,dp,ms);gc()
}
common<-Reduce(intersect,lapply(mat,rownames));stopifnot(length(common)>300000);zz<-do.call(cbind,lapply(mat,function(z)z[common,,drop=FALSE]));zz<-zz[,meta$IDAT,drop=FALSE];write.table(do.call(rbind,qc),file.path(out,'raw-intensity-and-detection-QC.tsv'),sep='\t',quote=FALSE,row.names=FALSE)
if(any(!is.finite(zz)))stop('Nonfinite intensities; repairsource missingness beforefit')
d<-CNV.load(as.data.frame(zz),names=colnames(zz));genes_frozen<-c('MTAP','CDKN2A','CDKN2B');gm<-AnnotationDbi::select(org.Hs.eg.db,keys=genes_frozen,keytype='SYMBOL',columns='ENTREZID');gm<-unique(gm[,c('SYMBOL','ENTREZID')]);stopifnot(nrow(gm)==3,!anyNA(gm$ENTREZID));gr<-GenomicFeatures::genes(TxDb.Hsapiens.UCSC.hg19.knownGene);genegr<-gr[gm$ENTREZID];genegr$name<-gm$SYMBOL;names(genegr)<-gm$SYMBOL;stopifnot(all(as.character(seqnames(genegr))=='chr9'))
write.table(data.frame(gene=genegr$name,entrez=gm$ENTREZID,genome='hg19',chr=as.character(seqnames(genegr)),start_1based=start(genegr),end_inclusive=end(genegr)),file.path(out,'frozen-locus-genomic-ranges.tsv'),sep='\t',quote=FALSE,row.names=FALSE)
data(exclude_regions,package='conumee');a0<-CNV.create_anno(array_type='overlap',exclude_regions=exclude_regions,detail_regions=genegr);unavailable<-a0@probes[!names(a0@probes)%in%common];a<-if(length(unavailable))CNV.create_anno(array_type='overlap',exclude_regions=c(exclude_regions,unavailable),detail_regions=genegr)else a0;stopifnot(all(names(a@probes)%in%common));annotation_receipt<-list(common_intensity_probe_n=length(common),annotation_probe_n=length(a@probes),excluded_unavailable_probe_n=length(unavailable),excluded_unavailable_probe_ids=names(unavailable),bin_minprobes=15,bin_minsize=50000,array_type='overlap',genome='hg19')
qids<-meta$IDAT[meta$role=='EMC_query'];refs<-meta$IDAT[meta$role!='EMC_query'];allresults<-list();coefrows<-list();errors<-list()
run_one<-function(id,refids,label,segment=FALSE){
 tryCatch({
  stopifnot(length(refids)>=2,!id%in%refids);x<-CNV.detail(CNV.bin(CNV.fit(d[id],d[refids],a,name=id)));effective_n<-max(0,length(x@fit$coef)-as.integer('(Intercept)'%in%names(x@fit$coef)));if(effective_n<2)stop('Fewer than twoeffective normalrefs aftersourcecorrelationfilter')
  reg<-a@detail;dt<-data.frame(IDAT=id,analysis=label,gene=reg$name,chr=as.character(seqnames(reg)),start_1based=start(reg),end_inclusive=end(reg),n_probes=as.integer(x@detail$probes),log2_relative_ratio=as.numeric(x@detail$ratio-x@bin$shift),reference_intended_n=length(refids),reference_effective_n=effective_n,fit_noise=x@fit$noise,centering_shift=x@bin$shift,stringsAsFactors=FALSE);dt$n_probes[is.na(dt$n_probes)]<-0L;dt$log2_relative_ratio[dt$n_probes==0]<-NA_real_;dt$normalized_signal_ratio<-2^dt$log2_relative_ratio;dt$interpretation<-ifelse(dt$n_probes==0,'unmeasured locus','relative array signal; not absolute copies/deletion genotype');allresults[[paste(label,id,sep='__')]]<<-dt;coefrows[[paste(label,id,sep='__')]]<<-data.frame(IDAT=id,analysis=label,literal_coefficient_name=names(x@fit$coef),coefficient=as.numeric(x@fit$coef),stringsAsFactors=FALSE)
  oo<-findOverlaps(reg,a@probes);pp<-data.frame(IDAT=id,analysis=label,gene=reg$name[queryHits(oo)],probe=names(a@probes)[subjectHits(oo)],chr=as.character(seqnames(a@probes))[subjectHits(oo)],start_1based=start(a@probes)[subjectHits(oo)],log2_relative_ratio=as.numeric(x@fit$ratio[subjectHits(oo)]-x@bin$shift),stringsAsFactors=FALSE);write.table(pp,file.path(out,paste0(label,'__',id,'__locus-probes.tsv')),sep='\t',quote=FALSE,row.names=FALSE)
  if(segment){
   x<-CNV.segment(x);seg<-CNV.write(x,what='segments');write.table(seg,file.path(out,paste0(label,'__',id,'__segments.tsv')),sep='\t',quote=FALSE,row.names=FALSE);locusseg<-lapply(seq_along(reg),function(i){h<-seg[seg$chrom==as.character(seqnames(reg))[i]&seg$loc.start<=end(reg)[i]&seg$loc.end>=start(reg)[i],,drop=FALSE];if(nrow(h))h$gene<-reg$name[i];h});locusseg<-do.call(rbind,locusseg);if(!is.null(locusseg))write.table(locusseg,file.path(out,paste0(label,'__',id,'__locus-segment-overlaps.tsv')),sep='\t',quote=FALSE,row.names=FALSE)
   tryCatch({pdf(file.path(out,paste0(label,'__',id,'__chromosome9.pdf')),width=10,height=5);CNV.genomeplot(x,chr='chr9');dev.off()},error=function(e){if(dev.cur()>1)dev.off();message('ploterror: ',conditionMessage(e))})
  }
  write_json(list(locus_rows=dt,coefficients=coefrows[[paste(label,id,sep='__')]],reference_ids=refids),file.path(out,paste0(label,'__',id,'__numeric.json')),pretty=TRUE,auto_unbox=TRUE,na='null');message('COMPLETED ',label,' ',id)
 },error=function(e){errors[[paste(label,id,sep='__')]]<<-list(IDAT=id,analysis=label,reference_ids=refids,error=conditionMessage(e));message('SCIENTIFIC_ERROR ',label,' ',id,': ',conditionMessage(e))})
}
for(id in qids)run_one(id,refs,'primary_18_FFPE_controls',segment=TRUE)
for(id in qids){p<-meta$platform[match(id,meta$IDAT)];r<-meta$IDAT[meta$role!='EMC_query'&meta$platform==p];run_one(id,r,'same_platform_reference_sensitivity')}
for(id in refs)run_one(id,setdiff(refs,id),'leave_one_control_out')
locus<-if(length(allresults))do.call(rbind,allresults)else data.frame();if(nrow(locus))write.table(locus,file.path(out,'all-primary-sensitivity-and-control-locus-measurements.tsv'),sep='\t',quote=FALSE,row.names=FALSE);if(length(coefrows))write.table(do.call(rbind,coefrows),file.path(out,'all-normalization-coefficients.tsv'),sep='\t',quote=FALSE,row.names=FALSE)
packages<-c('conumee','minfi','DNAcopy','IlluminaHumanMethylation450kmanifest','IlluminaHumanMethylation450kanno.ilmn12.hg19','IlluminaHumanMethylationEPICmanifest','IlluminaHumanMethylationEPICanno.ilm10b2.hg19','org.Hs.eg.db','TxDb.Hsapiens.UCSC.hg19.knownGene');versions<-setNames(lapply(packages,function(p)as.character(packageVersion(p))),packages);writeLines(capture.output(sessionInfo()),file.path(out,'R-session-info.txt'))
result<-list(schema='emc-ten-reference-MTAP-relative-array-CN/1',analysis_status=if(length(errors))'partial; scientific errors remain'else'completed',gene_n=3,query_n=10,reference_n=18,expected_fit_n=38,completed_fit_n=length(allresults),error_n=length(errors),errors=errors,source_metadata_sha256=m$metadata_sha256,source_primary_xml_sha256=m$primary_xml_sha256,conumee_source_commit='cc1caffa49143ef06fde5036b434846649542623',package_versions=versions,annotation=annotation_receipt,source_specimen_metadata=meta,all_locus_measurements=locus,raw_QC=do.call(rbind,qc),method=list(preprocessing='Identicalminfi preprocessIllumina background/controlnormalization',copy_number='Pinnedconumee1.6linearreferencefit/bincentering/detailmedians/defaultDNAcopyCBSprimary',default_CBS=list(alpha=0.001,nperm=50000,min_width=5,undo_splits='sdundo',undo_SD=2.2),gene_ranges='org.Hs.eg.db Entrez/TxDbhg19 no guessedcoords'),limitations=c('NormalFFPE muscle/reactivecontrol CNneutralityunverified; all18LOO locusprofiles retained','Crossgeneration sharedprobes primary; sameplatform only6/12controls','Effective referencecount follows sourcecorrelationfilter','Relative log2/exponentiatedsignals notabsolute/biallelicloss/protein/MTA/dependency/drugresponse','Purity/ploidy/FFPE/normalization distortsignals; no purityadjustedgenotypes','No classifier/classlabelsrefit; separatelocusquestion'))
write_json(result,file.path(out,'relative-locus-CN-results.json'),pretty=TRUE,auto_unbox=TRUE,na='null',digits=16);cat('EMC_MTAP_RELATIVE_CN_BEGIN\n');cat(toJSON(result,auto_unbox=TRUE,na='null',digits=16));cat('\nEMC_MTAP_RELATIVE_CN_END\n');if(length(errors))quit(status=2)
