import pathlib,json,hashlib,datetime,shutil,subprocess
D=pathlib.Path(__file__).resolve().parent
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(n,s):(D/n).write_text(s,encoding='utf-8')
write('RESULTS.txt',f'''Clinical FAPI imaging source gate — {now}
DECISION: SHELVE the standalone EMC FAPI-imaging paper at this bounded checkpoint. No new EMC finding demonstrated. This is an eligibility/value failure, not a biological negative and not exhaustive evidence completion. No authenticated EMC clinical FAPI row was found in the sources actually evaluated. Critical subtype supplements and generic diagnoses remain unresolved, preventing an absence claim or manuscript advancement.

The meaningful proposed question was whether verified same-patient, same-lesion FAPI/FDG measurements demonstrate a reproducible EMC imaging contrast advantage or independently verified added lesions. The source plan and conditional 28-day/no-intervening-therapy paired analysis were fixed before any authenticated EMC values. No case met the identity gate; hence no ratios, p-values or EMC estimates were computed. We did not replace EMC with generic sarcoma or conventional chondrosarcoma.

Actual source evaluation:
1. Koerber2021 (doi10.1007/s00259-021-05374-4) Table1/2 diagnoses account for15, with one sarcomaNOS unresolved. Table1 omits the myxofibrosarcoma present in Table2; LPS Table2 spans1high/4low cases. No explicit EMC; no within-cohort FDG comparison. Four cases overlap the earlier Kratochwil report by author statement, crosswalk unavailable.
2. Ferdinandus2022 (doi10.1158/1078-0432.CCR-22-1432) original TS1 enumerates all21 donors,16 sarcomas. No explicit EMC. Case10 CHS is explicitly conventional in the maintext; it is not EMC evidence. Case2 fibrosarcoma and case11 spindle-cell sarcoma remain unconfirmed identities, not silently excluded. Baseline FAPI measurements are retained as source bytes but cannot support EMC conclusions. Nine cases were reported previously; all cycles and lesions remain dependent observations. No therapy inference was attempted.
3. Novruzov2026 (doi10.1186/s41824-026-00295-7) all19 Table1 records evaluated, including every STS1–STS6. All six remain generic STS despite age/sex/treatment fields. The full supplement is only an acquisition protocol. Primary lesions were biopsy-proven and metastases used a composite clinical reference; this does not solve subtype identity or give independently verified EMC lesion measurements. Interim seven-pancreatic-cancer publication overlaps this source.
4. Pabst2025 (doi10.1016/S1470-2045(25)00299-2) full11page article read. It includes28 sarcomas (18STS/10bone); appendixp5 subtype list was not accessible by the ordinary publisher routes. Participant-level data are request-only after review, and outreach is unauthorized. The article explicitly permits co-enrolment in NCT04571086, so independence from the Essen observational reports is not established.
5. Dynamic Wang2021 (doi10.3389/fonc.2021.651005) all6 participant rows are3lung carcinomas and3no-tumor, not an EMC cohort. The same ethics/trial numbers in other Peking studies do not create shared EMC evidence.
6. First Clinical Experience2025 (doi10.3390/diagnostics15020218; local filename experience2024.xml is a retrieval label, not publication year) Table1 accounts for48 patients in12 named carcinoma/epithelial/mucinous-neoplasm categories and no sarcoma category. No EMC-specific measurement eligible on this complete categorical roster.
7. Independent reviewer evaluated Gu2022 all45 individual diagnoses and Zhang2022 all20 in six explicitly named fibroblastic categories; no author-labelled EMC in those inspected rosters. Yang2022 nasal54M chondrosarcoma remains generic, not excluded by location. Liu2026 abstract22patients/10IHC has no individual subtype roster. Bind the final independent receipt before integration.

Main gaps: Kessler47 SupplementalTable1 and Lanzafame200 SupplementalTable3 are not obtained despite original-index/main/PDF attempts; ordinary HTTP403 is an access gap, not negative evidence. Pabst appendix, Kratochwil original subtype roster and later broad clinical reports remain staged in COVERAGE. Generic sarcoma labels cannot establish or refute EMC identity. The unavailable R5 tissue lane was interrupted by a platform content-access restriction; it is separate and has not been taken over or reinterpreted as negative FAP evidence.

Scientific value: original studies already establish broad sarcoma FAPI uptake and some paired-FDG comparisons. Repeating their aggregate results, restating a single image, or producing this coverage audit would not establish new disease knowledge. A worthwhile future analysis needs authenticated EMC scan IDs, paired lesion values and chronology/verification, plus enough independent donors and contrary observations to change imaging selection or lesion verification for EMC researchers. No present empirical conclusion justifies a localization, treatment-efficacy, dosimetry or safety claim.

Reopen only on a concrete public EMC identity-to-scan crosswalk plus suitable measurements (especially the named missing supplements), then evaluate all eligible conditions/overlap and prior publication before executing or amending the preserved pilot. Do not extrapolate absence from failure to locate evidence.
''')
coverage=[
 {'source':'Koerber2021','doi':'10.1007/s00259-021-05374-4','status':'evaluated; one unresolved diagnosis','files':['koerber2021.xml','source-evaluation.json'],'n':15,'gap':'SarcomaNOS1 has no molecular/subtype crosswalk. Table1 missesMFS1; Table2 resolves category count. Four overlap earlier report, IDs unknown.'},
 {'source':'Ferdinandus2022','doi':'10.1158/1078-0432.CCR-22-1432','status':'evaluated all21 original TS1 rows; two generic sarcomas unresolved','files':['ferdinandus2022.xml','ferdinandus2022-ts1.docx','ferdinandus2022-ts2.docx','ferdinandus2022-ts3.docx','ferdinandus2022-ts4.docx','supplement-evaluation.json'],'n':21,'sarcoma_n':16,'gap':'Cases2fibrosarcoma/11spindle unknown; case10 conventionalCHS bymain. NoEMC-label. Nine previously reported, donor overlap withEssen notcrosswalked.'},
 {'source':'Novruzov2026','doi':'10.1186/s41824-026-00295-7','status':'evaluated all19mainclinical rows and entire1page supplement; all6STS subtype pending/unavailable in these releases','files':['novruzov2026.xml','novruzov2026-supp.pdf','source-evaluation.json'],'n':19,'sarcoma_n':6,'ids':['STS-1','STS-2','STS-3','STS-4','STS-5','STS-6'],'gap':'No histologic subtype, molecular identity or EMC values. Interim7PDAC overlap.'},
 {'source':'Pabst2025','doi':'10.1016/S1470-2045(25)00299-2','status':'mainarticle evaluated; originalappendix unavailable through attempted routes; individualdata request-only','files':['pabst2025.pdf','source-evaluation.json'],'n':155,'sarcoma_n':28,'gap':'Appendixp5 gives missing subtype roster; 18STS10bone. Explicit possible co-enrolmentNCT04571086; no independentpool.'},
 {'source':'Kessler2022','doi':'10.2967/jnumed.121.262096','url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC8717183/','status':'primary indexedmain evaluated; supplement unavailable through attempted routes','n':47,'paired_FDG_n':43,'gap':'SupplementalTable1 allentities and Table6 individualregions notobtained. Main42.6%bone/57.4%STS cannot resolveEMC. EarlyPDF403; BioCfile is ERRORpage, notarticle.'},
 {'source':'Lanzafame2024','doi':'10.2967/jnumed.123.267248','url':'https://jnm.snmjournals.org/content/65/6/880','status':'primary indexedmain andmetadata evaluated; supplement unavailable through attempted routes','n':200,'paired_FDG_n':186,'gap':'SupplementalTable3 otherbone/STS exacttypes notobtained. PotentialKessler/Pabstoverlap; noEMC exclusion.'},
 {'source':'Wangdynamic2021','doi':'10.3389/fonc.2021.651005','status':'evaluated all6individualidentity rows; demonstrably unsuitable bylabels','files':['dynamic2021.xml','citation-trail-evaluation.json'],'n':6,'gap':'NoEMC; 3lungCa/3no-tumor. No unrelateddosimetryanalysis.'},
 {'source':'FirstClinicalExperience2025','doi':'10.3390/diagnostics15020218','status':'evaluated all12diagnosis categories accountingfor48; demonstrably unsuitable bypublishedlabels','files':['experience2024.xml','second-order-evaluation.json'],'n':48,'gap':'No sarcoma category. No additionalnumericEMCanalysis appropriate.'},
 {'source':'Gu2022','doi':'10.1007/s00259-022-05700-4','status':'independent evaluation reused; exactDOItoverifyagainstreviewreceipt','n':45,'gap':'All45primaryindividualdiagnoses evaluated byfunctional; noEMCalias. Do not inferzeroEMCexpression.'},
 {'source':'Zhang2022','doi':'10.1016/j.ejrad.2022.110507','status':'independent originalpreprint table evaluated; finaltable unavailable','n':20,'gap':'SFT13,malignantSFT2,desmoid2,DFSP1,MFS1,highgradefibrosarcoma1. GenericFS1 identity remains a limitation to categoricalnoEMC claim.'},
 {'source':'Yang2022nasalCHS','doi':'10.1097/RLU.0000000000004023','pmid':'35025783','status':'independentabstract evaluated; fullpathology unavailable','n':1,'gap':'54M genericchondrosarcoma. Do notexcludeEMCbyanatomiclocation. PotentialinstitutionaloverlapLiu.'},
 {'source':'Liu2026','doi':'10.1093/bjr/tqag106','pmid':'42128000','status':'independentprimaryabstract/metadata evaluated; fullarticle403','n':22,'gap':'No individualhistologies;10IHC cannotbeassumedEMC. NoEMCeligibilityconclusion.'},
 {'source':'Kratochwil2019','doi':'10.2967/jnumed.119.227967','pmid':'30954939','status':'metadata/primarypublication verified; detailedhistology pending after attemptedS3notfound/PMCrecaptcha','n':80,'gap':'Broad28tumortypes include sarcoma; no retrievedsubtypecrosswalk. FourKoerberpatients previouslyreported.'},
 {'source':'ThreeTimePointFAPI46','url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC11927082/','status':'identified primaryclinical source, identityevaluation pending; S3attempt404','gap':'Two genericsarcomas amongbroadercohort; allscanconditions unassessedforEMC. Noabsenceclaim.'},
 {'source':'Hirmas2023','citation':'Fibroblast-activation protein PET and histopathology in a single-center database of324patients and21tumorentities. JNuclMed64:711–716.','status':'staged directprimarycitation; not evaluated','gap':'PotentialEssenoverlap and sarcoma subtypes unknown. Citation only is not evaluation.'},
 {'source':'Hirmas2024','citation':'Diagnostic accuracy of68GaFAPI versus18FFDG PET inpatientswithvariousmalignancies. JNuclMed65:372–378.','status':'staged directprimarycitation; not evaluated','gap':'PotentialEssenoverlap/EMCidentity unresolved.'},
 {'source':'InternationalFAPIInterobserver2023','url':'https://jnm.snmjournals.org/content/64/7/1043','status':'identified primaryclinical source; subtypeevaluation pending','gap':'50patients broadcohort withsarcoma; thisreview hasnotexaminedallhistologies.'},
 {'source':'liverMetastases2026','doi':'10.1007/s44178-026-00295-4','status':'identified freshprimaryclinical source; exactroster pending','gap':'IndexedfigurelabelshaveIDCS/MSFT/pleomorphic/synovial, notcompletecaseevaluation. CannotdeclareEMCabsent.'}
]
# Bind independently authenticated source DOI; metadata only, no new outcome evaluation.
for x in coverage:
 if x['source']=='Gu2022':x['status']='independent primary XML identity evaluation reused; DOI andsourcehash in reviewerreceipt';x['citation']='Head-to-head evaluation of[18F]FDG and[68Ga]Ga-DOTA-FAPI-04PET/CT in recurrentsofttissuesarcoma (2022)'
write('COVERAGE.json',json.dumps({'date_utc':now,'scope':'Bounded clinical FAPI source gate; not exhaustive claim','status':'No claim advanced; every named pending/unavailable item remains blocking','sources':coverage,'separate_interrupted_scope':'R5 tissue FAP worker stopped by platform content-access safety error; not taken over; no biological inference from interruption'},indent=2))
write('COVERAGE.txt','Clinical FAPI coverage at '+now+'\nNo complete-public-EMC-coverage claim. Exact dispositions and retained inputs are in COVERAGE.json.\n\n'+'\n\n'.join(x['source']+' — '+x['status']+'\n'+x['gap'] for x in coverage)+'\n')
write('SEARCH-RECEIPT.txt',f'''Bounded primary discovery record {now}
Initial leads: PMC8717183, JNM65:880. Search/output and actual acquisition routes retained in *fetch-receipts.json and code; query errors preserved rather than interpreted as source absence.
Webqueries actuallyissued thisgate included: "extraskeletal myxoid" FAPI; FAPI "NR4A3"; FAPI "myxoid chondrosarcoma"; exact originalstudy DOI/title plus supplemental/appendix; Kratochwil2019 sarcoma Table; dynamicFAPI DOI10.3389/fonc.2021.651005. No direct authenticated EMC scan emerged from those resultsets. Search results returning unrelatedEMCarticles are not evidence no FAPI case exists.
Primaryidentifiers confirmed via EuropePMC metadata and originalsources. Initial Kratochwil author/title query returned unrelatedlungcase; retained JSON is not the target. Correct DOIquery retained separately. Pabst firstmetadataquery returnedzero, later exactPubMed/DOI/mainPDFauthenticatedsource; zeroquery isnotabsence.
Pabst PDF public authorarticle mirror: https://www.brainlife.org/fulltext/2025/Pabst_KM250804_LancetOncol.pdf . urllib certificate validation failed; Windows curl.exe with ordinary certificate validation (no insecureflag) retrieved thefile, exit0. Bytehash is in source-evaluation.json and pabst-curl-receipt.json. Main PDF has no directappendixURL; originalLancet/ScienceDirectmainroutes403. No guessing private/reviewer routes, nooutreach.
No supportedbrowser used. No blockedR4content or deniedR5tissuesource wasread/retried. OrdinaryHTTP403/404/500 are documented accessoutcomes; independentplatformrestriction belongs to separateR5tissue lane.
''')
p=D/'pabst2025.pdf';write('pabst-curl-receipt.json',json.dumps({'url':'https://www.brainlife.org/fulltext/2025/Pabst_KM250804_LancetOncol.pdf','bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'retrieval':'Windows curl.exe ordinary TLS validation; exit0; after urllibCERTIFICATE_VERIFY_FAILED','receipt_saved_utc':now,'note':'Manual contemporaneous provenance receipt; original curl success recorded in tool output; not an invented HTTPstatus'},indent=2))
print('Reports saved',now,'files',len(list(D.iterdir())),'bytes',sum(p.stat().st_size for p in D.iterdir() if p.is_file()),'free',shutil.disk_usage(D).free)
