from pathlib import Path
import json,hashlib,datetime,xml.etree.ElementTree as E,zipfile,shutil
P=Path(__file__).resolve().parent
R=Path('/workspace/Rare-cancers')
Q=Path('/workspace/emc-r6-single_cell/research/autonomy/fresh-discovery-2026-10-05-round9/rna_processing/intron_retention_gate')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(name,x):(P/name).write_text(json.dumps(x,indent=2)+'\n')
refs=[R/'research/autonomy/fresh-discovery-2026-10-04-round7/fusion_transcripts/brenca-source-evaluation.json',R/'research/autonomy/fresh-discovery-2026-10-04-round7/fusion_transcripts/RESULTS.txt',R/'research/autonomy/fresh-discovery-2026-10-04-round7/fusion_transcripts/COVERAGE.txt',R/'research/autonomy/fresh-discovery-2026-10-04-round2/regulatory/brenca2019.xml.excerpts.txt',R/'research/autonomy/fresh-discovery-2026-10-04-round2/regulatory/filion2009-source-evaluation.json',R/'research/autonomy/fresh-discovery-2026-10-04-round3/mirna_deposition/linked-project-evaluation.json',Q/'PLAN.json',Q/'raw/Brenca2019-primary.xml',Q/'ALL23-CURRENT-IDENTITY-ASSAY-ROSTER.json']
write('REUSED-INPUTS.json',{'scope':'Prior native cohort/condition decisions, prior-art excerpts, deposit metadata and before-values owner plan; no outcome IR values read','bindings':[{'path':str(p),'bytes':p.stat().st_size,'sha256':sha(p)} for p in refs]})
r7=json.loads(refs[0].read_text());root=E.parse(Q/'raw/Brenca2019-primary.xml').getroot()
paras=[' '.join(''.join(x.itertext()).split()) for x in root.findall('.//p')]
methods=[t for t in paras if t.startswith('Tumor sections with >70%')]
method_tail=[t.split('For fresh')[1].split('Over')[0] for t in paras if 'For fresh' in t and 'libraries' in t]
methods.extend('For fresh'+t for t in method_tail)
supp=E.fromstring(zipfile.ZipFile(P/'raw-cache/PATH-249-90-s001.docx').read('word/document.xml'))
ns={'w':'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}
st=[' '.join(''.join(x.itertext()).split()) for x in supp.findall('.//w:p',ns)]
array=[t for t in st if 'TransPlex' in t or ('three' in t.lower() and 'TAF15' in t)]
write('METHODS-AND-CONDITIONS.json',{'primary_sha256':sha(Q/'raw/Brenca2019-primary.xml'),'primary_methods_relevant_paragraph':methods,'library_assignment':{'FFPE_and_cultures':'Brenca2016 GIST PMID26606880 DOI10.1002/path.4677 ref22','fresh_frozen':'Stacchiotti2014 PMID24703573 DOI10.1016/j.ejca.2014.03.013 ref3','actual_capture_or_depletion_recipes':'Not inspected in these referenced papers; not inferred from abstract or generic SRA labels'},'native_roster':r7['specimen_table'],'native_donors':12,'FFPE_conditions':12,'paired_frozen_conditions':{'n':5,'EWSR1':4,'TAF15':1,'not_new_donors':True,'individual_case_map':'not established'},'engineered_conditions':{'n':11,'EWSR1_NR4A3':4,'TAF15_NR4A3':4,'NR4A3':3,'not_native_donors':True,'prior_mapping':'Eight fusion cultures resolved; three NR4A3 plus twelve tumors not individually linked to source case/partner/specimen.'},'supplement_array_relevant_excerpts':array,'array_context':{'n':6,'EWSR1':3,'TAF15':3,'donor_map':'unresolved subset; not six new donors','assay':'Amplified total-RNA Agilent8x60K gene-expression array; unsuitable for native intron-retention measurement'},'confounding_context':'EWSR1 includes two women and five men; TAF15 all five men. Tumor sites differ across small groups. >70% nuclei enrichment does not measure residual tumor/stromal RNA or morphology/growth contributions. None of these alternatives is already demonstrated to cause an IR difference.'})
meta=json.loads((P/'raw-cache/ewsnative-splicing-metadata.json').read_text())['resultList']['result']
jbc=next(x for x in meta if x['id']=='11673470')
rbp=json.loads((P/'raw-cache/endogenous-rbp-metadata.json').read_text())['resultList']['result']
taf=next(x for x in rbp if x.get('id')=='23416048')
write('PRIOR-ART-EVALUATION.json',{'direct_EMC_fusion_splicing':{'pmid':'11673470','doi':jbc['doi'],'title':jbc['title'],'source_level':'Primary abstract only; not full methods/results inspected','relevant_abstract':jbc['abstractText'],'interpretation':'Engineered EWS/NOR1(NR4A3) pre-mRNA splicing/U1C activity is already published. It is not a native EMC partner comparison or mature retained-intron measurement. A general fusion-splicing claim has no novelty; retained native RNA phenotype could be distinct.'},'native_TAF15_U1':{'pmid':'19282884','doi':'10.1038/embor.2009.24','source_level':'Relevant primary XML methods/results inspected','observations':'HeLa chromatin-associated TAF15/U1 complex is distinct from canonical Sm/U1 snRNP. RNA-dependent chromatin association and transcription-related localization were investigated. Authors propose splicing or transcription initiation functions; mature retained introns and EMC are not demonstrated.','limit':'Non-EMC context; provides alternatives/control rationale, not transferable disease mechanism.'},'native_TAF15_targets':{'pmid':'23416048','doi':taf.get('doi'),'source_level':'Primary abstract inspected; ordinary EPMC fullTextXML returned500, retained failure not repeated','observations':'CLIP/RNAseq/TAF15-depletion work in brain/neuronal contexts reports conserved binding and neuronal alternative splicing; not EMC or a native EWS-vsTAF intron-retention result.','limit':'Full methods/results unverified; no rescue or disease inference imported.'},'published_Brenca':{'scope':'Partner-associated expression/pathway/morphology and engineered growth differences; known chimeric isoforms already recorded in R7. None can be repackaged as native non-fusion IR novelty.','Filion2009':'Published native NR4A3 isoforms/protein regulation remain prior art, not evidence of whole-native-transcriptome IR.'},'search_accountability':{'broad_RBP_query_hits_returned':770,'title_filtered_metadata_candidates':136,'tight_EWS_splicing_hits_returned':9,'not_a_claim':'Metadata candidates are not equivalent to full studies reviewed; no literature-exhaustion claim.'}})
write('COVERAGE.json',{'question':'Native non-fusion IR partner difference only; no observed IR values','conditions':[{'source':'Brenca2019','n':12,'unit':'native donors/FFPE profiles','status':'Source eligibility evaluated; numeric IR pending actual donor/partner/specimen run map and appropriate intron assay validation'},{'source':'Brenca2019','n':5,'unit':'paired frozen preparations of existing donors','status':'Relevant reported conditions; individual matching and raw availability unresolved. Similar gene-expression results/data-not-shown are not IR replication'},{'source':'Brenca2019','n':11,'unit':'engineered fibroblast libraries','status':'Separate mechanism/control context; native-comparison unsuitable; retained all, no technical-replicate donor inflation'},{'source':'Brenca2019 supplementary methods','n':6,'unit':'targeted gene-expression array preparations3EWS/3TAF','status':'Source-evaluated; unsuitable IR assay, unresolved subset donor linkage'},{'source':'PRJNA692081','n':23,'unit':'deposited runs','status':'Current official metadata delegated to quantitative owner. Prior generic inverse-rRNA/stranded-totalRNA labels do not map12 native case genotypes or identify5 frozen preparations'},{'source':'Racanelli targeted fusion panel','status':'Reused R7; unsuitable whole-native-RNA IR evidence; missing fusion detection not zero expression'},{'source':'Ohkura2002','status':'Evaluated primary-abstract prior-art engineered splice reporter, not native IR comparator'},{'source':'Native TAF15 studies','status':'Relevant primary/abstract prior-art contexts evaluated, non-EMC; one full source unavailable via current ordinary endpoint'}],'remaining_relevant_public_inputs':'Owner must account for all suitable whole-transcriptome EMC raw contexts and assay geometries before promotion. This focused challenge is not a whole-public-EMC numeric coverage completion. Accessible pending suitable data blocks promotion.'})
write('DECISION.json',{'decision':'Worthwhile bounded source/assay pilot; shelve numerical execution and scientific promotion at current unresolved gate','new_useful_EMC_finding':False,'why_question_remains':'Native non-fusion mature intron retention by partner is distinct from existing gene expression and engineered splicing. This review establishes no IR outcome.','strongest_defeat':'Run-to-authenticated-native-case/partner/specimen linkage and primary library recipes are unresolved; even linked intronic coverage can represent nascent RNA/FFPE/capture rather than mature retained RNA. Published morphology/growth, composition and preparation alternatives remain.','prior_art_value':'EMC EWS/NOR1 splicing activity already published. A new result must show a reproducible native phenotype with useful discrimination and adequate independent EMC support, not a generic splicing claim or selected-gene catalogue.','next_measurement_if_robust':'For pre-specified replicated candidate events, measure both exon-intron and exon-exon boundaries in molecularly authenticated native EMC using orthogonal RT-PCR/targeted sequencing of mature polyadenylated RNA with DNase/no-RT and nuclear/cytoplasmic or nascent-RNA controls. Pair FFPE/frozen preparations and comparable libraries where obtainable. Additional native donors test partner association; only controlled perturbation and rescue could test causal fusion effects.','reopen_conditions':['Exact individual case/partner/specimen/run map and paired-condition accountability','Primary ref22/ref3 assay recipes plus source-calibrated intronic/spliced coverage capable of resolving intended native endpoint','All relevant suitable accessible EMC contexts evaluated with controls and prior-art reassessment','A discriminating result beyond known expression/growth that directs and survives an informative orthogonal next measurement'],'limits':'Partner correlation is not causal splicing, a tumor-cell origin claim or a treatment dependency. A negative gated measurement is not absence of all RNA-processing biology.'})
cache=[{'path':str(p.relative_to(P)),'bytes':p.stat().st_size,'sha256':sha(p)} for p in (P/'raw-cache').rglob('*') if p.is_file()]
prior=sum(p.stat().st_size for p in (P.parent/'source-cache').rglob('*') if p.is_file()) if (P.parent/'source-cache').exists() else None
write('PORTABILITY.json',{'new_ignored_sources':cache,'new_cache_bytes':sum(x['bytes'] for x in cache),'prior_owned_functional_raw_bytes':28470099,'combined_owned_raw_bytes':28470099+sum(x['bytes'] for x in cache),'source_policy':'Full source archives/XML and parsed source derivative text stay ignored; exported relevant rosters/excerpts/receipts/scripts are sufficient to audit source gate, not to reconstitute uninspected graphics or numerical IR. Preserve caches. Main Brenca XML reused read-only from owner; no duplicate download.','regeneration':'python build_review.py requires retained exact inputs from REUSED-INPUTS and cache; fetch_gate.py and retrieval receipts document ordinary public source routes. One failed TAF15 XML route is not repeated.','free_bytes':shutil.disk_usage(P).free,'raw_softcap_bytes':64*1024*1024,'free_floor_bytes':10*1024**3})
(P/'REPORT.txt').write_text('Question: Is native non-fusion intron retention different by EWSR1 versus TAF15 in authentic EMC, in a way that adds useful information beyond published transcription and growth?\n\nApproach: Before IR values, reused the authenticated12-case/5-frozen/11-engineered records, recovered one ordinary public supplement for methods, checked relevant primary library paragraphs and endogenous/splice prior art, and coordinated run metadata with the quantitative owner. No raw sequencing, IR outcomes, selected genes, graphics or restricted content were examined.\n\nFinding: No new useful EMC measurement survived this source/value gate. The question remains distinct, but engineered EWS/NOR1 splicing/U1C activity was already reported in2002. Brenca confirms FFPE/culture preparation asref22 and fresh-frozen asref3; actual referenced recipes and individual raw-case links remain unresolved. All12native donors,5paired conditions,11engineered conditions and the supplementary3+3 gene-array subset are accountable without donor inflation.\n\nStrongest limits: Intronic reads can be nascent RNA, degradation or assay geometry. Partner is associated with small-group morphology/growth, sex/site and possible mixtures; >70%tumor nuclei does not remove RNA composition effects. The independent question is worth a bounded authenticated assay pilot, but numerical execution/promotion is shelved at this gate. A robust result would justify orthogonal matureRNA/splice-boundary and compartment controls; it would not alone establish causal partner splicing or treatment dependency. Suitable relevant public data pending blocks promotion. This is not evidence of absence or an exhausted search.\n')
# Current official source-roster follow-through is a separately frozen receipt.
exports=[p for p in P.iterdir() if p.is_file() and p.name!='MANIFEST.json']
write('MANIFEST.json',{'frozen_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'question':'Independent before-values native non-fusion intron-retention prior-art/value challenge','files':[{'path':p.name,'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(exports)],'raw_cache_in_git':False,'finding':False})
print(json.dumps({'exports':len(exports),'manifest_sha256':sha(P/'MANIFEST.json'),'new_cache_bytes':sum(x['bytes'] for x in cache),'free_bytes':shutil.disk_usage(P).free}))
