#!/usr/bin/env python3
"""Generate the vaccine-path manuscript's tables IN PLACE, from the committed artifacts.

⛔ WHY IN PLACE RATHER THAN IN A COMPANION FILE. An external reviewer reads the PDF. A stratified
table that lives beside the manuscript is invisible to them, and a table typed into the manuscript
is the densest place in a paper for an artifact and its report to diverge. So the manuscript carries
generated BLOCKS between sentinels, this script owns their contents, and `--check` fails the build
when the block and the artifact disagree — one home for the numbers, and it is the JSON.

WHAT THESE TABLES ANSWER, and it is not a stylistic point. Two independent external reviews of this
manuscript (aiXiv 1364 and 1365) asked for the same thing in different words: the pooled coverage
figure hides its own variance, and a reader planning anything needs the per-population spread rather
than one global number. `hla-coverage.py` has computed that spread all along and only the two
extremes ever reached the prose. A third ask — list the 34-allele panel so the analysis can be
reproduced and its choice assessed — is the second block.

⚠ THE REGIONAL TABLE IS THE TEN-ALLELE SCREEN, NOT THE 34. `hla_coverage.py` builds its regional
accumulators from the alleles carrying a strong binder in `fusion-breakpoint-neoantigens.json`,
which is the ten-allele junction screen: three alleles, global 27.4%, and the public-junction column
is HLA-B*15:01 alone at 8.5%. Labelling it as the 34-allele screen's 30.4% would be wrong by one
allele in every cell. The caption says which screen it is.

⚠ THE WILSON INTERVALS IN THE SOURCE ARTIFACT ARE NOT REPRODUCED HERE. §2.3 withdraws them, for a
reason that applies with more force per region than globally. Sample size is reported instead, which
is the thing a reader actually needs to weigh a regional cell.

Usage: vaccine_path_tables.py [--check]
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MS = os.path.join(HERE, "neoantigen", "emc-vaccine-development-path.md")
COVERAGE = os.path.join(HERE, "..", "modalities", "hla-coverage.json")
MATRIX = os.path.join(HERE, "..", "modalities", "epitope-allele-matrix.json")

BEGIN = "<!-- GENERATED by vaccine_path_tables.py ({}) — do not hand-edit -->"
END = "<!-- END GENERATED ({}) -->"


def _pct(x):
    return "—" if x is None else f"{x * 100:.1f}%"


def regional_block():
    cov = json.load(open(COVERAGE))
    regions = cov["regions"]
    g = cov["global"]
    rows = sorted(regions.items(),
                  key=lambda kv: (kv[1].get("coverage_any_strong_binder_allele") is None,
                                  -(kv[1].get("coverage_any_strong_binder_allele") or 0)))
    out = [
        "**Table 1. Predicted class I coverage by UN M49 sub-region, ten-allele screen.** "
        "Coverage is the union carrier frequency of the presenting alleles over Allele Frequency "
        "Net Database records [1], computed within each sub-region rather than pooled. The pooled "
        f"global figures are the last row. *Public junction* is the *EWSR1* exon 7 to *NR4A3* exon "
        f"3 junction, presented on HLA-B\\*15:01 alone; *any junction* pools every in-frame "
        f"junction, presented on {len(g['all_strong_binder_alleles'])} alleles. No confidence "
        "interval is given, for the reason in §2.3; *n* is the largest per-allele sample the "
        "sub-region contributes and is what a reader should weigh a cell against. A dash is an "
        "allele absent from that sub-region's records, not a coverage of zero.",
        "",
        "| Sub-region | Public junction | Any junction | Presenting alleles | *n* |",
        "|---|---|---|---|---|",
    ]
    for name, r in rows:
        alleles = ", ".join("HLA-" + a.replace("*", "\\*")
                            for a in r.get("coverage_all_alleles_used", [])) or "—"
        out.append(f"| {name} | {_pct(r.get('coverage_e7e3_public'))} | "
                   f"{_pct(r.get('coverage_any_strong_binder_allele'))} | {alleles} | "
                   f"{r.get('max_total_individuals', '—')} |")
    galleles = ", ".join("HLA-" + a.replace("HLA-", "").replace("*", "\\*")
                         for a in g["all_strong_binder_alleles"])
    out.append(f"| **Pooled global** | **{_pct(g['coverage_e7e3_public'])}** | "
               f"**{_pct(g['coverage_any_strong_binder_allele'])}** | {galleles} | — |")
    return "\n".join(out)


def panel_block():
    m = json.load(open(MATRIX))
    panel = m["panel"]
    a = [p for p in panel if p.startswith("HLA-A")]
    b = [p for p in panel if p.startswith("HLA-B")]
    fmt = lambda xs: ", ".join(x.replace("*", "\\*") for x in xs)  # noqa: E731
    return (
        f"**Table 2. The {len(panel)}-allele class I panel.** Listed so the coverage scan can be "
        "reproduced and the choice of panel assessed rather than taken on trust. It is a common-"
        "allele HLA-A and HLA-B panel spanning global diversity, and it carries no HLA-C and no "
        "class II allele — so every figure computed on it is a partial coverage of the class I "
        "repertoire, and §2.3's statement that extending the panel can only raise the figures "
        "applies to HLA-C before it applies to anything else.\n\n"
        f"| Locus | Alleles |\n|---|---|\n"
        f"| HLA-A ({len(a)}) | {fmt(a)} |\n"
        f"| HLA-B ({len(b)}) | {fmt(b)} |")


BLOCKS = {"regional-coverage": regional_block, "class-i-panel": panel_block}


def render(text):
    """Replace every generated block in `text`. Missing sentinels are an error, not a no-op."""
    for name, build in BLOCKS.items():
        begin, end = BEGIN.format(name), END.format(name)
        pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
        if not pat.search(text):
            raise SystemExit(f"⛔ the manuscript has no `{name}` block — expected {begin}")
        text = pat.sub(lambda _m: f"{begin}\n\n{build()}\n\n{end}", text, count=1)
    return text


def main(argv):
    with open(MS) as fh:
        current = fh.read()
    wanted = render(current)
    if "--check" in argv:
        if current != wanted:
            print("STALE: a generated table in emc-vaccine-development-path.md no longer matches "
                  "its artifact — rerun vaccine_path_tables.py", file=sys.stderr)
            return 1
        return 0
    with open(MS, "w") as fh:
        fh.write(wanted)
    print(f"wrote {len(BLOCKS)} generated block(s) into {MS}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
