import hashlib,json,pathlib
p=pathlib.Path('C:/Users/mcrae/.codex/worktrees/ipd-empirical-information-20260906/EMC-Research/research/autonomy/ipd-empirical-information-2026-09-06/README.md')
text=p.read_text(encoding='utf-8')
old=text.replace('# Empirical-information development checkpoint','# Outcome-blind empirical-information development checkpoint',1)
old=old.replace('Completed result: all120 development cases returned; the prespecified continuation gate failed. See `result.md`. Eleven reserved source groups remain unopened and no manuscript or further expansion is selected. Metadata/protocol/harness were prepared before empirical outcome access.','Metadata/protocol/harness prepared before empirical outcome access.',1)
old=old.replace('The saved primary metadata and package sources are in the sibling','No empirical analysis is claimed yet. The saved primary metadata and package sources are in the sibling',1)
newpara='The completed command and all four approved protocol/manifest/amendment hashes are in `authorization.json`. `pilot.py --run` also requires `--amendment-sha256` and `--runtime-amendment-sha256`; do not overwrite preserved execution. `runner.R` retains both original package calls with identical released arrays and the documented exact-time interface wrapper. R and package paths point to the existing baseline worktree cache, read-only. Per-case returned rows, warnings/failures and independently checked statistics are retained under `development/`. `summarize.py` computes the frozen descriptive comparisons and gate. `verify_original.py` independently checks the30 original assignments in R, opening only development records.'
oldpara='After coordinator approval, run `pilot.py --run --protocol-sha256 HASH --manifest-sha256 HASH`. `runner.R` preserves the original two package calls and replaces only the previous discrete-time input adapter with direct identical released arrays. R and package paths point to the existing baseline worktree cache, read-only. Per-case commands/logs, returned rows, warnings/failures and independently checked statistics are retained under `development/`. `summarize.py` computes the frozen descriptive comparisons and gate. It reads only those completed development outputs.'
assert newpara in old
old=old.replace(newpara,oldpara,1)
digest=hashlib.sha256(old.encode()).hexdigest()
result={'current_readme_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'reconstructed_pre_final_update_sha256':digest,'expected_independent_audit_sha256':'4d3440567158ab850de22c17465fc908239ef18cbac1080925f6f80e8969be3a','exact_old_hash_recovered':digest=='4d3440567158ab850de22c17465fc908239ef18cbac1080925f6f80e8969be3a','changes':['Title removed Outcome-blind.','Opening paragraph replaced pending empirical status with completed120-case gate-failed status and11reserved groups unopened.','Execution paragraph replaced prospective two-hash command with actual authorization receipt/four-hash invocation, exact-time wrapper and original30-assignment verifier.'],'tracked_files_edited':False,'scientific_outputs_reexecuted':False}
pathlib.Path(__file__).with_name('readme-change-check.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps(result))
