#!/usr/bin/env python3
"""What a LONGER catalytic gap costs and buys at the same NR4A3 fusion-junction seams.

⛔ WHY THIS EXISTS. The screened design space was one geometry: the 16-mer 5-6-5 LNA/DNA/LNA
gapmer. The submission manuscript's own Methods say why that is the weak point rather than a
detail — reported minima for the contiguous DNA run are five to six nucleotides, and for LNA/DNA/LNA
gapmers specifically a six-nucleotide gap gives "noteworthy but incomplete" activity with seven to
ten reported as optimal — and its Limitations concede that "nothing here bounds what a longer
catalytic gap would achieve at the same seams". A six-nucleotide gap was retained because it is the
gap at which a 16-mer admits junction-spanning registers at all. So the most likely reason this
modality fails at a bench is the gap length, and the unexplored design space attacks that directly.

⛔⛔ THE TWO QUANTITIES MOVE IN OPPOSITE DIRECTIONS AND THIS FILE REFUSES TO COMBINE THEM. Lengthening
the gap raises the gap-level margin — junction-unique DNA on the shorter side, the discriminator the
paper ranks by — and it lengthens the whole oligonucleotide, which is more sequence available to
match something else and a smaller share of the duplex that the seam makes unique. A single score
over the two would hide exactly the finding worth reporting, so every readout below is emitted as a
pair and the artifact carries no composite rank.

⭐ AND THE SHARPEST FORM OF THE COST IS ARITHMETIC, NOT A SEARCH RESULT. Inside the catalytic gap,
the junction-unique bases on the shorter side and the bases a WILD-TYPE PARENT pairs on the longer
side are complements: they sum to the gap. ⛔ WITHIN A GEOMETRY THAT MAKES THEM MOVE INVERSELY —
raising the margin LOWERS, by the same nucleotide, the contiguous DNA one wild-type parent pairs at
the design's own seam. What costs is a LONGER GAP, which is the only way to raise the margin past a
geometry's ceiling of half its gap rounded down, and which raises the parent-paired run at every
register — the quantity RNase-H1's own minimum is stated in. That is not a coincidence a better search could
dodge and no screen in this repository was measuring it, because it is a property of the geometry
rather than of the transcriptome.

WHAT THIS IS AND IS NOT
  · It is sequence and duplex arithmetic over committed artifacts, plus whatever transcriptome
    screens are present for each geometry. $0, offline, no network and no credentials.
  · It is NOT a potency, knockdown, delivery, tolerability, safety, therapeutic-window or
    clinical-readiness claim, and computes no such quantity.
  · It is NOT a cleavage measurement. No RNase-H1 assay exists anywhere in this repository. The
    thresholds below are REPORTED MINIMA from the literature this repository has retrieved, applied
    to predicted duplexes; a duplex is necessary for cleavage and is not sufficient.
  · It is NOT a recommendation of a longer gap. It measures a trade and reports both ends.

Output: aso-gap-length-tradeoff.json
"""
from __future__ import annotations

import json
import os
import statistics
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import aso_screen_sets as ass                                            # noqa: E402

REPO = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(HERE, "aso-gap-length-tradeoff.json")
GAP_LENGTH_LIT = os.path.join(REPO, "research", "manuscripts", "aso",
                              "lit-targets-aso-gap-length.json")

#: The geometries compared. The empty suffix is the committed 5-6-5 panel every published number in
#: this lane is derived from; it is the BASELINE and is never regenerated by this module.
#: ⚠ `wing` is 5 throughout on purpose. Varying the wing and the gap at once would confound the two,
#: and the wing is the half the manuscript's thermodynamics already treats as fixed (each parent
#: pairs exactly one five-nucleotide LNA wing). This asks one question: what does the GAP do?
GEOMETRIES = (
    {"suffix": "", "oligo_len": 16, "wing": 5, "role": "baseline — the panel the manuscript reports"},
    {"suffix": "-18mer-5-8-5", "oligo_len": 18, "wing": 5, "role": "longer gap, inside the reported optimum"},
    {"suffix": "-20mer-5-10-5", "oligo_len": 20, "wing": 5, "role": "longer gap, top of the reported optimum"},
)

#: ⛔ REPORTED MINIMA, NOT THRESHOLDS THIS REPOSITORY MEASURED, AND BOTH ENDS ARE CARRIED. The
#: retrieved sources disagree by one nucleotide — five and six — and picking either alone would
#: decide the headline: at five, every 5-10-5 design's parent-side DNA run qualifies; at six, fewer
#: do. So the count is emitted at BOTH and neither is presented as the answer. The verbatim sentences
#: are read from the committed anchor at run time rather than restated here, so this module cannot
#: drift from the evidence it cites (gate 4 discipline: a remembered quotation is the failure mode).
MIN_CONTIGUOUS_DNA_NT = (5, 6)

#: Which anchored quote supports each end. Keyed by (pmid, fragment) so a change to either side of
#: the anchor file fails the build instead of silently re-basing the claim.
_DNA_MIN_ANCHORS = {
    5: ("39126066", "requires a gap size of at least five for cleavage to occur"),
    6: ("41614678", "sufficient to activate RNase H. In general, this is six or more bases"),
}


def _anchor_quotes():
    """The verbatim sentences behind `MIN_CONTIGUOUS_DNA_NT`, read from the committed anchor file.

    RAISES if a fragment is missing. An absent quotation is not a quotation of absence: a threshold
    whose evidence cannot be found must stop this module, not be emitted with the citation dropped.
    """
    with open(GAP_LENGTH_LIT, encoding="utf-8") as fh:
        lit = json.load(fh)
    by_pmid = {r["pmid"]: r for r in lit["records"]}
    out = {}
    for nt, (pmid, fragment) in sorted(_DNA_MIN_ANCHORS.items()):
        rec = by_pmid.get(pmid)
        if rec is None:
            raise RuntimeError(f"lit-targets-aso-gap-length.json holds no PMID {pmid}")
        q = next((q for q in rec["quotes"] if q["fragment"] == fragment), None)
        if q is None:
            raise RuntimeError(f"PMID {pmid} carries no quote fragment {fragment!r} — the threshold "
                               f"of {nt} nt has lost its anchor")
        out[str(nt)] = {"pmid": pmid, "fragment": fragment, "title": rec.get("title"),
                        "full_text_path": rec.get("full_text_path")}
    return out, lit.get("source")


def _read(name):
    p = os.path.join(HERE, name)
    if not os.path.exists(p):
        return None
    with open(p, encoding="utf-8") as fh:
        return json.load(fh)


# ─────────────────────────────────────────────────────────────────────────────────────────────
# Screen discovery — by MEASURED oligo length, never by a filename convention
# ─────────────────────────────────────────────────────────────────────────────────────────────
#: ⭐ THIS IS THE ONE CONSUMER THAT LEGITIMATELY NEEDS MORE THAN ONE GEOMETRY, and it is served
#: `aso_screen_sets.iter_geometries` — one geometry at a time, as a mapping — rather than a pooled
#: list. The distinction is the whole point: this module compares geometries and must never average
#: across them, so it holds one set per geometry and combines them only where it says it is doing
#: so, per readout, in the open. There is no call in `aso_screen_sets` that would have handed it one
#: mixed bag, so "compares geometries" and "pools geometries" are different code rather than one
#: keystroke apart.
def _screen_geometry(screen):
    """The oligo length a committed screen ACTUALLY ran at, measured from its own designs.

    ⛔ MEASURED, BECAUSE THE PROVENANCE FIELD DOES NOT EXIST ON MOST OF THEM. `method.parameters`
    was added to this lane on 2026-08-13 and cannot be backfilled, so every screen committed before
    that date states its database, its program and its threshold and NOT its geometry. The length of
    the oligonucleotide the screen searched is in the file regardless — it is the thing that ran —
    and reading it is the difference between knowing and assuming which panel a count belongs to.

    ⭐ THE MEASUREMENT MOVED TO `aso_screen_sets` (2026-08-14) and this is a thin adapter. It was
    one of five hand-written copies of the same rule; four of them checked only the LENGTH, and a
    screen also states where its gap is. The loader checks both, which matters most in THIS module,
    since a gap window is the quantity it compares.
    """
    try:
        return ass.measure_oligo_len(ass.BLAST_SCREEN, screen)
    except ass.GeometryError:
        return None


def _screen_depth(screen):
    """(recorded ceiling or None, max hits stored on any design) — how deep this screen searched.

    The second is EVIDENCE rather than a parameter: retention was 15 by default, so a screen storing
    more than 15 hits on some design cannot have run at the default. It is the only depth signal the
    pre-2026-08-13 screens carry, and it is what makes a deep re-screen distinguishable from the
    shallow one beside it without trusting a filename.
    """
    params = (screen.get("method") or {}).get("parameters") or {}
    stored = max((len(o.get("offtargets") or []) for o in (screen.get("oligos") or [])), default=0)
    return params.get("blast_hitlist_size"), stored


def _discover(family):
    """{(oligo_len, junction_label): [(filename, artifact)]} over one artifact family.

    ⛔ THE PARTITION IS THE LOADER'S, NOT THIS MODULE'S (2026-08-14). This walked the directory
    itself and measured the length inline — correct, and a second implementation of a rule five
    other modules also needed, which is how one of them ends up with a different one. It now
    iterates `aso_screen_sets.iter_geometries`, which measures the same way AND additionally refuses
    any screen whose stated `gap_region_1based` disagrees with what it holds. A screen graded
    against one window and counted against another is the silent form of the geometry bug, and this
    module — which compares gap windows for a living — is the last place that should be reading one.
    """
    found = {}
    for geom, screens in ass.iter_geometries(family, root=HERE):
        for s in screens:
            label = s.junction_label
            if not label:
                continue
            found.setdefault((geom.oligo_len, label), []).append((s.name, s.artifact))
    return found


def _same_depth_siblings(cands, chosen_art):
    """Screens of the same junction run at a PROVABLY identical depth to the chosen one.

    ⛔ THE TEST IS THE RECORDED PAIR, AND ONLY THE RECORDED PAIR. Pooling a default-ceiling screen
    with a deep one produces a number that describes neither population — the defect 5233cf867
    corrected in the collapse artifact, where a widening glob moved a manuscript-quoted median from
    2.14 to 4.55 with no science behind it. A screen carrying no `parameters` block cannot prove its
    depth, so it never joins a union; for such junctions the union is the single chosen screen and
    nothing changes.
    """
    want = _screen_depth(chosen_art)[0], (chosen_art.get("method") or {}).get(
        "parameters", {}).get("saved_hits_per_design")
    if want[0] is None or want[1] is None:
        return []
    out = []
    for fn, art in cands:
        got = _screen_depth(art)[0], (art.get("method") or {}).get(
            "parameters", {}).get("saved_hits_per_design")
        if got == want:
            out.append((fn, art))
    return out


def _pick_deepest(cands):
    """The deepest screen for one (geometry, junction), with the evidence that says it is deepest.

    ⭐ AND THE SAME-DEPTH SIBLINGS TRAVEL WITH IT, BECAUSE A TRANSPORT FAILURE IS PER DESIGN AND PER
    RUN (2026-08-13). NCBI dropped three of this lane's 96 design queries with "Remote end closed
    connection without response". Re-dispatching did not simply fill them: at TAF15 e11 the re-run
    returned the design that had failed and FAILED a different one that had succeeded, and at FUS e8
    it did the same. Every design the two runs both screened returned identical counts, so the two
    partial results are consistent and each holds what the other lost.
    ⛔ THE FIX IS A UNION AT READ TIME, NOT A MERGED FILE. Editing one screen to carry another's
    record would be a hand-built artifact that no single run produced — the exact thing
    `test_every_committed_screen_predates_the_block_and_none_was_hand_backfilled` exists to catch.
    Both runs stay on disk exactly as CI wrote them, the union is computed here, and every design
    records which file supplied its record.
    ⚠ THE FAILURES LANDING ON DIFFERENT DESIGNS IN DIFFERENT RUNS IS ITSELF THE EVIDENCE that they
    are transport-random rather than a property of a sequence — which is what makes unioning them
    legitimate rather than cherry-picking the friendlier answer.
    """
    def rank(item):
        _, art = item
        ceiling, stored = _screen_depth(art)
        return (ceiling or 0, stored)
    fn, art = max(cands, key=rank)
    ceiling, stored = _screen_depth(art)
    return {
        "screen": fn,
        "blast_hitlist_size_recorded": ceiling,
        "max_hits_stored_on_a_design": stored,
        # ⚠ The two are different kinds of statement and must not render alike. A recorded ceiling is
        # a parameter the run wrote down; a stored-hit count is an inference from the output, and it
        # can only ever prove that retention EXCEEDED a value, never that the search ceiling did.
        "depth_evidence": ("recorded in the artifact's parameters block"
                           if ceiling else
                           f"no parameters block — retention exceeded the default 15 on some design "
                           f"({stored} stored), which a default run cannot produce"
                           if stored > 15 else
                           "no parameters block and no design stores more than the default retention "
                           "of 15, so the depth of this screen is UNKNOWN from the artifact alone"),
        "_n_candidates_seen": len(cands),
        "union_of_same_depth_screens": sorted(f for f, _ in _same_depth_siblings(cands, art)),
    }


def _union_rows(cands, chosen):
    """Per-design records unioned across same-depth screens of one junction, screened records winning.

    A design is taken from the chosen screen where that screen has it; where the chosen screen
    records a transport failure and a same-depth sibling screened it, the sibling's record is used
    and NAMED. A design no run screened stays a failure — the union recovers records, it never
    invents one.
    """
    by_file = dict(cands)
    order = [chosen["screen"]] + [f for f in chosen["union_of_same_depth_screens"]
                                  if f != chosen["screen"]]
    merged = {}
    for fn in order:
        art = by_file.get(fn)
        if art is None:
            continue
        for seq, row in _blast_rows(art).items():
            have = merged.get(seq)
            if have is None or (have.get("status") != "screened" and row.get("status") == "screened"):
                merged[seq] = {**row, "_from_screen": fn}
    return merged


def recount_loci(oligo):
    """Distinct loci and gap-spanning-risk loci, RECOUNTED from the stored hits with today's parser.

    ⭐ PUBLIC, AND IT BECAME PUBLIC BECAUSE A SECOND CONSUMER NEEDED IT AND DID NOT HAVE IT
    (2026-08-16). `research/manuscripts/submission_tables.py` was reading the screens'
    `n_loci_with_a_gap_spanning_hit` straight into Tables 2 and 3's deep columns — the very field
    the block below says must not be read — so Table 2 printed 17 gap-spanning loci for TCF12 e5
    where Table 4 and §3.3 printed 1, for the same molecule at the same depth. The remedy is this
    function, imported; a second implementation of the recount is how the two tables come to
    disagree again with nobody able to say which is right.

    ⛔⛔ THE STORED `n_distinct_loci` AND `n_loci_with_a_gap_spanning_hit` ARE NOT USED, BECAUSE THEY
    WERE COMPUTED AT SCREEN TIME BY A PARSER THAT WAS WRONG (2026-08-13, fixed in 5233cf867).
    `locus_of` took the gene symbol as the last parenthesised token BEFORE THE FIRST COMMA, so every
    gene whose own description contains a comma lost its symbol and fell back to its accession —
    `Homo sapiens germ cell-less 1, spermatogenesis associated (GMCL1), mRNA` split to a head with no
    parenthesis at all, and nine GMCL1 transcript variants were counted as NINE separate loci.
    Measured on this lane's own lead reagent: the 5-6-5 `GGGCATATCATCAAAC` carried
    `n_loci_with_a_gap_spanning_hit: 14`, of which five were real symbols and NINE were GMCL1
    accession fallbacks. Recounted with the fixed parser it is SIX.

    ⚠ THE ERROR IS ONE-DIRECTIONAL: a failed parse can only SPLIT a locus, never merge two, so every
    stored count is an over-count and every correction moves down. That makes the stale field unsafe
    in exactly the way that matters here — an inflated locus count reads as a dirtier reagent than
    the evidence supports, and this artifact compares reagents.

    ⛔ AND IT IS ONLY EXACT WHERE THE HIT LIST IS COMPLETE. The screen computed its counts over ALL
    ranked hits; this recount sees only the stored ones. Where the two agree the recount is exact;
    where the list is truncated it is a LOWER bound over a sample, and the pair is returned with
    `exact: False` rather than quoted as a measurement. Nothing here silently mixes the two.
    """
    from junction_aso_locus_collapse import locus_of  # noqa: PLC0415
    hits = oligo.get("offtargets") or []
    near = oligo.get("n_offtarget_near_matches")
    exact = near is not None and len(hits) == near
    risk = [h for h in hits if str(h.get("risk") or "").startswith("true_cleavage")]
    return {
        "n_distinct_loci": len({locus_of(h) for h in hits}),
        "n_loci_with_a_gap_spanning_hit": len({locus_of(h) for h in risk}),
        "loci_with_a_gap_spanning_hit": sorted({locus_of(h) for h in risk}),
        "exact": exact,
        "_basis": ("recounted from the complete stored hit list with the corrected locus parser"
                   if exact else
                   "LOWER BOUND — recounted over a truncated stored list, so loci beyond it are "
                   "unseen; the screen's own field is not substituted because it was produced by "
                   "the superseded parser and over-counts"),
    }


def _blast_rows(screen):
    """{antisense: per-design counts} from one gap-resolved screen, orientation status carried."""
    sys.path.insert(0, HERE)
    from junction_aso_offtarget import screen_orientation_status  # noqa: PLC0415
    status = screen_orientation_status(screen)
    rows = {}
    for o in screen.get("oligos") or []:
        if o.get("status") != "screened":
            rows[o.get("antisense_5to3")] = {"status": o.get("status"), "error": o.get("error")}
            continue
        near = o.get("n_offtarget_near_matches")
        saved = len(o.get("offtargets") or [])
        loci = recount_loci(o)
        rows[o["antisense_5to3"]] = {
            "status": "screened",
            "n_offtarget_near_matches": near,
            "n_true_cleavage_risk": o.get("n_true_cleavage_risk"),
            "n_minus_strand_not_hybridisable": o.get("n_minus_strand_not_hybridisable"),
            "n_gap_disrupted_no_cleavage": o.get("n_gap_disrupted_no_cleavage"),
            "loci": loci,
            # ⚠ WHAT THE SCREEN ITSELF RECORDED, KEPT BESIDE THE RECOUNT AND NEVER INSTEAD OF IT.
            # Retained so a reader can see the size and direction of the parser correction on this
            # exact design rather than having to take the recount on trust.
            # ⛔ THIS BLOCK ONCE ENDED "it is superseded, and nothing downstream reads it", AND THAT
            # SECOND CLAUSE WAS FALSE WHEN IT WAS WRITTEN (corrected 2026-08-16). The field was
            # superseded here and nowhere else: `research/manuscripts/submission_tables._deep_lookup`
            # read `n_loci_with_a_gap_spanning_hit` straight off the screens into the deep columns of
            # Tables 2 and 3, so 30 of the 187 deep 16-mer records printed the inflated figure —
            # TCF12 e5 / GGGCATATCCATCAGA at 17 where the recount is 1, TCF12 e3 / GGGCATATCTGATCCA
            # at 56 where it is 6, and the lead reagent GGGCATATCATCAAAC at 14 where it is 6, the
            # same three numbers Table 4 and the Results already carried corrected. A note asserting
            # that a superseded field has no readers is a claim about every other module in the
            # repository, which a comment here cannot check and cannot keep true. What replaced it is
            # `research/manuscripts/tests/test_deep_locus_cells_are_the_recount.py`: it holds the two
            # tables' rendered cells against this recount and refuses the one reader that had gone
            # wrong. A new reader elsewhere would still be unguarded — so the honest statement is
            # that this field is superseded, not that nobody reads it.
            "_superseded_locus_counts_from_the_old_parser": {
                "n_distinct_loci": o.get("n_distinct_loci"),
                "n_loci_with_a_gap_spanning_hit": o.get("n_loci_with_a_gap_spanning_hit"),
            },
            # ⚠ RIGHT-CENSORED means the stored list is shorter than the count, so the strand of the
            # remainder is unrecoverable and no later pass can repair it. Named per design because
            # within one screen some designs are censored and some are not.
            "hit_list_complete": (near is not None and saved == near),
            "orientation": status,
        }
    return rows


# ─────────────────────────────────────────────────────────────────────────────────────────────
# The two directions
# ─────────────────────────────────────────────────────────────────────────────────────────────
def design_rows(geom):
    """Every fusion-specific design at this geometry, with both halves of the gap accounted for."""
    atlas = _read(f"nr4a3-fusion-junction-atlas{geom['suffix']}.json")
    if atlas is None:
        return None, None
    gap = geom["oligo_len"] - 2 * geom["wing"]
    pgp = _read(f"aso-parent-gap-pairing{geom['suffix']}.json") or {}
    duplex = {(r["junction"], r["antisense_5to3"]): r for r in pgp.get("per_design", [])}
    thermo = _read(f"junction-aso-thermo{geom['suffix']}.json") or {}
    dg = {(r["junction"], r["antisense_5to3"]): r for r in thermo.get("per_design", [])}
    pre = _read(f"aso-premrna-offtarget{geom['suffix']}.json") or {}
    premrna = {(r.get("junction_label"), r.get("antisense_5to3")): r
               for r in (pre.get("per_design") or [])}

    rows = []
    for panel in atlas["panels"]:
        label = panel["junction_label"]
        for d in panel.get("designs") or []:
            if not d.get("fusion_specific"):
                continue
            k = (label, d["antisense_5to3"])
            gl, gr = d["gap_bases_from_EWSR1"], d["gap_bases_from_NR4A3"]
            if gl + gr != gap:                    # the complement identity IS the finding; check it
                raise RuntimeError(f"{k}: gap halves {gl}+{gr} do not sum to the gap {gap}")
            margin = min(gl, gr)
            parent_dna = max(gl, gr)              # = gap - margin, by the identity just asserted
            t, p = dg.get(k), premrna.get(k)
            rows.append({
                "junction": label,
                "donor": panel["donor_symbol"],
                "antisense_5to3": d["antisense_5to3"],
                "gc_percent": d["gc_percent"],
                "bases_from_donor": d["bases_from_EWSR1"],
                "bases_from_acceptor": d["bases_from_NR4A3"],
                # ── the direction that IMPROVES with a longer gap ──────────────────────────────
                "gap_specificity_margin": margin,
                # ── the direction that WORSENS, and it is the same subtraction ─────────────────
                #: contiguous DNA of the catalytic gap that ONE wild-type parent pairs at this
                #: design's own seam. Guaranteed by construction, not a search result.
                "parent_paired_gap_dna_nt": parent_dna,
                #: that run plus the LNA wing on the same side — the whole contiguous hybrid this
                #: design presents to that wild-type parent.
                "parent_seam_hybrid_bp": parent_dna + geom["wing"],
                "which_parent_pairs_the_longer_side": (
                    panel["donor_symbol"] if gl > gr else "NR4A3" if gr > gl else "both equally"),
                #: The share of the WHOLE duplex the seam makes unique: the oligonucleotide pairs
                #: the fusion over all of it and the best-matching parent over max(donor, acceptor)
                #: of it, so what is left is min(donor, acceptor). ⚠ A CENTRED DESIGN HOLDS THIS AT
                #: 0.5 AT EVERY LENGTH — centring is scale-free — so the erosion a longer oligo
                #: causes is not visible in the best register and shows only in the worst, where the
                #: minimum side is pinned at WING+1 whatever the length. That is why this is
                #: reported as a distribution and never as a per-geometry mean.
                "junction_unique_fraction_of_oligo": round(
                    min(d["bases_from_EWSR1"], d["bases_from_NR4A3"]) / geom["oligo_len"], 4),
                # ── coincidence screens, which a longer gap makes HARDER to trip ───────────────
                "mature_parent_duplex_through_whole_gap_bp":
                    (duplex.get(k) or {}).get("longest_parent_duplex_bp_through_gap"),
                "mature_parent_duplex_gene": (duplex.get(k) or {}).get("parent"),
                # ⚠ THE FIELD IS `n_hybridisable_gap_fully_paired`. A near-miss key name returns
                # None through `.get`, and None reads as "not screened" — so a mis-typed key would
                # have reported the whole pre-mRNA arm as absent at every geometry while the arm had
                # in fact run and answered. Caught by the summary printing None for all three.
                "premrna_hybridisable_gap_paired_sites":
                    (p or {}).get("n_hybridisable_gap_fully_paired") if p else None,
                "premrna_hits_invisible_to_mature_screens":
                    (p or {}).get("n_invisible_to_mature_screens") if p else None,
                # ── duplex thermodynamics ─────────────────────────────────────────────────────
                "dg37_fusion_duplex": (t or {}).get("dg37_fusion_duplex"),
                "dg37_most_stable_parent_duplex": (t or {}).get("dg37_best_parent_duplex"),
                "ddg37_discrimination": (t or {}).get("ddg37_discrimination"),
                "design_rules_passed": (sum((t or {}).get("design_rules", {}).values())
                                        if t else None),
                "also_exact_at_junctions": d.get("also_exact_in_junctions") or [],
            })
    return atlas, rows


#: The seam the one clinically-relevant candidate sits on: the most commonly reported EMC junction
#: (EWSR1 exon 12 :: NR4A3 exon 3), which the 16-mer lead also spans at TAF15 exon 11 and FUS exon 10
#: through ten identical donor bases. Named as a JUNCTION rather than as a sequence, because the
#: sequence is what changes between geometries and the question is what happens at that seam.
LEAD_JUNCTION = "EWSR1_e12__NR4A3_e3"
LEAD_PARTNERS = 3


def lead_reagent(rows_by_geom, atlases):
    """The best-margin design at `LEAD_JUNCTION` that still covers all three FET partners exactly.

    ⛔ DERIVED, NEVER TYPED. Writing the three sequences in as literals would make this block a
    restatement of a result rather than a measurement of one, and the whole point is that the
    sequence a longer gap selects at this seam is not the 16-mer with bases added — the register
    moves. It is chosen by the same two criteria at every geometry: cross-partner coverage first
    (that is what makes this candidate the interesting one), then the gap-level margin.

    ⚠ COVERAGE IS BOUNDED BY THE TRANSCRIPTS, NOT BY THE OLIGONUCLEOTIDE. The three donors are
    identical over ten bases 5' of their breakpoints and diverge at the eleventh, so any design
    drawing more than ten donor bases covers EWSR1 alone whatever its length. That ceiling is read
    from the atlas rather than assumed, and it is why the margin at this seam stops rising at 5.
    """
    out = {}
    for arch, rows in rows_by_geom.items():
        atlas = atlases[arch]
        cover = atlas["isoform_coverage"]["multi_partner_exact"]
        maximal = {len(v.get("maximal_shared_donor_run") or "") for v in cover.values()
                   if len(v.get("partners_covered") or []) >= LEAD_PARTNERS}
        cands = [r for r in rows
                 if r["junction"] == LEAD_JUNCTION
                 and len({lab.split("_e")[0] for lab in
                          [LEAD_JUNCTION] + r["also_exact_at_junctions"]}) >= LEAD_PARTNERS]
        if not cands:
            out[arch] = {"_absent": "no design at this seam covers three partners at this geometry"}
            continue
        best = max(cands, key=lambda r: (r["gap_specificity_margin"], r["antisense_5to3"]))
        out[arch] = {
            **{k: v for k, v in best.items() if k not in ("also_exact_at_junctions",)},
            "also_exact_at_junctions": best["also_exact_at_junctions"],
            "n_partners_covered_exactly": len({lab.split("_e")[0] for lab in
                                               [LEAD_JUNCTION] + best["also_exact_at_junctions"]}),
            "max_gap_margin_available_at_this_seam_under_the_coverage_constraint":
                best["gap_specificity_margin"],
            "maximal_shared_donor_run_nt": max(maximal) if maximal else None,
        }
    return out


def _screened(rows, junctions=None):
    return [r for r in rows
            if (r.get("alignment_screen") or {}).get("status") == "screened"
            and (junctions is None or r["junction"] in junctions)]


def _screen_summary(rows, junctions=None):
    """Alignment-screen counts over a set of designs, with the censoring state named per set."""
    ok = _screened(rows, junctions)
    if not ok:
        return {"n_designs_with_alignment_counts": 0,
                "_absent": "no design in this set carries an alignment count — an absent reading, "
                           "not a reading of absence"}
    near = [r["alignment_screen"]["n_offtarget_near_matches"] for r in ok]
    risk = [r["alignment_screen"]["n_true_cleavage_risk"] for r in ok]
    # ⛔ A DESIGN THE REMOTE SERVICE DROPPED CARRIES NO COUNT, AND ITS ABSENCE MUST BE COUNTED. Every
    # statistic here is over `status == screened` only, so a failed query silently shrinks the
    # denominator — and a shrinking denominator on a screen that keeps returning zeros reads exactly
    # like a cleaner panel. Named per set so a reader can see how much of the set answered.
    scoped = [r for r in rows if junctions is None or r["junction"] in junctions]
    failed = [r["antisense_5to3"] for r in scoped
              if (r.get("alignment_screen") or {}).get("status") not in (None, "screened")]
    risk_loci = [r["alignment_screen"]["loci"]["n_loci_with_a_gap_spanning_hit"] for r in ok]
    old_risk_loci = [r["alignment_screen"]["_superseded_locus_counts_from_the_old_parser"]
                     ["n_loci_with_a_gap_spanning_hit"] for r in ok]
    inflated = sum(1 for new, old in zip(risk_loci, old_risk_loci)
                   if old is not None and old > new)
    return {
        "n_junctions": len({r["junction"] for r in ok}),
        "n_designs_with_alignment_counts": len(ok),
        "n_designs_the_remote_service_dropped": len(failed),
        "designs_with_no_count": sorted(failed),
        "loci_with_a_gap_spanning_hit": _dist(risk_loci),
        "distinct_loci": _dist([r["alignment_screen"]["loci"]["n_distinct_loci"] for r in ok]),
        # ⚠ HOW FAR THE SUPERSEDED PARSER INFLATED THIS SET, stated rather than left implicit. The
        # correction can only move counts DOWN — a failed symbol parse splits a locus, it cannot
        # merge two — so this is the whole size of the change on this population.
        "n_designs_whose_risk_locus_count_the_old_parser_inflated": inflated,
        "n_designs_whose_locus_recount_is_exact": sum(
            1 for r in ok if r["alignment_screen"]["loci"]["exact"]),
        "n_designs_with_an_incomplete_hit_list": sum(
            1 for r in ok if not r["alignment_screen"]["hit_list_complete"]),
        "near_matches": _dist(near),
        "hybridisable_gap_spanning_risks": _dist(risk),
        "n_with_zero_hybridisable_gap_spanning_risk": sum(1 for x in risk if x == 0),
        "n_with_no_near_match_at_all": sum(1 for x in near if x == 0),
        "exhaustive_le1mm": _dist([r.get("exhaustive_le1mm_matches") for r in ok]),
    }


def _matched(rows_by_geom, present):
    """The only like-for-like alignment comparison: the seams EVERY present geometry was screened at.

    ⛔ WITHOUT THIS THE COMPARISON IS OF COVERAGE. The baseline is screened at all 38 junctions and a
    new geometry at whatever a dispatch reached, so a corpus-total contrast would put 190 designs
    against 41 and read as a specificity difference. Restricting to the intersection costs nothing
    and is the difference between a measurement and an artefact of what has been run so far.
    """
    per_arch = {}
    for g in present:
        arch = g["architecture"]
        per_arch[arch] = {r["junction"] for r in _screened(rows_by_geom[arch])}
    shared = set.intersection(*per_arch.values()) if per_arch else set()
    return {
        "_junctions": sorted(shared),
        "n_junctions": len(shared),
        "_absent": None if shared else (
            "no junction has an alignment screen at every present geometry, so no like-for-like "
            "comparison can be made yet"),
        "by_geometry": {arch: _screen_summary(rows_by_geom[arch], shared) for arch in per_arch}
        if shared else {},
    }


def _dist(values):
    v = [x for x in values if x is not None]
    if not v:
        return None
    return {"n": len(v), "min": min(v), "median": round(statistics.median(v), 3), "max": max(v)}


def _counter(values):
    out = {}
    for x in values:
        out[str(x)] = out.get(str(x), 0) + 1
    return dict(sorted(out.items(), key=lambda kv: int(kv[0])))


def build():
    anchors, anchor_source = _anchor_quotes()
    sys.path.insert(0, HERE)
    from aso_parent_gap_pairing import MIN_DUPLEX_BP  # noqa: PLC0415 — one home for the threshold

    blast = _discover(ass.BLAST_SCREEN)
    exhaustive = _discover(ass.DESIGN_EVALUATION)

    geoms, per_design, screens = [], [], {}
    rows_by_geom, atlases = {}, {}
    for g in GEOMETRIES:
        atlas, rows = design_rows(g)
        if atlas is None:
            geoms.append({**g, "present": False,
                          "_why": f"nr4a3-fusion-junction-atlas{g['suffix']}.json is not in this "
                                  "checkout, so this geometry contributes nothing — an absent "
                                  "reading, not a reading of absence"})
            continue
        gap = g["oligo_len"] - 2 * g["wing"]
        arch = f"{g['wing']}-{gap}-{g['wing']}"
        for r in rows:
            r["architecture"] = arch
            r["oligo_len"] = g["oligo_len"]
        per_design.extend(rows)
        rows_by_geom[arch], atlases[arch] = rows, atlas

        margins = [r["gap_specificity_margin"] for r in rows]
        pdna = [r["parent_paired_gap_dna_nt"] for r in rows]
        dup = [r["mature_parent_duplex_through_whole_gap_bp"] for r in rows
               if r["mature_parent_duplex_through_whole_gap_bp"] is not None]
        pre = [r["premrna_hybridisable_gap_paired_sites"] for r in rows
               if r["premrna_hybridisable_gap_paired_sites"] is not None]

        # which screens answered for this geometry, and which did not
        junctions = sorted({r["junction"] for r in rows})
        sc = {}
        for label in junctions:
            b = blast.get((g["oligo_len"], label))
            e = exhaustive.get((g["oligo_len"], label))
            chosen = _pick_deepest(b) if b else None
            scan = (max(e, key=lambda it: len(it[1].get("top_designs") or [])) if e else None)
            sc[label] = {
                "gap_resolved_alignment": chosen,
                "exhaustive_le1mm_transcript_scan": ({"artifact": scan[0]} if scan else None),
            }
            # attach the per-design counts to the rows of this junction
            by_seq = _union_rows(b, chosen) if chosen else {}
            le1 = {d["antisense_5to3"]: d for d in (scan[1].get("top_designs") or [])} if scan else {}
            for r in rows:
                if r["junction"] != label:
                    continue
                hit = by_seq.get(r["antisense_5to3"])
                r["alignment_screen"] = hit
                r["alignment_screen_artifact"] = chosen["screen"] if chosen else None
                s = le1.get(r["antisense_5to3"])
                r["exhaustive_le1mm_matches"] = (s or {}).get("offtarget_le1mm")
                r["exhaustive_exact_matches"] = (s or {}).get("offtarget_exact")
        screens[arch] = sc

        geoms.append({
            **g, "present": True, "architecture": arch, "gap_nt": gap,
            "junction_spanning_registers_per_seam": gap - 1,
            "n_junctions": len(junctions),
            "n_fusion_specific_designs": len(rows),
            "n_designs_perfectly_complementing_a_parent": 0,
            "atlas": f"nr4a3-fusion-junction-atlas{g['suffix']}.json",
            "gap_margin_distribution": _counter(margins),
            "parent_paired_gap_dna_distribution": _counter(pdna),
            "n_reaching_reported_dna_minimum": {
                str(nt): sum(1 for x in pdna if x >= nt) for nt in MIN_CONTIGUOUS_DNA_NT},
            "n_whose_seam_hybrid_reaches_min_duplex_bp": sum(
                1 for r in rows if r["parent_seam_hybrid_bp"] >= MIN_DUPLEX_BP),
            "mature_parent_whole_gap_duplex": {
                "n_with_any_gap_pairing_window": sum(1 for x in dup if x > 0),
                "n_at_or_above_min_duplex_bp": sum(1 for x in dup if x >= MIN_DUPLEX_BP),
                "longest_run_distribution": _counter(dup),
                "_threshold_note": (
                    "MIN_DUPLEX_BP is an ABSOLUTE hybrid length and does not scale with the gap, so "
                    "these two counts converge as the gap grows: at a gap of 10 the catalytic gap "
                    "alone is already a 10 bp hybrid and every gap-pairing window clears the "
                    "threshold by construction. Read the first count for how often a parent can "
                    "pair the whole gap at all, and the second for how often that duplex is long "
                    "enough to be a plausible substrate."),
            },
            "premrna_hybridisable_gap_paired": {
                "n_designs_with_at_least_one": sum(1 for x in pre if x),
                "n_designs_screened": len(pre),
            } if pre else None,
            "dg37_fusion_duplex": _dist([r["dg37_fusion_duplex"] for r in rows]),
            "dg37_most_stable_parent_duplex": _dist([r["dg37_most_stable_parent_duplex"]
                                                     for r in rows]),
            "ddg37_discrimination": _dist([r["ddg37_discrimination"] for r in rows]),
            "n_designs_passing_all_four_conventional_rules": sum(
                1 for r in rows if r["design_rules_passed"] == 4),
        })

    present = [g for g in geoms if g.get("present")]
    return {
        "_title": "Gap length versus junction specificity for NR4A3 fusion-junction gapmers: "
                  "5-6-5, 5-8-5 and 5-10-5 at the same seams",
        "_generated_by": "research/modalities/aso_gap_length_tradeoff.py",
        "_cost": "$0 — CPU only, offline over committed artifacts. No network, no credentials, no "
                 "GPU and no rental.",
        "_what": ("What a longer RNase-H1 catalytic gap costs and buys, measured at the SAME "
                  "frame-compatible junctions the 16-mer panel was screened at, on the same "
                  "instruments, with the two directions of the trade kept apart."),
        "_why": ("The screened design space was 5-6-5 only, at a gap length the manuscript's own "
                 "Methods place at the short end of the usable range and below the reported "
                 "optimum, retained because it is what admits junction-spanning registers in a "
                 "16-mer. The manuscript concedes that nothing in it bounds what a longer gap would "
                 "achieve at the same seams. This is that bound."),
        "_what_this_is_not": [
            "Not a cleavage measurement. No RNase-H1 assay exists in this repository. Every "
            "threshold here is a REPORTED MINIMUM from retrieved literature applied to a predicted "
            "duplex, and a duplex is necessary for cleavage without being sufficient.",
            "Not a potency, knockdown, delivery, tolerability, safety, therapeutic-window or "
            "clinical-readiness claim. No such quantity is computed anywhere in this file.",
            "Not a recommendation of a longer gap, and not of a shorter one. It measures a trade in "
            "which one quantity improves and another worsens, and reports both.",
            "Not a claim about which junctions patients carry. The seams here are frame-compatible, "
            "which is an arithmetic property of exon structure; breakpoint recurrence is a clinical "
            "observation and is not decided here.",
            "Not a like-for-like transcriptome comparison unless the screens say so. The alignment "
            "arm admits a fixed TWO mismatches at every length, which is a looser FRACTIONAL "
            "threshold at 16 (14/16) than at 20 (18/20), so a lower near-match count at the longer "
            "geometry is partly that threshold and not only the sequence. The exhaustive arm is "
            "fixed at <=1 mismatch and carries the same asymmetry.",
        ],
        "thresholds": {
            "min_contiguous_dna_nt_for_rnaseh1": {
                "values": list(MIN_CONTIGUOUS_DNA_NT),
                "_why_two": ("The retrieved sources disagree by one nucleotide and the choice would "
                             "decide the headline, so both are carried and neither is presented as "
                             "the answer."),
                "anchors": anchors,
                "anchor_file": os.path.relpath(GAP_LENGTH_LIT, REPO),
                "anchor_source": anchor_source,
            },
            "min_duplex_bp_for_hybrid_binding_domain": {
                "value": MIN_DUPLEX_BP,
                "_home": "aso_parent_gap_pairing.MIN_DUPLEX_BP — imported, never re-typed",
            },
        },
        "geometries": geoms,
        "the_trade": {
            "_the_identity": (
                "Inside the catalytic gap the junction-unique bases on the shorter side and the "
                "bases one wild-type parent pairs on the longer side are COMPLEMENTS: they sum to "
                "the gap, which this module asserts per design rather than assuming. ⛔ THEY "
                "THEREFORE MOVE INVERSELY WITHIN A GEOMETRY, NOT TOGETHER: at a fixed gap each "
                "nucleotide of gap-level margin is one FEWER nucleotide of contiguous "
                "parent-paired DNA, and a design centred on its seam has them equal. What the "
                "identity forbids is raising the margin past the geometry's ceiling of half its "
                "gap, rounded down; that takes a longer gap, and a longer gap raises the "
                "parent-paired run at every register. ⚠ Superseded, retained (round 5, 2026-08-15): "
                "'the gap-level margin and the contiguous parent-paired DNA rise together, "
                "nucleotide for nucleotide' — true across geometries, backwards within one, and "
                "contradicted by this module's own `parent_dna = max(gl, gr)  # = gap - margin`."),
            "improves_with_a_longer_gap": {
                "best_available_gap_margin": {g["architecture"]: max(int(k) for k in
                                                                     g["gap_margin_distribution"])
                                              for g in present},
                "designs_per_seam": {g["architecture"]: g["junction_spanning_registers_per_seam"]
                                     for g in present},
                "mature_parent_can_pair_the_whole_gap": {
                    g["architecture"]:
                        f"{g['mature_parent_whole_gap_duplex']['n_with_any_gap_pairing_window']} of "
                        f"{g['n_fusion_specific_designs']}" for g in present},
                "_why": ("A wild-type parent must match the whole gap to be a cleavable off-target "
                         "there, so a longer gap is a longer coincidence to require."),
            },
            "worsens_with_a_longer_gap": {
                "contiguous_parent_paired_dna_at_the_design_s_own_seam": {
                    g["architecture"]: g["parent_paired_gap_dna_distribution"] for g in present},
                "n_reaching_the_reported_dna_minimum": {
                    g["architecture"]: g["n_reaching_reported_dna_minimum"] for g in present},
                "n_whose_seam_hybrid_reaches_min_duplex_bp": {
                    g["architecture"]:
                        f"{g['n_whose_seam_hybrid_reaches_min_duplex_bp']} of "
                        f"{g['n_fusion_specific_designs']}" for g in present},
                "most_stable_wild_type_parent_duplex_dg37": {
                    g["architecture"]: g["dg37_most_stable_parent_duplex"] for g in present},
                "junction_unique_fraction_of_the_whole_duplex": {
                    "_what": ("min(donor, acceptor) / length — the share of the duplex no single "
                              "wild-type parent pairs. The quantity a longer oligonucleotide is "
                              "expected to erode, and it erodes only at the edges of the register "
                              "set: a CENTRED design sits at 0.5 whatever the length, while the "
                              "most off-centre register is pinned at (wing + 1) / length and so "
                              "falls from 6/16 to 6/20 as the oligonucleotide grows."),
                    "per_geometry": {g["architecture"]: _dist(
                        [r["junction_unique_fraction_of_oligo"] for r in rows_by_geom[
                            g["architecture"]]]) for g in present},
                },
                "_why": ("A junction-spanning design gives each parent a contiguous run of its own "
                         "sequence: one LNA wing plus that parent's share of the gap. Lengthening "
                         "the gap lengthens that share. The parent duplex therefore becomes both "
                         "longer and more stable, and the DNA inside it approaches the run RNase-H1 "
                         "needs — so the enzyme is being made more competent against the fusion and "
                         "against the wild-type transcript at the same time."),
            },
            "_never_collapse_these": (
                "No composite score is emitted and none should be derived. A rank that mixes them "
                "would move with whichever end the weighting favours, and the finding is that they "
                "point in opposite directions."),
            "transcriptome_coincidence_falls_but_it_MUST": {
                "_the_bound": (
                    "⛔ At a FIXED ABSOLUTE mismatch budget a longer probe is necessarily at least "
                    "as specific, and this is arithmetic rather than a result. Both arms hold the "
                    "budget fixed — the alignment screen at two mismatches (>=14/16, >=16/18, "
                    ">=18/20) and the exhaustive scan at one — so if an 18-mer matches a locus "
                    "within the budget then every 16-mer window inside it matches within the same "
                    "budget. The set of loci a longer design can hit is therefore a SUBSET of the "
                    "set its own centre can hit. A falling near-match count is what the instrument "
                    "guarantees; only the SIZE of the fall, and which designs reach zero, are "
                    "measurements."),
                "_and_the_threshold_is_fractionally_stricter_too": (
                    "Two mismatches is 12.5 % of a 16-mer and 10.0 % of a 20-mer, so the longer "
                    "geometry is also being asked a slightly stricter question. Both effects push "
                    "the same way, which is why no cleanliness claim here rests on the counts alone."),
                "_and_the_denominators_differ": (
                    "⛔ THE GEOMETRIES ARE NOT SCREENED AT THE SAME NUMBER OF JUNCTIONS. The 5-6-5 "
                    "panel is screened at all 38; a longer geometry is screened only where a "
                    "dispatch has run. Comparing corpus totals across them would be comparing "
                    "coverage, not specificity — so `matched_junctions` below restricts every "
                    "geometry to the seams ALL of them were screened at, and the per-geometry "
                    "block is reported for completeness rather than for comparison."),
                "per_geometry_NOT_COMPARABLE_different_denominators": {
                    g["architecture"]: _screen_summary(rows_by_geom[g["architecture"]])
                    for g in present},
                "matched_junctions": _matched(rows_by_geom, present),
            },
            "_and_ddg_is_not_selectivity": (
                "The fusion-versus-parent ΔΔG widens with length, because the fusion duplex gains "
                "from the whole added window while each parent gains only from its own side. That "
                "is not a selectivity gain in the sense that matters: what decides whether a "
                "wild-type transcript is cleaved is whether ITS duplex forms and is a substrate, "
                "not whether it is weaker than the fusion's. The absolute parent ΔG is the "
                "decision-relevant column and it moves the wrong way."),
        },
        "not_measured_at_the_longer_geometries": {
            "_why_this_block_exists": (
                "A compartment that was screened at 5-6-5 and not at 5-8-5 or 5-10-5 must be "
                "visible as UNSCREENED. A missing arm and a clean arm are the same shape in a "
                "summary table, and the missing one is the flattering one."),
            "exhaustive_grch38_genome_scan": {
                "state": "UNAVAILABLE BY CONSTRUCTION at 18 and 20 nt, not merely unrun",
                "why": ("aso_genome_offtarget is a complete 2-bit-packed bitmap over the whole "
                        "4**16 code space of a 16-mer. At 20 nt that bitmap is 4**20/8 bytes and the "
                        "rolling code no longer fits the uint32 the kernel is verified over, so the "
                        "module refuses by name rather than degrading. A longer window needs a "
                        "different data structure, which is a build and not a parameter."),
                "what_can_still_be_said_without_it": (
                    "A BOUND, not a measurement, and it is not computed here: at a fixed absolute "
                    "mismatch budget every genomic site a longer design can hit is also hit by each "
                    "of its own 16-mer sub-windows, so the longer design's genome liability cannot "
                    "exceed what the existing 16-mer machinery would report for any sub-window. "
                    "Nobody has run that, so it is stated as an available next step and not as a "
                    "result."),
            },
            "wet_lab": ("Everything. No RNase-H1 cleavage, no knockdown, no parental sparing, no "
                        "delivery and no tolerability has been measured for any sequence at any "
                        "geometry, here or anywhere in this repository."),
            "lna_parameters": ("No LNA nearest-neighbour parameters exist in this lane, so every ΔG "
                               "here is the duplex the DNA backbone would form. The wing is five "
                               "nucleotides at every geometry compared, so LNA affinity enters each "
                               "parent duplex identically and cannot explain a difference between "
                               "them — but the absolute values are not the modified molecule's."),
        },
        "lead_reagent_at_the_most_commonly_reported_seam": {
            "_junction": LEAD_JUNCTION,
            "_why_this_one": (
                "EWSR1 exon 12 joined to NR4A3 exon 3 is the junction reported most often in EMC, "
                "and the 16-mer this panel ranks first at that seam also spans the TAF15 exon 11 "
                "and FUS exon 10 seams exactly. It is the one candidate in the panel with a "
                "clinical readership, so whether a longer gap leaves it cleaner or dirtier is the "
                "single most decision-relevant row here."),
            "_what_is_NOT_claimed": (
                "Not that one reagent serves three patient groups. The published exon-resolved "
                "TAF15::NR4A3 breakpoints are exon 6, not exon 11, and no exon-resolved FUS::NR4A3 "
                "breakpoint has been published at all — so the three-partner property is a "
                "statement about FET-family sequence architecture at seams that may not occur."),
            "by_geometry": lead_reagent(rows_by_geom, atlases),
        },
        "screens_per_geometry": screens,
        "n_designs": len(per_design),
        "per_design": sorted(per_design, key=lambda r: (r["oligo_len"], r["junction"],
                                                        -r["gap_specificity_margin"],
                                                        r["antisense_5to3"])),
    }


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    art = build()
    new = json.dumps(art, indent=1, sort_keys=False) + "\n"
    if "--check" in argv:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur != new:
            print("aso-gap-length-tradeoff.json is stale; re-run without --check", file=sys.stderr)
            return 1
        print("gap-length trade-off artifact is current")
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(new)
    print(f"wrote {os.path.basename(OUT)}", file=sys.stderr)
    for g in art["geometries"]:
        if not g.get("present"):
            print(f"  {g['suffix'] or '(baseline)':<16} ABSENT — {g['_why']}", file=sys.stderr)
            continue
        print(f"  {g['architecture']:<8} {g['n_fusion_specific_designs']:>4} designs · "
              f"margin {g['gap_margin_distribution']} · "
              f"parent-paired DNA {g['parent_paired_gap_dna_distribution']} · "
              f"parent duplex ΔG median "
              f"{(g['dg37_most_stable_parent_duplex'] or {}).get('median')}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
