#!/usr/bin/env python3
"""
Where each of the four Stage 0 vaccine items actually landed, and whether the manuscript states the
figure the artifact produced.

⛔ WHY THIS EXISTS. Ledger row AUT-077 reads "Run the Stage 0 items: proteome-wide novelty, class II
regeneration, anchor-position analysis, extended allele panel", state `queued`, `attempts: 0`. All
four had already been run. A queued row over finished work is this repository's most expensive
recurring defect, because the next session takes the row and pays for the work twice. This module is
the evidence that closes the row, and it is built so a reader can check it rather than trust it.

★ THE BINDING CHECK IS THE POINT, NOT THE INVENTORY. For each item the module derives the headline
figure FROM THE ARTIFACT and then searches the manuscript for that derived string. An item counts as
landed only when the artifact exists AND the manuscript states its figure. A figure present in an
artifact but absent from the manuscript is a different situation from a finished item — the work ran
and nothing reads it — and this separates the two rather than reporting both as done.

⛔ WHAT THIS IS NOT. Not a scientific result and not a quality judgement. It says an analysis ran and
that a document states its number. It says nothing about whether the analysis was the right one,
whether its result is strong, or whether any peptide is presented, immunogenic or safe. Every
underlying figure is a binding PREDICTION or a sequence search.

Inputs:  the committed artifacts named per item, plus emc-vaccine-development-path.md
Output:  stage0-vaccine-item-provenance.json
Cost:    $0 — reads committed files and, where available, read-only `git log`. No network, no GPU.
"""

import json
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
MANUSCRIPT = os.path.join(
    REPO, "research", "manuscripts", "neoantigen", "emc-vaccine-development-path.md")
OUT = os.path.join(HERE, "stage0-vaccine-item-provenance.json")


def read_json(name):
    path = os.path.join(HERE, name)
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def first_commit(relpath):
    """The date the artifact entered the repository, or None if git cannot answer.

    Read-only. A missing answer is recorded as None rather than guessed.
    """
    try:
        out = subprocess.run(
            ["git", "log", "--diff-filter=A", "--format=%ad", "--date=short", "--", relpath],
            cwd=REPO, capture_output=True, text=True, timeout=30, check=False)
        lines = [ln for ln in out.stdout.splitlines() if ln.strip()]
        return lines[-1] if lines else None
    except Exception:
        return None


def last_change(relpath):
    """The most recent commit touching the artifact, with its subject.

    ⛔ NOT THE SAME AS `entered_repo`, AND CONFLATING THEM MISDATES THE WORK. Several of these files
    were created weeks before the analysis this module is about and were REGENERATED by it. The
    creation date understates when the result landed; the last-change date is when the committed
    numbers last moved.
    """
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%ad|%s", "--date=short", "--", relpath],
            cwd=REPO, capture_output=True, text=True, timeout=30, check=False)
        line = out.stdout.strip()
        if not line or "|" not in line:
            return None
        date, subject = line.split("|", 1)
        return {"date": date, "subject": subject}
    except Exception:
        return None


def probe(manuscript_lines, needle):
    hits = [i + 1 for i, ln in enumerate(manuscript_lines) if needle in ln]
    return {"needle": needle, "found": bool(hits), "manuscript_lines": hits}


def main():
    novelty = read_json("junction-proteome-novelty.json")
    cd4 = read_json("patient-cd4-demo.json")
    selfsim = read_json("junction-selfsimilarity.json")
    coverage = read_json("hla-coverage.json")
    curve = read_json("coverage-threshold-curve.json")

    with open(MANUSCRIPT, encoding="utf-8") as fh:
        man_lines = fh.read().splitlines()

    items = []

    # ---- 1. proteome-wide novelty -------------------------------------------------------------
    if novelty:
        n_novel, n_tested = novelty["n_novel_proteome_wide"], novelty["n_peptides_tested"]
        items.append({
            "aut077_phrase": "proteome-wide novelty",
            "artifact": "junction-proteome-novelty.json",
            "script": "junction_proteome_novelty.py",
            "entered_repo": first_commit("research/modalities/junction-proteome-novelty.json"),
            "last_change": last_change("research/modalities/junction-proteome-novelty.json"),
            "headline_derived_from_the_artifact": {
                "n_peptides_tested": n_tested,
                "n_novel_proteome_wide": n_novel,
                "n_found_in_proteome": novelty["n_found_in_proteome"],
                "n_predicted_binders_found_in_proteome":
                    novelty["n_predicted_binders_found_in_proteome"],
                "proteome": (novelty.get("_proteome") or {}).get("proteome_id"),
                "n_sequences_searched": (novelty.get("_proteome") or {}).get("n_sequences"),
            },
            "manuscript_probes": [probe(man_lines, f"{n_novel} of {n_tested}")],
            "instrument_limit": "exact-substring absence from the reviewed human proteome. It "
                                "bounds sequence identity and says nothing about a near neighbour, "
                                "about processing, about presentation or about immunogenicity.",
        })

    # ---- 2. class II regeneration --------------------------------------------------------------
    if cd4:
        strong = [p for p in cd4["all_predictions"] if p.get("call") == "strong"]
        items.append({
            "aut077_phrase": "class II regeneration",
            "artifact": "patient-cd4-demo.json",
            "script": "patient_cd4_epitopes.py",
            "entered_repo": first_commit("research/modalities/patient-cd4-demo.json"),
            "last_change": last_change("research/modalities/patient-cd4-demo.json"),
            "headline_derived_from_the_artifact": {
                "n_alleles_screened": cd4["n_alleles_screened"],
                "n_predicted_binders": cd4["n_predicted_binders"],
                "n_strong": cd4["n_strong"],
                "strong_calls": [{"peptide": s["peptide"], "allele": s["allele"],
                                  "ic50_nM": s["ic50_nM"]} for s in strong],
                "junction_context": cd4.get("junction_context"),
                "alleles_without_a_model": cd4.get("alleles_without_a_model"),
                "predictor": (cd4.get("_predictor") or {}).get("tool"),
            },
            "manuscript_probes": (
                [probe(man_lines, f"{cd4['n_alleles_screened']} class II alleles")]
                + [probe(man_lines, s["peptide"]) for s in strong]
                + [probe(man_lines, str(s["ic50_nM"])) for s in strong]
            ),
            "instrument_limit": "MHCnuggets class II binding predictions. The manuscript itself "
                                "grades class II prediction as substantially less accurate than "
                                "class I, so one strong call on one allele is a weak positive, and "
                                "no class II call here is evidence of presentation or of help "
                                "delivered to a CD8 response.",
        })

    # ---- 3. anchor-position analysis ------------------------------------------------------------
    if selfsim:
        items.append({
            "aut077_phrase": "anchor-position analysis",
            "artifact": "junction-selfsimilarity.json",
            "script": "junction_selfsimilarity.py",
            "entered_repo": first_commit("research/modalities/junction-selfsimilarity.json"),
            "last_change": last_change("research/modalities/junction-selfsimilarity.json"),
            "headline_derived_from_the_artifact": {
                "n_queries": selfsim["n_queries"],
                "max_mismatches": selfsim["max_mismatches"],
                "n_queries_with_any_near_self": selfsim["n_queries_with_any_near_self"],
                "n_anchor_only_near_self_total": selfsim["n_anchor_only_near_self_total"],
                "anchor_convention_used": selfsim.get("⚠_anchor_convention"),
            },
            "manuscript_probes": [
                probe(man_lines, f"Zero of the {selfsim['n_queries']}"),
                probe(man_lines, f"0 of {selfsim['n_queries']} binders"),
            ],
            "instrument_limit": "a Hamming-distance search plus one anchor convention. Sequence "
                                "distance is not T-cell-receptor distance, and the convention is a "
                                "general class I rule rather than an allele-specific motif — see "
                                "junction-anchor-convention-sensitivity.json, which measures how "
                                "far the null travels across conventions.",
            "⚠_extended_by": "junction-anchor-convention-sensitivity.json (2026-09-01)",
        })

    # ---- 4. extended allele panel ---------------------------------------------------------------
    matrix = read_json("epitope-allele-matrix.json")
    if coverage and curve and matrix:
        # ⛔ THE PANEL SIZE COMES FROM THE FILE THAT DEFINES THE PANEL, not from the curve's
        # frequency table. The first draft of this module read `curve.allele_frequencies` and
        # derived 28, because the curve records a frequency only for an allele that presents
        # something at or below its 5.0 ceiling. 28 and 34 are both true statements about different
        # things, and only one of them is the panel.
        n_panel = len(matrix["panel"])
        presents_at_all = sorted(curve.get("allele_frequencies", {}))
        panel = sorted(curve.get("at_conventional_threshold", {}).get("alleles", []))
        items.append({
            "aut077_phrase": "extended allele panel",
            "artifact": "hla-coverage.json (+ coverage-threshold-curve.json)",
            "script": "hla_coverage.py (+ coverage_threshold_curve.py)",
            "entered_repo": first_commit("research/modalities/hla-coverage.json"),
            "last_change": last_change("research/modalities/hla-coverage.json"),
            "last_change_curve": last_change("research/modalities/coverage-threshold-curve.json"),
            "headline_derived_from_the_artifact": {
                "n_alleles_in_the_panel": n_panel,
                "panel_source": "epitope-allele-matrix.json → panel",
                "n_panel_alleles_presenting_anything_at_or_below_the_curve_ceiling":
                    len(presents_at_all),
                "⚠_the_difference": "The remaining panel alleles present no junction peptide at any "
                                    "threshold the data speaks to (ceiling "
                                    f"{curve.get('_ceiling', {}).get('value')}). That is a negative "
                                    "reading, not a missing frequency: it was checked against the "
                                    "curve's own allele set and the two agree exactly.",
                "alleles_presenting_at_the_conventional_threshold": panel,
                "conventional_threshold": curve.get("conventional_threshold"),
                "coverage_at_the_conventional_threshold":
                    curve.get("at_conventional_threshold", {}).get("coverage"),
                "lowest_threshold_with_any_presenting_allele":
                    curve.get("lowest_threshold_with_any_presenting_allele", {}).get("threshold"),
            },
            "manuscript_probes": [probe(man_lines, f"{n_panel}-allele")],
            "instrument_limit": "a class I HLA-A and HLA-B panel with no HLA-C and no class II "
                                "allele, over allele frequencies pooled across populations whose "
                                "frequencies differ by more than the figures reported. Every "
                                "coverage number is therefore a partial coverage of the class I "
                                "repertoire, and a predicted-presentation figure is not evidence "
                                "that any patient's tumour presents anything.",
        })

    for it in items:
        it["landed"] = bool(it["headline_derived_from_the_artifact"]) and any(
            p["found"] for p in it["manuscript_probes"])

    out = {
        "_what": "Provenance for the four Stage 0 items named in ledger row AUT-077: the artifact "
                 "that produced each, the figure derived from it, and whether the vaccine "
                 "manuscript states that figure.",
        "_why": "AUT-077 stands `queued` with `attempts: 0` over work that had already been run. "
                "This is the evidence for closing it, assembled so it can be checked.",
        "⛔_what_this_is_not": "Not a scientific result and not a quality judgement. It records that "
                              "an analysis ran and that a document states its number. Every figure "
                              "it points at is a binding PREDICTION or a sequence search, not a "
                              "measurement of presentation, immunogenicity, efficacy or safety.",
        "_method": "each headline is derived from the artifact and then used as a search string "
                   "against the manuscript, so an item is 'landed' only when both the artifact and "
                   "the statement exist. Nothing here is typed from a document.",
        "_manuscript": {
            "path": "research/manuscripts/neoantigen/emc-vaccine-development-path.md",
            "n_lines": len(man_lines),
            "last_commit": first_commit(
                "research/manuscripts/neoantigen/emc-vaccine-development-path.md"),
        },
        "_cost": "$0 — committed files and read-only git. No network, no predictor, no GPU.",
        "ledger_row": {
            "id": "AUT-077",
            "what": "Run the Stage 0 items: proteome-wide novelty, class II regeneration, "
                    "anchor-position analysis, extended allele panel.",
            "state_when_this_ran": "queued",
            "attempts_when_this_ran": 0,
        },
        "n_items": len(items),
        "n_landed": sum(1 for it in items if it["landed"]),
        "items": items,
        "⛔_what_none_of_these_four_covers": [
            "Step 1 of the manuscript's own §6.1 ordering — calibrating the acceptance threshold "
            "against experimentally validated epitopes — which is computational, needs only public "
            "data, and has NOT been run. coverage-threshold-curve.json supplies the "
            "threshold-agnostic curve, which is what the manuscript says is the honest report "
            "UNTIL that calibration exists; it is not the calibration.",
            "Any measurement. Steps 2 to 4 of §6.1 need synthesised peptides, EMC tissue and "
            "matched donors, and no in-silico item substitutes for one of them.",
            "A near-self search for the class II peptides. The one that exists covers the 11 class "
            "I binders only.",
        ],
    }

    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    print(f"wrote {OUT}")
    for it in items:
        probes = ", ".join(
            f"{p['needle']!r}{'@' + str(p['manuscript_lines']) if p['found'] else ' NOT FOUND'}"
            for p in it["manuscript_probes"])
        print(f"  {it['aut077_phrase']:<26} landed={it['landed']}  {probes}")


if __name__ == "__main__":
    main()
