#!/usr/bin/env python3
"""Freeze the reviewer-approved valB_mini calibration edge: Wurz compound 1 -> compound 4 (SMARCA2-VHL).

Reviewer verdict (2026-07-17, Option-1 conditional GO): the PROTAC 2 -> cis-PROTAC 2 epimer edge is RETIRED as
the valB cooperativity calibration (a pure stereocenter inversion is a null alchemical transformation under a
complete single-topology map — verified). The approved replacement is a GENUINE CONSTITUTIONAL edge from the
Wurz et al. SMARCA2-VHL series, measured by SAME-PAPER SPR:

    compound 1 (minimal linker = PYRIDINE, alpha_SPR = 12.8)  ->  compound 4 (linker = BENZENE, alpha_SPR = 2.6)

The 1->4 change is approximately a linker ring N -> CH (pyridine -> benzene): a real heteroatom/element
perturbation the production single-topology RBFE handles cleanly (element_change map), NOT an identity morph.
Preregistered quantitative target:
    ddG_coop_exp = -RT ln(alpha_4 / alpha_1) = -RT ln(2.6 / 12.8) = +0.94 kcal/mol at 298.15 K.

STARTING MODEL (reviewer mandate, item 4): stage from Wurz PDB 8G1Q, which is a 3.73 A SMARCA4-compound1-VHL
structure -- it is NOT a SMARCA2 crystal. compound 1 is the co-crystallized PROTAC in 8G1Q, so RCSB gives its
chemistry directly; compound 4 is the benzene analogue (linker pyridine N -> CH). The SMARCA2 bromodomain model
is generated by substituting the SMARCA4 BD sequence with the experimental SMARCA2 BD sequence and relaxing
(the original investigators did the same because SMARCA2 crystallization failed) -- an explicit LIMITATION.

HONESTY CONTRACT (repo golden rule): compound 1's chemistry comes from RCSB 8G1Q; compound 4 is a DEFINED single
ring-atom N->CH transformation of it (reported explicitly, validated as a genuine constitutional edge, NOT
stereo-only, NOT identity); the alpha values + the +0.94 target are the reviewer-supplied same-paper SPR numbers.
Nothing is fabricated. Because compound 4 has no separate crystal, the frozen edge records it as DERIVED and the
diagnostic enumerates EVERY pyridine ring + its N->CH variant so the linker ring is chosen with evidence, and the
smoke gate (5-part) independently re-checks built-vs-frozen chemical identity before any GPU spend.

Runs on a CI runner (unrestricted internet; the dev-sandbox egress proxy 403s RCSB). Emits wurz-calib-frozen.json
(+ a wurz-calib-diagnostic.json enumerating linker candidates).
"""
from __future__ import annotations

import json
import math
import os
import sys

import ternary_calib_freeze as tcf   # reuse _get_json, RCSB URLs, _degrader_ligand, _IGNORE_CCD

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "wurz-calib-frozen.json")
DIAG = os.path.join(HERE, "wurz-calib-diagnostic.json")

CMPD1_PDB = "8G1Q"                        # Wurz et al. SMARCA4-compound1-VHL ternary (3.73 A); compound 1 = the PROTAC
ALPHA_1, ALPHA_4 = 12.8, 2.6             # same-paper SPR cooperativity (reviewer-supplied)
RT_298 = 1.987204e-3 * 298.15            # kcal/mol
DDG_EXP = -RT_298 * math.log(ALPHA_4 / ALPHA_1)   # +0.94 kcal/mol (1->4)

# SMARCA2 bromodomain (UniProt P51531) — the experimental construct the SMARCA4->SMARCA2 model must carry.
SMARCA2 = {"uniprot": "P51531", "domain": "bromodomain",
           "note": "8G1Q resolves SMARCA4 BD; the SMARCA2 model is built by sequence substitution + relaxation."}


def _citation(pdb: str) -> dict:
    """8G1Q primary citation — confirm the Wurz provenance + capture DOI/PMID/title for the frozen record."""
    entry = tcf._get_json(tcf.RCSB_ENTRY.format(pdb=pdb)) or {}
    c = entry.get("rcsb_primary_citation", {}) or {}
    return {"title": c.get("title"), "authors": c.get("rcsb_authors"), "doi": c.get("pdbx_database_id_doi"),
            "pmid": c.get("pdbx_database_id_pub_med"), "journal": c.get("journal_abbrev"), "year": c.get("year")}


def _pyridine_variants(smiles: str) -> dict:
    """Enumerate every aromatic 6-membered ONE-nitrogen ring (pyridine) in compound 1 and, for each, produce the
    N->CH (pyridine->benzene) variant. Each candidate is a possible compound 4; the linker ring is chosen from the
    diagnostic (a linker N bridges the two PROTAC halves, so it tends to be in a ring whose two ring-exit bonds
    lead toward different large fragments). Returns candidates + the RDKit ring inventory."""
    from rdkit import Chem

    m = Chem.MolFromSmiles(smiles)
    if m is None:
        return {"ok": False, "reason": "compound 1 SMILES did not parse"}
    ri = m.GetRingInfo()
    cands = []
    for ring in ri.AtomRings():
        if len(ring) != 6:
            continue
        atoms = [m.GetAtomWithIdx(i) for i in ring]
        if not all(a.GetIsAromatic() for a in atoms):
            continue
        n_idx = [a.GetIdx() for a in atoms if a.GetSymbol() == "N"]
        if len(n_idx) != 1:                     # pyridine = exactly one ring N
            continue
        nidx = n_idx[0]
        na = m.GetAtomWithIdx(nidx)
        # exocyclic substituents on this ring = how many ring atoms carry a bond leaving the ring (linker-ness)
        exo = 0
        exo_atoms = []
        for i in ring:
            for nb in m.GetAtomWithIdx(i).GetNeighbors():
                if nb.GetIdx() not in ring:
                    exo += 1
                    exo_atoms.append(nb.GetIdx())
        # build the N->CH variant
        rw = Chem.RWMol(m)
        rw.GetAtomWithIdx(nidx).SetAtomicNum(6)
        rw.GetAtomWithIdx(nidx).SetNoImplicit(False)
        rw.GetAtomWithIdx(nidx).SetFormalCharge(0)
        try:
            var = rw.GetMol()
            Chem.SanitizeMol(var)
            var_smi = Chem.MolToSmiles(var)
        except Exception as e:  # noqa: BLE001
            var_smi = None
            print(f"[wurz] N->CH sanitize failed for ring N idx {nidx}: {e}", flush=True)
        cands.append({
            "ring_atom_idx": list(ring), "ring_N_idx": nidx,
            "N_degree_in_ring_exits": exo, "exit_neighbor_idx": exo_atoms,
            "N_has_exocyclic_substituent": any(nb.GetIdx() not in ring for nb in na.GetNeighbors()),
            "benzene_variant_smiles": var_smi,
        })
    return {"ok": True, "n_pyridine_rings": len(cands), "candidates": cands,
            "n_heavy": m.GetNumHeavyAtoms()}


def _validate_constitutional(c1: str, c4: str) -> dict:
    """compound 1 -> compound 4 must be a GENUINE constitutional edge: identical connectivity EXCEPT the single
    ring N->CH, i.e. NOT identity, NOT stereo-only. Confirms one fewer N + graphs differ + heavy-atom count equal
    (N and C are both heavy) so the perturbation is a real element change the RBFE map represents with dummies-free
    element_change=True. Also confirms it is NOT the epimer failure mode (differ after stereo removal)."""
    from rdkit import Chem

    m1, m4 = Chem.MolFromSmiles(c1), Chem.MolFromSmiles(c4)
    if m1 is None or m4 is None:
        return {"ok": False, "reason": "a SMILES did not parse"}
    flat1 = Chem.MolToSmiles(m1, isomericSmiles=False)
    flat4 = Chem.MolToSmiles(m4, isomericSmiles=False)
    def _count(m, sym):
        return sum(1 for a in m.GetAtoms() if a.GetSymbol() == sym)
    n1, n4 = _count(m1, "N"), _count(m4, "N")
    c1c, c4c = _count(m1, "C"), _count(m4, "C")
    graphs_differ_flat = flat1 != flat4                      # differ even ignoring stereo => constitutional
    return {
        "ok": True,
        "differ_ignoring_stereo": graphs_differ_flat,        # MUST be True (the epimer edge was False here)
        "is_identity": flat1 == flat4,
        "delta_N": n4 - n1, "delta_C": c4c - c1c,
        "heavy_1": m1.GetNumHeavyAtoms(), "heavy_4": m4.GetNumHeavyAtoms(),
        "single_N_to_C_swap": (n4 - n1 == -1 and c4c - c1c == +1
                               and m1.GetNumHeavyAtoms() == m4.GetNumHeavyAtoms()),
        "genuine_constitutional_edge": bool(graphs_differ_flat and (n4 - n1 == -1) and (c4c - c1c == +1)),
        "note": "a genuine ring N->CH edge is NOT the epimer null-map failure mode: differ_ignoring_stereo=True "
                "and one N is replaced by one C, so the hybrid topology carries a real element perturbation.",
    }


def freeze(chosen_ring_N_idx: int | None = None) -> dict:
    """Fetch compound 1 from 8G1Q, enumerate pyridine->benzene candidates, and (if the linker ring is chosen)
    emit the frozen 1->4 edge. chosen_ring_N_idx pins WHICH pyridine N becomes CH (the minimal linker); if None,
    the freeze stays INCOMPLETE and only the diagnostic is written so the ring is chosen with evidence."""
    lig = tcf._degrader_ligand(CMPD1_PDB)
    cite = _citation(CMPD1_PDB)
    if not lig:
        return {"_status": f"INCOMPLETE - RCSB returned no PROTAC-scale ligand for {CMPD1_PDB}",
                "cmpd1_pdb": CMPD1_PDB, "citation": cite}
    c1_smiles = lig.get("smiles_stereo") or lig["smiles"]
    variants = _pyridine_variants(c1_smiles)

    diag = {"cmpd1_pdb": CMPD1_PDB, "citation": cite, "cmpd1_ccd": lig.get("ccd"),
            "cmpd1_smiles": c1_smiles, "cmpd1_mw": lig.get("mw"), "cmpd1_name": lig.get("name"),
            "pyridine_enumeration": variants,
            "how_to_choose": "The minimal LINKER pyridine is the ring whose N->CH gives compound 4. Pick the "
                             "ring_N_idx of the linker ring (bridging the SMARCA2-warhead and VHL-ligand halves) "
                             "from the candidates, then re-run freeze(chosen_ring_N_idx=...)."}
    with open(DIAG, "w") as f:
        json.dump(diag, f, indent=2)

    if chosen_ring_N_idx is None or not variants.get("ok"):
        return {"_status": "INCOMPLETE - pyridine linker ring not yet chosen (see wurz-calib-diagnostic.json)",
                "diagnostic": DIAG, **{k: diag[k] for k in ("cmpd1_pdb", "citation", "cmpd1_ccd", "cmpd1_smiles")}}

    chosen = next((c for c in variants["candidates"] if c["ring_N_idx"] == chosen_ring_N_idx), None)
    if chosen is None or not chosen.get("benzene_variant_smiles"):
        return {"_status": f"INCOMPLETE - chosen ring_N_idx {chosen_ring_N_idx} is not a valid pyridine candidate",
                "diagnostic": DIAG}
    c4_smiles = chosen["benzene_variant_smiles"]
    val = _validate_constitutional(c1_smiles, c4_smiles)

    return {
        "_status": "FROZEN" if val.get("genuine_constitutional_edge") else "INCOMPLETE - edge not constitutional",
        "_provenance": f"compound 1 SMILES from RCSB {CMPD1_PDB}; compound 4 = defined linker ring N->CH "
                       f"(pyridine->benzene) of compound 1; alpha values are same-paper SPR (reviewer-supplied).",
        "reviewer_approval": "valB_mini per reviewer 2026-07-17 Option-1 conditional GO (Wurz 1->4 replaces the "
                             "retired PROTAC 2->cis epimer edge).",
        "citation_8g1q": cite,
        "calib_hi": {"role": "calib_hi", "name": "Wurz_cmpd1", "state": "productive_ternary_high_coop",
                     "pdb": CMPD1_PDB, "ccd": lig["ccd"], "smiles": c1_smiles, "mw": lig.get("mw"),
                     "alpha_SPR": ALPHA_1, "source": f"RCSB {CMPD1_PDB} / Wurz et al. (SPR)"},
        "calib_lo": {"role": "calib_lo", "name": "Wurz_cmpd4", "state": "productive_ternary_low_coop",
                     "modeled_from": CMPD1_PDB, "smiles": c4_smiles, "alpha_SPR": ALPHA_4,
                     "derivation": {"transform": "linker pyridine N -> CH (pyridine -> benzene)",
                                    "chosen_ring_N_idx": chosen_ring_N_idx, "ring_atom_idx": chosen["ring_atom_idx"]},
                     "note": "DERIVED (no separate crystal); the 5-part smoke gate re-checks built-vs-frozen "
                             "identity and that this is a genuine N->CH element edge, not identity/stereo-only."},
        "morph": "Wurz_cmpd1 -> Wurz_cmpd4 (pyridine linker -> benzene linker; ring N -> CH)",
        "target_bromodomain": SMARCA2,
        "starting_model": {
            "template_pdb": CMPD1_PDB,
            "is_smarca2_crystal": False,
            "construct_note": "8G1Q is a 3.73 A SMARCA4-compound1-VHL structure. Build the SMARCA2 model by "
                              "substituting the SMARCA4 BD sequence with the experimental SMARCA2 BD (P51531) and "
                              "relaxing; the original investigators did the same (SMARCA2 crystallization failed).",
            "require_two_relaxed_models": True,
            "divergence_rule": "Keep >=2 independently relaxed starting models; if they yield materially different "
                               "binding modes BEFORE production, STOP - the benchmark is not diagnostically clean.",
            "limitation": "SMARCA4-derived SMARCA2 starting model (homology substitution + relaxation), 3.73 A "
                          "parent resolution - recorded as an explicit valB_mini limitation.",
        },
        "preregistered_target": {
            "ddG_coop_exp_kcal_per_mol": round(DDG_EXP, 3), "temperature_K": 298.15,
            "formula": "ddG_coop_exp = -RT ln(alpha_4/alpha_1) = -RT ln(2.6/12.8)",
            "alpha_1": ALPHA_1, "alpha_4": ALPHA_4, "assay": "alpha_SPR (same-paper SPR; NOT TR-FRET)"},
        "decision_rule_valB_mini": {
            "PASS_requires_ALL": ["correct POSITIVE sign", "combined uncertainty EXCLUDES zero",
                                  "no unresolved forward/reverse disagreement",
                                  "no collapse / ligand escape / restraint-dominated result",
                                  "broad consistency with +0.94 kcal/mol"],
            "INDETERMINATE_not_a_pass": ["noisy positive point estimate alone (separation < 1 kcal/mol)",
                                         "CI includes zero", "unresolved hysteresis"],
            "retired_rule": "The former +-1.0 kcal/mol acceptance band is REMOVED - it could accept zero or the "
                            "wrong physical result given the <1 kcal/mol experimental separation."},
        "validation": val,
    }


def main() -> int:
    # CHOSEN_RING_N_IDX env pins the linker pyridine once identified from the diagnostic; unset => diagnostic only.
    env = os.environ.get("WURZ_LINKER_N_IDX")
    chosen = int(env) if (env and env.strip().lstrip("-").isdigit()) else None
    r = freeze(chosen_ring_N_idx=chosen)
    with open(OUT, "w") as f:
        json.dump(r, f, indent=2)
    print(json.dumps(r, indent=2), flush=True)
    print(f"[wurz-freeze] wrote {OUT} (status={r.get('_status')}); diagnostic at {DIAG}", flush=True)
    return 0 if r.get("_status") == "FROZEN" else 2


if __name__ == "__main__":
    sys.exit(main())
