args <- commandArgs(trailingOnly=TRUE)
x <- readRDS(args[1])
cat('RDS class:',paste(class(x),collapse=','),'dimensions:',paste(dim(x),collapse='x'),'\n')
stopifnot(is.matrix(x) || is.data.frame(x))
ids <- readLines(args[2])
stopifnot(sum(rownames(x)=='CSPG4')==1)
stopifnot(all(vapply(ids,function(id) sum(colnames(x)==id)==1,logical(1))))
v <- as.numeric(x['CSPG4',ids])
stopifnot(all(is.finite(v)), all(v>=0))
options(digits=17)
write.table(data.frame(sample_id=ids,gene='CSPG4',TPM=v),file=args[3],sep='\t',quote=FALSE,row.names=FALSE)
writeLines(c(paste('class',paste(class(x),collapse=',')),paste('dimensions',paste(dim(x),collapse='x')),paste('CSPG4_row_index',which(rownames(x)=='CSPG4')),paste('selected_columns',paste(match(ids,colnames(x)),collapse=','))),args[4])
