"""Retrospective bounded source-measurement check, not a disease finding."""
import pathlib,json,math,hashlib,datetime,xml.etree.ElementTree as ET
P=pathlib.Path(__file__).parent
import argparse
a=argparse.ArgumentParser();a.add_argument('--source-dir',type=pathlib.Path,default=P.parents[3]/'.cache'/'emc-r6-challenge');C=a.parse_args().source_dir

def paragraphs(name):
 r=ET.parse(C/(name+'.xml'))
 return '\n'.join(''.join(p.itertext()) for p in r.findall('.//body//p'))

clinical=paragraphs('regression2025')
primary=[{'date':'2015-03','diameter_cm':5.5,'condition':'diagnostic MRI; primary','selected_for_descriptive_arithmetic':False},{'date':'2015','diameter_cm':6.0,'condition':'initial surgical pathology','selected_for_descriptive_arithmetic':False},{'date':'2016-03','diameter_cm':2.5,'condition':'recurrence MRI; before sunitinib','selected_for_descriptive_arithmetic':True},{'date':'2016-09 approximate','diameter_cm':4.1,'condition':'after nominal6months sunitinib; source gives duration not exact month','selected_for_descriptive_arithmetic':True},{'date':'2017-11','diameter_cm':11.9,'condition':'after3months atezolizumab; intervening interval not a uniform untreated condition','selected_for_descriptive_arithmetic':True},{'date':'2018-08','diameter_cm':15.8,'condition':'progression after trabectedin; last systemic therapy reported','selected_for_descriptive_arithmetic':True},{'date':'2019-08','diameter_cm':18.0,'condition':'no subsequent systemic therapy reported; symptomatic primary','selected_for_descriptive_arithmetic':True},{'date':'2019-10','diameter_cm':18.0,'condition':'debulking pathology; distinct measurement','selected_for_descriptive_arithmetic':False}]
for v in ['5.5','6\xa0cm','2.5','4.1','11.9','15.8','18\xa0cm','NR4A3']:
 assert v in clinical,('source mismatch',v)
series=[r for r in primary if r['selected_for_descriptive_arithmetic']]
changes=[]
for a,b in zip(series,series[1:]):
 changes.append({'from':a['date'],'to':b['date'],'diameter_percent_change':(b['diameter_cm']/a['diameter_cm']-1)*100,'conditions':[a['condition'],b['condition']],'interpretation':'Acquisition modality, scan protocol and segmentation comparability are unverified. Source uses MRI explicitly in2016/2017 and does not establish identical imaging for later timepoints. Cannot assign RECIST or causal treatment effect from one reported primary diameter; intervals differ in therapy and duration.'})
untreated_change=changes[-1]
untreated_change.update({'nominal_interval_months':12,'linear_diameter_change_cm_per_month':(18-15.8)/12,'log_diameter_change_per_month':math.log(18/15.8)/12,'limit':'Month-level dates only; acquisition modality/protocol/segmentation comparability unverified. No exact-day rate uncertainty, lesion aggregate or untreated lung sizes. No volume-doubling estimate.'})
lung_states=[{'date':'2018-05','measurement':'new bilateral sub-centimetre pulmonary nodules suspicious for metastases; no individual dimensions'}, {'date':'2018-08','measurement':'stable pulmonary metastases; no individual dimensions'}, {'date':'2019-08','measurement':'enlarging bilateral presumed lung metastases; no lung biopsy/case-linked dimensions reported'}, {'date':'2020-01','measurement':'decrease after2019-10 primary debulking; no dimensions'}, {'date':'2020-05','measurement':'full radiographic resolution'}, {'date':'2024-11','measurement':'no evidence of disease on last imaging'}]
rt_text=paragraphs('massive2018')
rt=[{'source_lesion':'pelvic mass','before_cm':[17.4,13.4],'after_cm':[11.8,9.2],'before_suv':3.6,'after_suv':2.8},{'source_lesion':'left inguinal mass','before_cm':[15.1,6.9],'after_cm':[12.1,4.6],'before_suv':3.3,'after_suv':2.7}]
for x in rt:
 for v in x['before_cm']+x['after_cm']+[x['before_suv'],x['after_suv']]: assert str(v) in rt_text
 x.update({'donor':'Paoluzzi2018 one female donor; EWSR1–NR4A3 confirmed','condition':'45Gy in18fractions; ~4month post-RT PET/CT; ongoing pazopanib','diameter_percent_changes':[(a/b-1)*100 for a,b in zip(x['after_cm'],x['before_cm'])],'SUV_percent_change':(x['after_suv']/x['before_suv']-1)*100,'interpretation':'Published anatomic/metabolic decreases; cannot isolate RT effect from concurrent drug or establish population benefit.'})
r=ET.parse(C/'bsc2016.xml');tables=[''.join(t.itertext()) for t in r.findall('.//table-wrap')]
assert '1EMCS' in tables[1] and '2EMCS' in tables[1] and '6MCS' in tables[1] and '7MCS' in tables[1] and '8MCS' in tables[1]
bsc={'all_EMC_rows':[{'source_id':1,'baseline_sum_diameter_mm':132.8,'PFS_months':13.0,'best_response':'SD','best_percent_change':-1,'condition':'trabectedin'},{'source_id':2,'baseline_sum_diameter_mm':38.4,'PFS_months':7.4,'best_response':'SD','best_percent_change':-27,'condition':'trabectedin'}],'all_BSC_rows':[{'source_id':i,'histology':'MCS, not EMC'} for i in [6,7,8]],'consequence':'No randomized untreated EMC control exists in this subanalysis. Published whole-TRS/MCS BSC comparisons cannot estimate untreated EMC lesion kinetics.'}
lt=paragraphs('longterm2020');assert all(str(v)+' months' in lt for v in [50,70,126])
observation=[{'source_id':'Patient1','followup_months':50,'local_management':'none','systemic_therapy':'none','lung_sizes':'not tabulated; slow progression author observation','identity':'author-labelled histology plus EWSR1 FISH, without specified NR4A3 partner'},{'source_id':'Patient2','followup_months':70,'local_management':'none','systemic_therapy':'none','lung_sizes':'not tabulated; slow progression author observation','identity':'author-labelled histology plus EWSR1 FISH, without specified NR4A3 partner'},{'source_id':'Patient3','followup_months':126,'local_management':'palliative below-knee amputation','systemic_therapy':'none','lung_sizes':'radiographs2,5,7,10years; no individual diameter table','identity':'author-labelled histology plus EWSR1 FISH, without specified NR4A3 partner','outcome':'died of unresectable colon cancer; no inference of no EMC progression'}]
e=ET.parse(C/'elsayed2018.xml');figs=[{'id':f.attrib['id'],'caption':' '.join(f.itertext())} for f in e.findall('.//fig')]
elsayed={'donor':'53-year-old male diagnosed2009; primary RT/resection, lung lobectomy2012; no systemic therapy reported','identity':'author-labelled histology; resected lung pathology consistent with primary; no molecular result reported','all_serial_lung_figures':[f for f in figs if f['id'] in ['FIG3','FIG4','FIG5','FIG6','FIG7']],'untreated_pulmonary_window_months':47,'window':'2013-08 through2017-07; source figure captions','limit':'No individual longitudinal numeric dimensions in article text; image segmentation/lesion matching not performed, so not an estimated lung growth rate. Eight years from primary diagnosis is not eight years of the documented untreated pulmonary interval.'}
results={'date':datetime.datetime.now(datetime.timezone.utc).isoformat(),'kind':'limited source/value negative gate and reproducible arithmetic; no publication-worthy finding','primary_measurements':primary,'primary_changes':changes,'pulmonary_followup_states':lung_states,'RT_lesion_measurements':rt,'randomized_source_histology_check':bsc,'all_Brown2020_observation_donors':observation,'Elsayed2018_serial_source':elsayed,'decision':'SHELVE standalone untreated-kinetics or metabolic-phenotype paper from this bounded gate','scientific_value':'Known indolence and rare regressions are the authors\' reported observations. The published numerical primary interval changes do not supply a new untreated lung comparator. Stable disease or modest shrinkage alone cannot establish treatment attribution, but this is established design caution rather than a new disease finding.','reopening_condition':'Independent authenticated EMC cohort with complete case-linked serial lesion dimensions/acquisition dates during documented untreated intervals, comparator controls or mechanistically discriminating measurements; all relevant suitable sources evaluated before promotion.'}
(P/'measurement-gate-results.json').write_text(json.dumps(results,indent=2)+'\n')
print(json.dumps({'checks':'source numeric/text assertions passed','primary_intervals':len(changes),'untreated_primary_change_percent':untreated_change['diameter_percent_change'],'RT_lesions':len(rt),'EMC_trial_rows':2,'BSC_EMC_rows':0,'observation_donors':3,'serial_Elsayed_figures':len(elsayed['all_serial_lung_figures']),'decision':results['decision']},indent=2))
