"""Compact endocrine source/condition decisions; whole sources remain ignored."""
import pathlib,json,hashlib,datetime,subprocess,xml.etree.ElementTree as E
B=pathlib.Path(__file__).parent
ROOT=pathlib.Path('/workspace/Rare-cancers/research/autonomy')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(n,d): (B/n).write_text(json.dumps(d,indent=2,allow_nan=False)+'\n')
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def prior(n):return json.loads(subprocess.run(['git','show','HEAD:research/autonomy/fresh-discovery-2026-10-05-round8/adaptation/'+n],capture_output=True,text=True,check=True).stdout)
pgr=prior('MEASUREMENTS.json')['observations']['pgr2022'];dump('REUSED-PGR-PRIOR-ART.json',{'utc':now,'status':'verified evaluation reused','primary_pmid':'36103645','primary_pmc':'PMC9489176','DOI':'10.1200/PO.22.00039','all_case_conditions':pgr,'source_hashes':{k:v for k,v in prior('MEASUREMENTS.json')['sources'].items() if k=='pgr2022'},'limits':'Published outliers, fusion and course are prior art. No numeric image reconstruction, new endocrine-response claim or independent posttamoxifen molecular sampling.'})
case=[]
for fn,identity in [('vulvar2021.xml','63F EWSR1 and NR4A3 FISH; source reports ESWR1-NR4A3 fusion (printed spelling retained)'),('breast2022.xml','45F author-labelled primary breastEMC/EWSR1-rearranged; no case NR4A3 authentication assumed'),('vulvar2015.xml','32F author-labelled recurrent vulvarEMC; no new molecular authentication'),('breast_met2015.xml','Author-labelled EMC breast metastasis; no receptor condition assigned')]:
 p=B/'.cache'/fn;rt=E.parse(p).getroot();ps=[' '.join(q.itertext()) for q in rt.findall('.//p')];passages=[t for t in ps if 'estrogen receptor' in t.lower() and ('negative for' in t.lower() or 'immunophenotypically inconsistent' in t.lower())]
 obs={'source':fn,'cache_sha256':sha(p),'identity':identity,'status':'evaluated' if fn=='vulvar2021.xml' else 'demonstrably unsuitable measurement','condition':'Published excisional tumor IHC' if fn=='vulvar2021.xml' else 'Published tumor/pathology clinical conditions, no estrogen-response set or matched endocrine assay recovered','measurement':'Tumor estrogen receptor IHC negative; PGR/ESR2 staining not assigned from differential-diagnosis discussion.' if fn=='vulvar2021.xml' else 'No reported ER/PR endocrine-program measurement identified in inspected source; absence of a reported assay is not receptor negativity.','selected_exact_passages':passages[:2],'overlap':'Distinct source-case labels; no pool with RNA or PGR donor; no cross-source donor independence assumed.'}
 case.append(obs)
dump('PUBLISHED-ENDOCRINE-CONDITIONS.json',{'utc':now,'cases':case,'additional_sources':[{'source':'PMC6449903 vulvar2019','status':'unavailable evidence','attempts':'EuropePMC500; BioC200 error-text6148B, not XML/full primary; all payloads/receipts retained. No receptor-negative inference.'},{'source':'PMID18855877 PMC4429309 EWSR1/NR4A3-PPARG2008','status':'unavailable evidence','attempts':'EuropePMC500; BioC429. Abstract prior-art molecular source, not an estrogen-response contrast. Source limitation preserved.'}],'limit':'Selected published conditions are not a certificate that every historical endocrine IHC case or case table has been acquired.'})
r=json.loads((B/'PROGRAM-RESULTS.json').read_text());conditions=[]
for c,co in r['cohorts'].items():
 for row in co['all_source_EMC_metadata']:
  i=row['sample_id'];sc=json.loads((B/'PROGRAM-SCORES.json').read_text())[c]
  conditions.append({'source':c,'specimen':i,'condition':'Bulk source tissue; treatment status not established here; source exception/technical history retained in metadata','status':'evaluated','metadata':row,'program_percentile_scores':{k:v['primary_population'][i] for k,v in sc.items()},'limits':'Not hormone-perturbation or receptor protein measurement; no inferred partner, donor overlap, sex or hormone state.'})
dump('EMC-CONDITION-OBSERVATIONS.json',{'utc':now,'all19_source_specimens':conditions,'technical_and_donor_limit':'Hofvander3priorMDBoverlaps and1LR separately evaluated, not19independent newly observed donors. Individual Hofvander/GSE24369 donor crosswalk unresolved.'})
coverage=[
 {'source':'Hofvander2026 primaryS1+TPM','status':'evaluated','conditions':'All13EMC; nineoverlap-reduced primary, threeMDBdiscovery-overlap andoneLR; originalS1 sex9M2F2NA, primary9sex6M1F2NA; all published source-case metadata and target-gene values retained. Fixed thirteenLGFMS/sixtyMFS, all eligible source-class malignant context.','consequence':'Early/late program fails; exact paired-data/sex sensitivities and missing symbols retained.'},
 {'source':'GSE24369/PMID21536545','status':'evaluated','conditions':'AllsixEMC GSM600934–939; all17LGFMS/sixMFS; originalGPL6244unambiguous measured-probe mapping median; 42samples parsed, no unmapped-zero replacement. Desmoid/muscle not malignant controls; unstratifiedSFT not assumed malignant.','consequence':'Earlyweakpositive/lateweakpositive RNA-array discordance retained; coherence/uncertainty gates fail. No sex fields.'},
 {'source':'Wilbur2022 PGR::NR4A3','status':'verified evaluation reused','conditions':'OneTP_2274donor35F; all8clinical conditions, recurrentpretamoxifenRNA and Table1/figure/narrative distinctions retained fromR8.','consequence':'Exceptional receptor outliers/clinical course published; no serial molecular assay; no added novelty.'},
 {'source':'Vulvar2021 PMID34458187/PMC8387072','status':'evaluated','conditions':'One63F EWSR1/NR4A3-authenticated source excision IHC; estrogenreceptornegative.','consequence':'Published contrary protein observation; no PGR/ESR2 or hormone response inferred.'},
 {'source':'Breast2022/PMC9248243, vulvar2015/PMC4579798, breastmetastasis2015/PMC4492482','status':'demonstrably unsuitable measurement','conditions':'All identifiable index-case endocrine assay scope checked in acquired primaryXML; morphology/clinical/IHC sources without required endocrine program/paired assay, no assigned ER/PR negativity.','consequence':'Could support future identity/citation trails; not endocrine controls or validated independent receptor measurements.'},
 {'source':'Vulvar2019/PMC6449903; PPARG2008/PMC4429309','status':'unavailable evidence','conditions':'Actual primaryAPI500s and BioC errortext/429 retained; title/abstract prior art only where available.','consequence':'Missingfullsource stays visible; no negative assay or lack of receptor signaling claim.'},
 {'source':'GSE4303/GPL3290 older myxoid-chondrosarcoma rows','status':'pending accessible analysis','conditions':'Alltenprinted source aliases/GSMs retained in source metadata gate; primarysource/overlap/multiplatform ratios require separate source-compatible analysis.','consequence':'Not treated negative or excluded; any stronger transcriptomic absence/promotion requires evaluation. Frozen primary two-source program hypothesis already fails.'},
 {'source':'GSE71119 broader RNA source labels and R7Brenca2019 endogenousRNA inputs','status':'pending accessible analysis','conditions':'Retained broader metadata did not identify an EMC literal/chondrosarcoma row; generic labels not assigned histology. Original R7Brenca donor/assay overlap limits reused; endocrine gene-set values not recomputed.','consequence':'Additional authentication/mapping/program analysis unresolved, not excluded by catalogue wording.'},
 {'source':'Nottley2025/R3 UCL RNA','status':'verified evaluation reused','conditions':'Donors9EWSR1/29TCF12 paired pre/post50Gy/25RNA; previous evaluation retains bulk composition/treatment conditions, no released individualRNA matrix. Existing thesis includes estrogen among14PROGENy paths; not a new endocrine method finding.','consequence':'Published pathway inference/graphs cannot supply new exact individual fold changes or an antiestrogen response result.'},
 {'source':'R8TempO/culture sources','status':'pending accessible analysis','conditions':'All12library calibrated counts preservedcache-only, targetsmasked inpriorwork; R8threeper-libraryestimatorfailures notassay invalidity. No hormone-perturbation contrast or fullyauthenticated condition-to-endocrine program linkage newly analyzed here.','consequence':'No culture rescue or independence claim; suitable authentic comparative measurements remain pending for any advancing broad claim.'},
 {'source':'ORIEN2025 PMID40328759/PMC12055966','status':'pending accessible analysis','conditions':'Diagnosticowner sourcegate:12generic MyxoidChondrosarcoma tumors; no EMC/NR4A3 individual authentication. Public49,904,690BData1–4book unassessed; no identity or endocrinevalue transfer.','consequence':'Potential broadercase/RNA identity remains pending. No duplicate download or false nonEMC exclusion.'},
 {'source':'Interrupted restricted task content','status':'unavailable evidence','conditions':'FAP-tissue/glycan/structural-genomics/HLA-review restriction preserved; no new route, worker or interpretation.','consequence':'Restriction gaps not biological absence.'}
]
dump('COVERAGE.json',{'utc':now,'scope':'Dated bounded source/primary-set pilot; no complete universal discovery or endocrine-response absence claim. All identified relevant conditions and pending suitable evidence remain explicit.','search_cutoff':now,'searches':'EuropePMC disease/endocrine, disease/expression and NR4A3/TEC-endocrine families; title/abstract eligibility screen plus acquired index sources/citation trails, all13Hof/all6originalarray. Queries/raw counts/hashes in receipt files. Fulltextindex reference hits are not completed sample evaluation.','records':coverage,'pending_suitable_blocks_promotion':True})
decision={'utc':now,'decision':'SHELVE standalone endocrine program paper','validity':'Valid descriptive frozen-set calculations with source/probe/sex/overlap sensitivity; no replicated coherent high-estrogen-response program established.','value':'Failure of a speculation does not contradict an established panEMCendocrine claim. Published exceptional PGRcase is already priorart. Correct program scores and one gene-high example do not yield a useful new independent measurement implication after contrary evidence.','replicated_numerical_gate':r['replicated_numerical_gate'],'no_therapy_inference':True,'no_exhaustion':True,'TMEM266':'shelved','pending_suitable_blocks_promotion':True,'reopen':'New authenticated independent EMC endogenous ER/PR protein and matched hormone-perturbation/time-course transcripts with malignant compartment/sex/lineage controls and donor/partner mapping, or useful cohort-linked receptor assay contrast not already published. Complete additional suitable public assay/overlap coverage and independent source/value challenge before promotion. Do not simply select a new expression panel or favor a singleESR/PGR/GREB1 case.','next':'Independent phosphoproteomic omission/case/assay-linkage review assigned by lead; not a hormone mechanism extension.'}
dump('DECISION.json',decision)
lines=['2026-10-05 — SHELVE the standalone endocrine-program proposal.','', 'The frozen early-estrogen-response gene set did not establish a replicated coherent EMC program beyond the published PGR::NR4A3 exception. This failure is not a finding that EMC lacks receptors, does not respond to hormones, or cannot benefit from endocrine therapy. No manuscript or new publication-worthy finding is warranted. The public search remains unexhausted; TMEM266 stays shelved.','']
for c,d in r['cohorts'].items():
 for s,v in d['sets'].items():lines.append(f"{c} {s}: {len(v['covered_genes'])}/200 genes; equal-histology AUC{v['primary']['equal_histology_AUC']:.6f}, coherence{v['coherence']['fraction']:.6f}, one-sided95% bootstrap lower{v['bootstrap']['one_sided_95_lower']:.6f}.")
lines+=['','All13Hofvander conditions and all6arrayEMC measurements are retained; the nine-primary-Hofvander analysis separates three known olddiscoveryoverlaps andoneLR. RNA early-set AUC0.196 conflicts with weak array0.585; bothfail coherence/uncertainty rules. Late-response setsfail too; their139?shared genes are counted exactly in results and do notconstitute independent validation. Original S1 supplies sex9M/2F/2unknown; arraysexunreported. Sex/year/commonmapping/leave-one/example-removal and broader malignant-context checks do notrescue the original interpretation.','', 'Separate receptor observations remain real. Hofvander11881-19 hasGREB142.04TPM with ESR10.10/PGR0.01TPM, so it cannotrescue the multigene coherence rule. All source ESR1/ESR2/PGR/GREB1 values are retained. A63FNR4A3-confirmed vulvar case has published negative ERIHC. Neither observation measures hormone dependence. The original35FPGRfusion donor and >5-year tamoxifen course, all8clinical conditions and Table1/narrative distinctions are verified priorart fromR8.','', 'Older GSE4303 printedtenmyxoidchondrosarcoma rows, broaderRNA identities, Brenca/TempO endocrine mappings, UCL individualRNA and public genericORIEN rows remain explicit pending/limited evidence. Primary-source API failures stay unavailable, distinct from negative assays. Suitable accessible pending evidence blocks promotion; this shelved packet makes no complete endocrine absence or universalcoverage claim.','', 'The lists come from officialMSigDB early/late estrogen-response200-gene sets and primary Liberzon2015 methodology. They can also reflect lineage, secretory/metabolic/proliferation composition and do not assay receptoractivity in EMC. A numericallycorrect failed speculativescore comparison or renamedmarker subset is insufficient scientificvalue. Reopening requires new authenticated orthogonal/endogenous hormone-state measurements with useful independent contrast; exact gene/probe/source/condition tables and scripts preserve the current limits.','', 'Original caches are ignored and reusedinplace; originals were not deleted. No rawread/matrixredownload, UI/computeruse, restrictedlane bypass, spend/GPU/outreach/publication or sharedrootedit occurred. Quietfile/APIwork only; lead owns integration, gates and verifiedpush.']
lines=[x.replace('139?shared genes',str(r['set_overlap'])+'shared genes') for x in lines];(B/'REPORT.txt').write_text('\n'.join(lines)+'\n')
sources=[]
for p in sorted((B/'.cache').rglob('*')):
 if p.is_file():sources.append({'path':str(p),'bytes':p.stat().st_size,'sha256':sha(p),'disposition':'cache-only; notGit'})
dump('CACHE-ORIGINALS.json',{'utc':now,'new_retained_bytes_including_outputs':sum(r['bytes'] for r in sources),'new_soft_cap_bytes':67108864,'files':sources,'legacy_sources':'SOURCE-INPUT-RECEIPTS and REUSED-PGR-PRIOR-ART bind old shared/originalsources usedinplace; no copies or recoveredWindowscacheclaim.'})
print('finalized',now,'newraw',sum(r['bytes'] for r in sources),'shared-set-overlap',r['set_overlap'])
