"""Human/model-authored judgments after complete packet reading; no prior labels read."""
import json,hashlib,gzip,datetime
from pathlib import Path
OUT=Path(__file__).resolve().parent
ROOT=OUT.parents[2]
REPAIR=ROOT/'research/autonomy/trial-reference-repair-2026-09-05'
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def dump(n,d):
 p=OUT/n
 if p.exists():raise RuntimeError('Frozen/preserved file exists: '+str(p))
 p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def sha(b):return hashlib.sha256(b).hexdigest()
def now():return datetime.datetime.now(datetime.timezone.utc).isoformat()
def resolve(d,p):
 for s in p.strip('/').split('/'):
  s=s.replace('~1','/').replace('~0','~');d=d[int(s)] if isinstance(d,list) else d[s]
 return d
# Labels apply only to disease-level scope; never individual eligibility.
E='explicit_diagnosis_compatible';F='defining_fusion_compatible';C='fusion_class_compatible';B='broad_tumor_compatible';X='explicit_exclusion';U='insufficient_evidence'
J={}
def add(n,labels,cohorts,rationale,quotes,biomarker='No additional tumor biomarker gate stated in the saved disease inclusion criteria.',uncertainty='Full external protocol not reviewed; remaining patient-level criteria are preserved in the complete source evidence.',restriction='none',domain='oncology',purpose='investigational treatment',availability='Current site and cohort enrollment not verified; overall status is the saved registry snapshot only.'):
 J[n]={'labels':labels,'cohort_reconciliation':cohorts,'rationale':rationale,'decisive_quotes':quotes,'extra_biomarker_requirement':biomarker,'protocol_uncertainty':uncertainty,'restriction_type':restriction,'task_domain':domain,'purpose_interpretation':purpose,'recruitment_uncertainty':availability}
add('NCT03967834',{'DSRCT':E},['Prospective rare-sarcoma biospecimen cohort explicitly includes DSRCT; retrospective cases described separately.'],'DSRCT is explicitly enumerated in the positive histology list. This is translational characterization, not a therapeutic drug trial.',['Desmoplastic Small Round Cell Tumours (DSRCT)','Diagnosis of all other histotypes of soft tissue sarcoma.'],purpose='translational biospecimen and clinical characterization')
add('NCT05918640',{'EMC':C,'DSRCT':E,'SS':B},['Phase 1 dose escalation and exploratory cohort require EWSR1, FUS or TAF15-containing fusion. EMC compatibility is limited to matching FET-fused variants.','DSRCT is explicitly recognized but enrollment is conditional on at least 3 non-DSRCT patients enrolled without dose-limiting toxicity; satisfaction of that condition is unknown.','Phase 2 requires Ewing sarcoma with EWS-FLI1 and does not establish an EMC, DSRCT or SS pathway.','SS has broad solid-tumor histologic scope in phase 1 only, but its defining SS18::SSX does not establish a FET gate; hypothetical additional FET alteration remains unestablished.'],'The phase-1 molecular class is broader than Ewing sarcoma, despite the arm label. Preserve the DSRCT safety lead-in condition and the narrower phase-2 restriction.',['Patients must have a known FET fusion (fusion that contains EWSR1, FUS, or TAF15)','Patients with Desmoplastic small round cell tumor (DSRCT) will be excluded from enrollment until at least 3 non-DSRCT patients have been enrolled without dose limiting toxicity.'],biomarker='Documented FET-containing fusion required in phase 1; EMC only FET-partner subset; DSRCT EWSR1::WT1 matches supplied defining scope; SS18::SSX alone does not qualify. SS additional qualifying fusion unestablished.',availability='Overall RECRUITING snapshot. Phase/cohort opening unknown; DSRCT hold is conditional, with satisfaction unknown, not asserted currently blocked.',restriction='phase-specific closed histology and conditional safety hold')
add('NCT07695311',{'EMC':X},['Both monotherapy safety and later combination cohorts require ES or DSRCT plus one of the listed fusions; no EMC cohort.'],'An EWSR1 gene hit does not overcome the ES/DSRCT histologic restriction or listed FLI1/ERG/WT1 partners.',['Participants must have histologically confirmed Ewing sarcoma (ES) or desmoplastic small round cell tumor (DSRCT)','EWSR1-FLI1, EWSR1-ERG, EWSR1-WT1'],biomarker='Listed fusion breakpoint plus HLA peptide fit; age/combination cohorts require safety review. No EMC-specific fit established.',restriction='closed allowed histology list',availability='NOT_YET_RECRUITING snapshot; pediatric and combination openings depend on safety review and IRB approval.')
add('NCT06277154',{'DSRCT':E},['Both randomized treatment groups share histologic eligibility explicitly naming DSRCT.'],'DSRCT is named among eligible advanced STS; the separate EMC exclusion does not exclude DSRCT.',['endometrial stromal sarcoma, desmoplastic small round cell tumor.'],uncertainty='First-line advanced disease, 18-70 years and full clinical constraints apply; no external protocol reviewed.')
add('NCT06625190',{'SS':E},['Relapsed/refractory NRSTS includes synovial sarcoma in shared transplant eligibility; phase Ib dose selection precedes phase II.'],'SS is directly named, with pediatric/AYA age, transplant suitability and donor requirements.',['relapsed/refractory non-rhabdomyosarcoma soft tissue sarcoma (NRSTS): synovial sarcoma','Haplo-identical related donor'],biomarker='No tumor molecular biomarker gate stated; haplo-identical donor and transplant requirements are additional constraints.')
add('NCT06456359',{'EMC':X},['Single maintenance arm allows DSRCT or SySa only.'],'The fusion discussion concerns the two named histologies and is not an all-fusion basket.',['Reference pathological proven diagnosis of DSRCT','Reference pathological proven diagnosis of SySa'],biomarker='High SSTR2/3/5 mRNA expression by MASTER/INFORM RNA sequencing; not evidence of EMC inclusion.',restriction='closed allowed histology list',uncertainty='Referenced prohibited medication Table 5 is not supplied as full external protocol; remission, timing and age constraints remain.')
add('NCT05135975',{'EMC':B,'DSRCT':E,'SS':B},['Stratum A names DSRCT BR2 or later and separately any other soft tissue sarcoma BR2 or later, covering broad EMC/SS scope.','Strata B, C and D are metastatic Ewing, osteosarcoma and fusion-positive rhabdomyosarcoma, respectively; they do not override Stratum A.'],'A broad STS pathway persists alongside the explicitly named DSRCT pathway, but omitted protocol exclusions prevent definitive eligibility.',['Desmoplastic small round blue cell tumor, BR2 or later','Any other soft tissue sarcoma, BR2 or later','SEE PROTOCOL FOR ADDITIONAL EXCLUSION CRITERIA'],uncertainty='Explicit missing external exclusion criteria and referenced best-response definitions (Section 3.1.2); histology scope supported, full protocol eligibility unresolved. BR2+, maintained best response, age and maintenance timing requirements retained.')
add('NCT04901702',{'DSRCT':B},['Phase I A/B and expansions A1/B1 allow non-Ewing solid tumors.','Expansion A2 additionally requires a deleterious HR-repair/DSB signaling alteration.','Phase II is histologically Ewing restricted and does not establish DSRCT scope.'],'The broad phase-I pathway makes a whole-trial DSRCT exclusion inappropriate; the molecular EWS criterion belongs to phase II.',['Patients with refractory or recurrent non-central nervous system (CNS) solid tumors not amenable to curative treatment are eligible.','Patients eligible for the expansion cohort, A2'],biomarker='HR-repair/DSB deleterious alteration required for A2 only, unestablished; no such gate stated for phase I A/B or A1/B1.',availability='RECRUITING snapshot does not establish which phase or expansion is open.')
add('NCT07297979',{'DSRCT':X},['Dose confirmation and expansion both require histologic Ewing sarcoma and EWSR1-ETS molecular evidence.'],'DSRCT EWSR1::WT1 is not the required Ewing histology or ETS-partner criterion.',['Histologically or cytologically confirmed EWS with molecular evidence of an EWSR1 translocation with an E26 transformation-specific (ETS) family gene'],biomarker='EWSR1-ETS required; shared EWSR1 alone insufficient.',restriction='closed histology plus defining molecular restriction',purpose='dose-finding anticancer intervention; registry primaryPurpose BASIC_SCIENCE retained')
add('NCT05071209',{'EMC':C,'DSRCT':F,'SS':B},['Part A and B1 allow any EWS-fusion positive solid tumor; DSRCT defining EWS-WT1 explicitly included, EMC only EWSR1-fused subset.','PAX3-FOXO1 rhabdomyosarcoma route does not cover these diagnoses.','Part A DDR and Part B3 allow non-CNS solid tumor with qualifying inactivating DDR alteration: possible SS histologic scope, extra marker unestablished.'],'An EWS-fusion route and a separate DDR route coexist. SS cannot be labeled excluded merely because SS18::SSX is not an EWS fusion.',['any EWS-fusion positive solid tumor','EWS-WT1, EWS-ATF1','Any (non-CNS primary) solid tumor including lymphoma with inactivating alterations'],biomarker='EWS-fusion confirmed in tissue for fusion route; EMC EWSR1 subset only. SS requires additional qualifying DDR alteration, unestablished. Pathogenicity review and study-chair approval may be necessary.',availability='ACTIVE_NOT_RECRUITING saved status; disease scope remains a historical/registered scope judgment, not a currently open opportunity.')
add('NCT01804634',{'DSRCT':E},['Single transplant cohort names DSRCT among examples meeting high-risk expected-survival requirement; other solid tumors considered case by case.'],'Explicit DSRCT scope remains conditional on high-risk assessment, stable disease where measurable, donor and transplant criteria.',['Desmoplastic small round cell tumor','Any other solid tumor and soft tissue sarcoma'],biomarker='Suitable HLA-haploidentical donor required; no tumor biomarker gate stated.')
add('NCT06239272',{'DSRCT':X},['Low-, intermediate- and high-risk NRSTS groups share explicit DSRCT exclusion.'],'General NRSTS terminology does not overcome direct exclusion of desmoplastic small round cell tumor.',['rhabdomyosarcoma, desmoplastic small round cell tumor, BCOR-CCNB3 fusion positive sarcoma.'],restriction='direct diagnosis exclusion')
add('NCT03013998',{'DSRCT':X},['Master groups A/B and select-site C enroll AML/myeloid malignancies; all listed S1-S26 therapeutic cohorts remain under that scope.','Closed historical cohorts and currently described S17/S24/S25/S26 do not add a solid-sarcoma pathway.'],'AML/myeloid enrollment cannot be inferred to include DSRCT from WT1 or fusion terms.',['Group A: Patients must have previously untreated AML','Group B: Patients must have relapsed or refractory AML'],restriction='closed hematologic disease domain',purpose='AML genomic assignment and investigational treatment')
add('NCT07188532',{'EMC':U},['Cohort A groups 1/2, B and C are all within Ewing or conditionally Ewing-like sarcoma treated per Ewing paradigms.'],'The record permits Ewing-like cases but does not establish that EMC belongs to that protocol definition. An EWSR1 non-ETS condition term is insufficient to settle EMC eligibility.',['Patients with "Ewing-like" sarcoma may be eligible if patients are planned to be treated per Ewing treatment paradigms'],uncertainty='Unresolved meaning of Ewing-like and trial-specific Ewing treatment paradigms for EMC. No external protocol or investigator confirmation available.',restriction='unresolved histology boundary')
add('NCT06526897',{'DSRCT':U},['Both imaging arms share the listed truncal/extremity histologies and exclude retroperitoneal/mesenteric/abdominal sarcoma.'],'DSRCT is not expressly included. Ewing-like and unclassified grade-2/3 language does not establish DSRCT inclusion. The site restriction excludes abdominal cases but cannot establish universal DSRCT exclusion.',['extraskeletal Ewing and Ewing-like sarcoma','Patient must not have retroperitoneal, mesenteric/abdominal sarcoma'],uncertainty='DSRCT fit to allowed histologies unresolved, including unusual extra-abdominal sites; grade/stage/location and prior curative resection all required.',restriction='anatomic exclusion and unresolved histology boundary',purpose='lung surveillance imaging comparison; not systemic treatment')
add('NCT06367075',{'EMC':X},['Single cadonilimab/adriamycin arm excludes extraosseous myxoid chondrosarcoma in inclusion definition.'],'EMC is directly excluded despite broad STS framing.',['soft tissue sarcomas other than','extraosseous myxoid chondrosarcoma'],restriction='direct diagnosis exclusion',uncertainty='Saved age fields conflict: text less than 60 versus structured maximum 75; this does not alter histologic exclusion.')
add('NCT07202884',{'EMC':U},['GZS1/GZS2 and both active/placebo groups concern female stress urinary incontinence with overweight/obesity.'],'This is a nononcology search hit. The record does not establish an EMC oncology cohort or directly exclude every person with an EMC history.',['Have a diagnosis of stress urinary incontinence'],domain='nononcology',purpose='stress urinary incontinence and weight-related intervention',restriction='outside oncology task domain',uncertainty='No oncology eligibility inference; any coincident EMC patient eligibility is unknown and outside the task.')
add('NCT07037433',{'EMC':X},['Both cardiovascular-outcomes groups share recent malignancy exclusion.'],'Outside oncology task domain, with an explicit 5-year malignancy exclusion covering active/recent EMC. This is not a lifetime disease exclusion.',['History of malignancy within the last 5 years before screening or between screening and randomization'],domain='nononcology',purpose='cardiovascular morbidity/mortality intervention',restriction='direct recent-malignancy exclusion; outside oncology task domain',uncertainty='Cancer-free history beyond five years is not ruled out by this clause; no EMC treatment scope.')
add('NCT07141732',{'EMC':X},['Single newly diagnosed glioblastoma cohort; no sarcoma arm.'],'Required glioblastoma histology and active/prior malignancy exclusion preclude an EMC disease-directed pathway. EMC in study description denotes European Medical Center.',['The subject has been newly diagnosed with glioblastoma','Active or prior malignancy'],restriction='closed histology list plus other-malignancy exclusion')
add('NCT06094101',{'EMC':X,'DSRCT':X,'SS':E},['Screening stage 1 restricts enrollment to metastatic fusion-driven rhabdomyosarcoma, Ewing and synovial sarcoma.','Stage 2 requires successful personalized vaccine manufacture and complete/stable partial remission with local treatment of residual sites.'],'Generic fusion-driven language does not expand the explicit screening histology list; SS is named, EMC and DSRCT are not.',['Confirmed metastatic fusion-driven rhabdomyosarcoma, Ewing- and synovial sarcoma','Design and production of the patient-individual vaccine cocktail was successful'],biomarker='Fusion-breakpoint WES/RNA information and successful individual vaccine production required; no single predefined HLA allele gate claimed.',restriction='closed allowed histology list for EMC/DSRCT',uncertainty='Remission/PRplus and investigator review remain required; no proof of successful manufacturing for hypothetical patient.')
add('NCT06571734',{'EMC':C,'DSRCT':C,'SS':E},['Cohort 1 leiomyosarcoma and cohort 2 bone sarcoma do not define these STS pathways.','Cohort 3 accepts histologically confirmed metastatic/unresectable translocation-associated STS, with greater than 2 prior treatment lines and no more than 2 TKI lines. SS is explicitly named as an example in enrollment description.'],'The TAS class supports the supplied fusion-defined diagnosis scope; it is not solely a leiomyosarcoma trial.',['Inclusion Criteria For Cohort 3 - Translocation-associated Soft Tissue Sarcoma','metastatic or unresectable translocation-associated soft tissue sarcoma (TAS)'],biomarker='Translocation-associated histology needs NCCN-center pathology review; no additional named target biomarker gate stated.',uncertainty='TAS pathology adjudication and cohort opening remain unverified. Preserve >2 prior treatment lines exactly; no extrapolation of benefit.')
add('NCT06235125',{'EMC':B},['Single Cytalux imaging cohort includes other NRSTS despite osteosarcoma-specific official title.'],'Full eligibility and descriptions support a broader pediatric sarcoma imaging cohort than the title alone.',['or other non-rhabdomyosarcoma soft tissue sarcoma'],purpose='fluorescence-guided pulmonary surgery imaging',uncertainty='Pulmonary surgical indication, age/weight and other constraints required; registry birthday/sex criteria contain awkward or conflicting language needing protocol clarification.')
add('NCT07383116',{'EMC':X},['Both HB0025 and tislelizumab chemotherapy arms require nonsquamous NSCLC; sarcoma components are expressly excluded.'],'This is a lung-carcinoma study, not an EMC lung-metastasis study.',['non-squamous non-small cell lung cancer (NSCLC)','Histologically confirmed presence of any small cell carcinoma, neuroendocrine carcinoma, or sarcoma components'],biomarker='EGFR/ALK and other driver exclusions apply to NSCLC, not an EMC molecular route.',restriction='closed histology plus direct sarcoma-component exclusion')
add('NCT06646627',{'EMC':X},['Intraperitoneal and IV arms both enroll ovarian carcinoma; pure sarcoma excluded even though focal sarcomatous elements in carcinoma allowed.'],'An ovarian/peritoneal location or B7-H3 expression cannot overcome the pure-sarcoma exclusion.',['The study does not include pure sarcoma, stromal, or germ-cell tumors.','B7-H3 positive expression on malignant cells is NOT required'],restriction='direct pure-sarcoma exclusion',biomarker='B7-H3 expression explicitly not required; do not invent a biomarker gate.')
add('NCT04776525',{'SS':E},['Single sequential chemotherapy cohort lists synovial sarcoma.'],'Explicit SS scope is localized high-grade extremity/girdle/trunk disease; metastases excluded.',['Synovial sarcoma'],uncertainty='No external protocol read; size, grade, prior treatment and location restrictions retained.')
add('NCT07698899',{'SS':B},['All four dose levels share open-ended B7-H3-expressing tumor scope and required recurrent/refractory CNS disease.'],'The list is expressly non-exhaustive. SS is not named, so only broad histologic scope is supported, conditional on B7-H3 and CNS setting.',['Histologically confirmed diagnosis of a tumor that is known to express B7-H3 including but not limited to'],biomarker='Tumor known to express B7-H3 required; SS-specific satisfaction unestablished. CNS involvement and intraventricular access additionally required.',uncertainty='How an unlisted SS tumor establishes B7-H3 eligibility is not specified; no negative inference or guaranteed eligibility.')
add('NCT07271914',{'DSRCT':X},['Single early ovarian/fallopian diagnostic surgery group; sarcomas explicitly excluded.'],'Non-epithelial ovarian wording is narrowed by a direct sarcoma exclusion.',['Sarcomas, melanomas, mesotheliomas, hematologic malignancies'],restriction='direct sarcoma exclusion',purpose='surgical staging and histopathologic diagnosis')
add('NCT07359053',{'EMC':B},['Bone arm uses lenvatinib; soft tissue arm uses anlotinib. Broad STS criterion supports EMC in STS arm.'],'No direct EMC restriction is stated, but suitability for the chemotherapy regimen is investigator-determined.',['Histologically confirmed advanced/metastatic bone or soft tissue sarcoma.'],uncertainty='Investigator may deem histologies unsuitable; prior first-line progression and full organ/clinical constraints remain. No diagnosis-wide treatment suitability inferred.')
add('NCT05774275',{'SS':E},['Phase Ib and II treatment arm both include localized SS.'],'Synovial sarcoma is explicitly included; metastatic disease and radiation-induced sarcoma are excluded.',['leiomyosarcoma, synovial sarcoma, myxofibrosarcoma'],uncertainty='Localized limb/trunk, grade, size/resectability and age constraints required; no external protocol reviewed.')
add('NCT07575724',{'SS':B},['Both biopsy-tract strategies accept primary extremity bone/STS; no SS-specific exclusion.'],'Broad extremity STS surgical scope includes SS at disease level, conditional on limb-sparing en-bloc resection and absence of distant disease.',['primary bone or soft tissue sarcoma of the extremities'],purpose='surgical biopsy-tract management comparison')
add('NCT06761651',{'SS':B},['Part 1 dose escalation accepts advanced/metastatic solid tumors after standard therapy.','Part 2 selects common cancers or other tumor types with best Part-1 responses; SS expansion is not established.'],'The broad escalation pathway persists, but SS-specific expansion or biomarker status cannot be assumed.',['Phase 1: Subjects with advanced or metastatic solid tumors who have failed standard therapy or have no standard treatment.','or other solid tumor types with the best clinical response observed from Phase 1'],biomarker='No tumor biomarker enrollment gate stated for Part 1. Part 2 named carcinomas require EGFR/MET/VEGF alteration or expression; applicability to an SS expansion is unresolved.',uncertainty='Registry calls Parts 1/2 phases although design phase is PHASE1. Actual expansion selection and any SS biomarker requirements unknown.')
add('NCT05949125',{'DSRCT':X},['Both phase-1a escalation and phase-1b expansion are CD123+ AML; MRD+ AML remains AML.'],'Neither CD123 nor a myeloid sarcoma term establishes DSRCT eligibility.',['Participants with CD123+ AML'],biomarker='CD123 threshold and HLA matching apply to AML; not a DSRCT molecular pathway.',restriction='closed AML histology domain')
add('NCT07030959',{'DSRCT':B},['Parts A/B monotherapy and Part C cetuximab combination operate within solid-tumor scope, but each has unspecified KRAS details.'],'Broad solid-tumor scope is conditional on additional KRAS alteration; DSRCT alone does not establish it, and part-specific rules are missing.',['Patients with Kirsten rat sarcoma (KRAS) alteration confirmed by local tests or central laboratory test (Details are defined for each part)'],biomarker='Additional KRAS alteration required and unestablished; defining EWSR1::WT1 does not satisfy it.',uncertainty='Exact eligible KRAS variants, part-specific histologies and additional full-protocol criteria unavailable; cohort compatibility beyond umbrella scope unresolved.')
add('NCT06979596',{'DSRCT':X},['Cohort A HR+/HER2- breast carcinoma; B high-grade epithelial ovarian/fallopian/peritoneal carcinoma; C low-grade endometrioid carcinoma.','Experimental, endocrine comparator and observation groups inherit those cohort restrictions; no DSRCT route.'],'Peritoneal carcinoma and carcinosarcoma should not be conflated with DSRCT. All relevant cohorts are restricted.',['Has histologically confirmed high-grade epithelial','other types of pure sarcomas, and adenosarcomas are not eligible.'],restriction='closed carcinoma histology lists; direct pure-sarcoma exclusion in C',biomarker='Cohort-specific endocrine/histologic features do not establish a DSRCT pathway.')
add('NCT07686367',{'SS':E},['Single brenetafusp cohort includes molecularly confirmed SS and myxoid/round-cell liposarcoma.'],'SS scope is explicit. HLA-A*02:01 is required; PRAME positivity appears in study aims, but the saved eligibility does not define a PRAME cutoff or testing gate.',['Patients must have metastatic or unresectable synovial sarcoma','Patients must be HLA-A'],biomarker='HLA-A*02:01 required and unestablished. PRAME-positive target population in descriptions; precise enrollment assay/threshold unresolved, not assumed.',uncertainty='PRAME enrollment requirement cannot be reconciled completely from saved text; no external protocol. Prior TCR-T and PRAME-directed therapies excluded.')
add('NCT04282044',{'SS':X},['Monotherapy and combination cohorts share one-of-eight allowed tumor list; no SS arm.'],'Osteosarcoma in the positive list is not permission for all sarcomas. Broad title and combination-arm shorthand defer to the explicit histology list.',['Subjects must have histologically confirmed diagnosis of one of the following tumors:'],restriction='closed allowed histology list')
add('NCT05687136',{'EMC':B,'DSRCT':B,'SS':B},['Both escalation and expansion require broad solid malignancy plus approved molecular/IHC alteration.','SS18 is named among SWI/SNF mutations, but SS18::SSX fusion is not explicitly stated as accepted. Other listed alteration routes remain available in principle to all three diagnoses.'],'The diagnosis itself does not establish the additional molecular gate. SS18 mention cannot be promoted to proven defining-fusion compatibility or treated as an exclusion.',['SWI/SNF member mutation (ARID1A, PBRM1, SMARCA4, ARID2, ARID1b, SMARCB1, SMARCA2, SS18)','All mutations/alterations must be approved by the overall principal investigator (PI).'],biomarker='Additional qualifying ATM/MYC/FBXW7/CCNE1/SWI-SNF/ATRX-DAXX alteration or IHC finding required and unestablished for each diagnosis. SS18 mutation versus SS18::SSX fusion acceptance unresolved.',uncertainty='List syntax (including conjunctions) and PI-approved molecular acceptance require clarification; do not infer that every named alteration co-occurs or that fusion equals mutation. Paired biopsy required in expansion unless exempted.')
if __name__=='__main__':
 pkt=load(REPAIR/'review-packet.json');sel=load(REPAIR/'selection.json');assert set(J)==set(pkt)
 members={}
 for s in sel['strata']:
  for n in s['selected_ids']:members.setdefault((s['diagnosis'],n),[]).append({'set':'metadata','stratum':s['stratum']})
 for a in sel['challenge_anchors']:
  for d in a['diagnoses']:members.setdefault((d,a['nct_id']),[]).append({'set':'challenge','stratum':'anchor'})
 evidence=[];readlog=[];cache={};refids={}
 modules=['eligibilityModule','descriptionModule','armsInterventionsModule','conditionsModule','designModule','statusModule']
 for n,v in pkt.items():
  raw=Path(ROOT/v['source']).read_bytes();assert sha(raw)==v['source_sha256']
  if v['source'] not in cache:cache[v['source']]=json.loads(gzip.decompress(raw))
  record=resolve(cache[v['source']],v['pointer']);assert record==v['record']
  p=record['protocolSection'];refids[n]=[]
  for m in modules:
   if m not in p:continue
   ptr=v['pointer']+'/protocolSection/'+m
   value=p[m];canonical=json.dumps(value,ensure_ascii=False,sort_keys=True,separators=(',',':'))
   eid=n+':'+m;refids[n].append(eid)
   evidence.append({'evidence_id':eid,'source':v['source'],'source_sha256':v['source_sha256'],'pointer':ptr,'value':value,'value_canonical_sha256':sha(canonical.encode())})
  qrefs=[]
  criterion=p['eligibilityModule']['eligibilityCriteria']
  for qi,q in enumerate(J[n]['decisive_quotes']):
   assert q in criterion,(n,q)
   start=criterion.index(q);eid=n+':quote:'+str(qi);qrefs.append(eid)
   evidence.append({'evidence_id':eid,'source':v['source'],'source_sha256':v['source_sha256'],'pointer':v['pointer']+'/protocolSection/eligibilityModule/eligibilityCriteria','excerpt':q,'start_codepoint':start,'end_codepoint':start+len(q),'excerpt_utf8_sha256':sha(q.encode())})
  refids[n]+=qrefs
  readlog.append({'nct_id':n,'complete_saved_eligibility_read':True,'complete_saved_description_read':True,'all_saved_arms_and_interventions_read':True,'conditions_design_status_read':True,'source_verified_against_packet':True,'missing_modules':[m for m in modules if m not in p],'eligibility_chars':len(criterion),'reading_note':'Systematic packet reads in current fresh session; truncated tool sections were reread separately. Raw gzip record equality verified before freeze.'})
 labels=[]
 for (d,n),ms in sorted(members.items()):
  a=J[n];p=pkt[n]['record']['protocolSection'];label=a['labels'][d]
  labels.append({'pair_id':d+'|'+n,'diagnosis':d,'nct_id':n,'memberships':ms,'label':label,'eligibility_scope':{'level':'disease/cohort registry scope, not patient eligibility','label':label,'cohort_reconciliation':a['cohort_reconciliation'],'rationale':a['rationale'],'restriction_type':a['restriction_type']},'extra_biomarker_requirement':{'state':'unestablished_or_not_applicable_see_detail','detail':a['extra_biomarker_requirement']},'protocol_uncertainty':a['protocol_uncertainty'],'recruitment_uncertainty':a['recruitment_uncertainty'],'current_availability':{'overall_status_snapshot':p['statusModule']['overallStatus'],'current_as_defined_in_frozen_sample':p['designModule']['studyType']=='INTERVENTIONAL' and p['statusModule']['overallStatus'] in ['RECRUITING','NOT_YET_RECRUITING','ENROLLING_BY_INVITATION'],'site_and_cohort_current_availability':'unverified','status_module_evidence':n+':statusModule'},'clinical_trial_purpose':{'task_domain':a['task_domain'],'registry_study_type':p['designModule']['studyType'],'registry_primary_purpose':p['designModule'].get('designInfo',{}).get('primaryPurpose'),'phases':p['designModule'].get('phases',[]),'interpretation':a['purpose_interpretation']},'all_other_constraints':'Full eligibility module is retained verbatim; age, organ function, treatment history, location, disease status and investigator judgment remain unassessed for an individual.','evidence_ids':refids[n]})
 assert len(labels)==49 and len(readlog)==37
 dump('source-evidence.json',{'evidence':evidence,'encoding':'UTF-8; offsets count Unicode codepoints; JSON value hash uses sorted compact canonical serialization'})
 dump('reading-log.json',{'completed_utc':now(),'trials':readlog,'trials_read':37,'unreviewed_ids':[]})
 dump('independent-labels.json',{'version':'1-frozen-independent','created_utc':now(),'reader':'Fresh independent model session; not clinical/human review','diagnosis_scope_assumptions':{'EMC':'Supplied extraskeletal myxoid chondrosarcoma molecular scope; EWSR1/TAF15 FET-partner subsets do not imply all EMC.','DSRCT':'Supplied EWSR1::WT1 defining fusion.','SS':'Supplied SS18::SSX defining fusion; not an EWS/FET fusion.'},'prior_labels_read':False,'unit':'unique diagnosis-trial pair','pairs':labels,'unreviewed_ids':[]})
 names=['contract.json','reading-label-protocol.json','independent_judgments.py','independent-labels.json','source-evidence.json','reading-log.json']
 dump('independent-freeze-receipt.json',{'frozen_utc':now(),'prior_labels_opened_before_freeze':False,'sha256':{n:sha((OUT/n).read_bytes()) for n in names},'input_sha256':{n:sha((REPAIR/n).read_bytes()) for n in ['label-protocol.json','selection.json','freeze-receipt.json','review-packet.json']},'counts':{'unique_pairs':49,'distinct_trials':37,'metadata_memberships':33,'challenge_memberships':18,'overlap_pairs':2}})
 print('Independent labels and exact raw evidence frozen:',len(labels),'pairs',len(evidence),'evidence objects')
