"""Reproduce source-identity evaluation without fitting pharmacologic effects."""
from pathlib import Path
from xml.etree import ElementTree as E
import json,hashlib,re,datetime
R=Path(__file__).resolve().parent
P=Path('C:/Projects/EMC-Research')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,x):(R/n).write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
def txt(e):return ' '.join(e.itertext()) if e is not None else ''
def table(x,index=0):return [[' '.join(c.itertext()) for c in row if c.tag in ['td','th']] for row in x.findall('.//table-wrap')[index].findall('.//tr')]
qs=[]
for n in ['functional-primary.json','broader-title-metadata.json','broader-title-page2.json']:
 d=json.loads((R/n).read_text(encoding='utf-8'));qs.append({'file':n,'hit_count':d['hitCount'],'returned':len(d['resultList']['result']),'sha256':sha(R/n)})
a=json.loads((R/'broader-title-metadata.json').read_text(encoding='utf-8'))['resultList']['result']+json.loads((R/'broader-title-page2.json').read_text(encoding='utf-8'))['resultList']['result']
assert len(a)==1450 and len({(r['source'],r['id']) for r in a})==1450
save('title-candidates.json',{'scope':'Title screen only; not full scientific evaluation of1450papers','candidates':[r for r in a if re.search('sarcoma',r['title'],re.I) and re.search('model|organoid|xenograft|screen|precision|tumoroid|ex vivo|drug',r['title'],re.I)]})
ala=E.parse(R/'ala2022.xml').getroot(); rows=table(ala)
emc=[r for r in rows if len(r)>3 and r[3]=='EMC'];assert len(emc)==1
assert emc[0]==['4','19','F','EMC','–','Primary','Res','Chemo','80%','14','2','10','7','Pos (+)','0']
ala_sections={s.findtext('title',''):txt(s) for s in ala.findall('.//sec') if s.findtext('title','') in ['CAM model, photodynamic detection (PDD) and therapy (PDT)','Criteria for evaluating PDD results','Histopathological effects of photodynamic therapy (PDT)']}
assert 'A meaningful interpretation of PDT-associated histological tumor necrosis was not possible' in ala_sections['Histopathological effects of photodynamic therapy (PDT)']
assert not ala.findall('.//supplementary-material')
save('ala-source-evaluation.json',{'doi':'10.1186/s13018-022-02931-x','source_sha256':sha(R/'ala2022.xml'),'all_Table1_rows':rows,'all_Table2_rows':table(ala,1),'eligible_author_labelled_EMC_rows':emc,'EMC_donors':1,'model_authentication':'Author histology label and histological confirmation of grafts; no NR4A3-fusion identity released in evaluated main text. Do not relabel or presume molecular confirmation.','conditions':'Published row:14eggs,2samples per egg,10evaluable eggs,7histology-confirmed, qualitative5ALAfluorescence+,zero contaminated. Not14donors or14drugresponses. Generic protocol specifies5ALA2mg/200uL with4h incubation and untreated controls; case-level control/PDD/PDT/dose/viability map not released.','specificity':'Benign and borderline tumors also fluoresce; fluorescence is not tumor-specific killing. Background and spontaneous regression confound PDT.','author_interpretation':'PDT necrosis not interpretable because spontaneous regression; no EMC-specific controlled PDT effect reported.','novelty_value':'Already-published one-donor qualitative observation; no new vulnerability or replicated selectivity finding.','source_sections':ala_sections})
inbrx=E.parse(R/'inbrx2023.xml').getroot(); ip=[txt(p) for p in inbrx.findall('.//body//p') if any(t in txt(p) for t in ['H-EMC-SS','CTG-1255','CTG-2383'])]
assert any('consistent with conventional chondrosarcoma' in t for t in ip)
shared=E.parse(R/'shared2026.xml').getroot();cellsec=next(s for s in shared.findall('.//sec') if s.findtext('title')=='Cells');ct=txt(cellsec)
models=['SW1353','CAL78','HEMCSS','HT1080','SW982','SYO-1','HS-SYII','A4573','EW8','TC32','TC71','Lipo224A','Lipo573B','Lipo863B','Lipo246','PLS-1','MLS-1765-92','MLS-402-91','DL-221','LM7']
assert all(v in ct for v in models) and len(set(models))==20
save('disputed-model-evaluation.json',{'INBRX109':{'doi':'10.1158/1078-0432.CCR-23-0974','source_sha256':sha(R/'inbrx2023.xml'),'actual_evaluation':'All H-EMC-SS primary method/result paragraphs and Figure2caption read: bivalent/TRAIL/tetravalent/hexavalent binding,16h viability, caspase3/7 with/without pan-caspase inhibitor. Published positive apoptosis measurements retained as author-labelled-model results, not authenticated EMC dependence.','source_paragraphs':ip,'PDX':'CTG-1255 andCTG-2383 explicitly conventionalchondrosarcoma;8mice/group do not establish8donors orEMC efficacy.','clinical':'Table1one investigator-labelledEMC; footnote chondrosarcoma-like diagnosis; ownergenomic_clinical evaluated separately. No fusion/outcome bridge inferred.'},'shared2026':{'doi':'10.1158/2767-9764.CRC-26-0142','source_sha256':sha(R/'shared2026.xml'),'all20models':models,'source_cells_section':ct,'interpretation':'HEMCSS is CVCL_1238, the same disputed H-EMC-SS resource, not a new independent EMC donor. Generic CS grouping does not authenticateNR4A3; no numericalEMC effect fit.','pending':'Model identity remains unresolved; all1387drugresponse values/supplement conditions are not evaluated asEMC. They are pending if identity and worthwhile question become established, not negative evidence.'}})
bone=E.parse(R/'bone2026.xml').getroot(); br=table(bone);assert len(br)==12
mini=E.parse(R/'minopoli2020.xml').getroot();mr=table(mini);assert len(mr)==19
hdac=E.parse(R/'hdac2025.xml').getroot();hs={s.findtext('title',''):txt(s) for s in hdac.findall('.//sec') if s.findtext('title','') in ['Cells and culture media','Ethics and clinical samples']}
save('new-cohort-identities.json',{'bone2026':{'doi':'10.1007/s12094-026-04261-4','source_sha256':sha(R/'bone2026.xml'),'all11Table1rows':br[1:],'scope':'Main full cohort explicitly OS/Ewing, no authenticatedEMC; pairedadherent/spheroidconditions not additionaldonors.'},'minopoli2020':{'doi':'10.3390/cells9041062','source_sha256':sha(R/'minopoli2020.xml'),'all18Table1rows':mr[1:],'scope':'Primary fulltext evaluates conventional/dedifferentiated boneCHS, organotypiccultures from#8/#16; noEMC response authenticated. S-CMO9316 genericmetastaticCHS links thispublication but lacks exactcase crosswalk.'},'hdac2025':{'doi':'10.1080/15384047.2025.2589666','source_sha256':sha(R/'hdac2025.xml'),'actual_source_sections':hs,'scope':'UPS/LMS models includingnewEDI-UPS-1/EDI-LMS-1; no authenticatedEMC in specifiedfunctionalcohort.'}})
reuse=[]
for rel in ['research/autonomy/fresh-discovery-2026-10-04/functional/RESULTS.txt','research/autonomy/fresh-discovery-2026-10-04/functional/COVERAGE.txt','research/autonomy/fresh-discovery-2026-10-04/functional/HANDOFF.txt','research/autonomy/fresh-discovery-2026-10-04-round3/functional_discovery/RESULTS.txt','research/autonomy/fresh-discovery-2026-10-04-round3/functional_discovery/COVERAGE.txt','research/autonomy/fresh-discovery-2026-10-04-round6/nr4a3_regulatory/HANDOFF.txt']:
 p=P/rel;reuse.append({'path':str(p),'bytes':p.stat().st_size,'sha256':sha(p),'scope':'unchanged prior evaluated evidence and explicit gaps reused; no drug reanalysis'})
save('reused-evidence.json',reuse)
save('evaluation.json',{'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'decision':'SHELVE standalone R7functionalmodel proposal','new_demonstrated_EMC_findings':[],'numeric_biology_pilot':False,'source_gate':'New published one-donorCAMobservation is not a novel controlledvulnerability. New broaderscreens do not establish an independent authenticatedEMC comparison; unresolvedsourceidentity remainsvisible.','queries':qs,'complete_broader_metadata_rows':1450,'limits':'Metadata completion is not complete scientific evaluation. No globalabsence/exhaustion or drugresistance claim. Source gaps blockpromotion.','reopen':'Specific authenticEMC model/condition/casecrosswalk with measuredcontrols and consequential unansweredcomparison; resolve allpublicconditions and obtainindependentreview.'})
print(json.dumps({'EMC_CAM_rows':len(emc),'bone_rows':len(br)-1,'minopoli_rows':len(mr)-1,'shared_models':len(models),'broader_metadata_rows':len(a),'new_finding':False}))