"""Hash-bind scoped independent scientific review to the actual inspected sources."""
from pathlib import Path
import json,hashlib,datetime
P=Path(__file__).resolve().parent
I=Path('C:/Users/mcrae/.codex/worktrees/emc-fresh-20261004-microenvironment/research/autonomy/fresh-discovery-2026-10-04-round3/immune')
names=['RESULTS.md','COVERAGE.md','AMENDMENT-20261004.txt','moura2024-text.txt','moura2024.pdf','moura-supp-tables.json','starzer2021.xml','starzer2021-supp-text.txt','PMC7993298-jitc-2020-001458supp001.pdf','PMC7993298-jitc-2020-001458supp002.xlsx','starzer-main-06.png','starzer-main-7.png','starzer-supp-4.png','moura-main-39.png','moura-main-40.png']+[f'moura-ccr-24-1782_supplementary_figure_s{i}_suppsf{i}.png' for i in range(1,6)]
out={'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'review_scope':'Diagnosis, repeated donors, response definitions and whether released paired measurements expose EMC identity; not full newliterature census.','status':'Provisional only for additional Pollack/Kelly sources under active recovery. Prior reviewed findings and correction below are complete.','observations':[
'Moura originalTable1 has4centraldiagnosisEMC,3pairedtranscript and3pairedblood records. The3+3sets cannot be assumed identical. VisualFig1/2 andall5suppfigures have no EMC-specificpointIDs. SupplementaryTables1-4 are pan-sarcoma summary/results, not patient-level assay values. Request-only data sentence verified in source.',
'MouraS1 explicitly shows total paired assays; S2/S4 use MAXSTAT-derived PFS cuts. Do not retrofit these cuts as prespecified EMC biomarkers. S3 has real paired solubleprotein changes, but nohistologylabels; S5 cannot substitute LMSexperimental cultures forEMC.',
'Starzer supplementcenter1case7 is authors histologicEMC label, male54,hip,pembrolizumab,bestiRECISTPD,PFS3months. No fusion confirmation found in methods. Case5 is myxoidchondrosarcoma/ribs and remains unresolved, despite PD/PFS5.9.',
'Starzer mainFig2/3 andsuppS3 visually have no patientIDs. PublicXLSX sheetsS4(2456x9),S5(24x7),S6(81x7) are differentialprobe/pathway outputs, not patient-level immune/methylation matrix. Cannot map case7 into heatmap byguessing. Fig3 selectedDMP-basedclusters are not independent validation; Fig2 uses all704003probes and should not be conflated with Fig3.',
'Schur2017 andStarzer2021 may repeat Vienna patients; no compatible donorcrosswalk recovered. Do not sum as independent. IMMUNOSARC I/II use sameNCT03277924 and II is an extension/stage2, not a distinct registration demonstrating independentpatients.',
'One material correction sent and accepted: replace distincttrial wording with stage2extension sameNCT03277924. Sources https://clinicaltrials.gov/study/NCT03277924 and https://www.hra.nhs.uk/planning-and-improving-research/application-summaries/research-summaries/immunosarc-2-protocol-version-7/. CurrentRESULTS/COVERAGE incorporate correction.',
'Scoped shelving is warranted for currently linkedmeasurement question, not evidence of immunotherapy inefficacy or proof no publiccrosswalk exists. Pending accessible supplements may alter feasibility and must be finished/dispositioned before advancement.'], 'files':[{'path':str(I/n),'bytes':(I/n).stat().st_size,'sha256':hashlib.sha256((I/n).read_bytes()).hexdigest()} for n in names]}
(P/'independent-immune-review.json').write_text(json.dumps(out,indent=2),encoding='utf8')
print('Bound',len(names),'reviewed source/result files')
